### ISSUE TITLE
Need margin between "View items as" header and its options

### ISSUE THREAD

**Issue by ggeisler** [sul-dlss/sul-embed#1014]
Great to see the plugins in the SUL version of the embed. I noticed, though, that the whitespace between the first header of the Window options menu and its options disappeared (the margin is there in other instances):

<img width="423" alt="Screen Shot 2019-06-07 at 4 02 14 PM" src="https://user-images.githubusercontent.com/101482/59137743-141e0480-893e-11e9-8094-fc6aaf3f3a22.png">

Should be similar whitespace as after the "Show thumbnails" heading.

**Comment by mejackreed** [comment]
I think this has to do with the vertical height of the options menu. When the viewer is vertically smaller it will scroll but "View items as" is sticky. 

Should it not be sticky?

**Comment by ggeisler** [comment]
Ah, yeah, you're right, I didn't catch that.

I don't think it should be sticky. Because if there was even less height (or more options) and we could scroll a bit more, it seems like we could get a situation where half the option icons could be scrolled under the heading:

<img width="360" alt="Screen Shot 2019-06-07 at 4 42 12 PM" src="https://user-images.githubusercontent.com/101482/59138662-3fefb900-8943-11e9-8384-a9a5644a4245.png">


We do plan to suggest increasing the height of the embed in PURL a bit, so the scrolling should go away then, which would hide the issue, but we might also eventually add more options, so the issue could come back. So maybe eliminating the stickiness is the best approach.

(JV and I also discussed splitting out the View items and Show thumbs option to their own menu, which would really solve the problem, but until we decide that for sure, we probably should address the current issue.)
