### ISSUE TITLE
Hide annotations panel?

### ISSUE THREAD

**Issue by ggeisler** [sul-dlss/sul-embed#1016]
@jvine pointed out that maybe in the SUL environment the annotations panel is never going to be populated. @caaster or @anarchivist do you know whether it's the case that no SDR items have annotations?

If that is true, we could update the embed configuration to:

```
window: {
  hideAnnotationsPanel: true;
}
```

and not show a useless annotations sidebar category for all of our objects.

**Comment by mejackreed** [comment]
Yes this is correct. We do not have any annotations linked in manifests we return from Purl.

**Comment by ggeisler** [comment]
Thanks @mejackreed. In that case it would be great to hide the annotations panel, both to reduce visual clutter and to avoid misleading users into thinking there is something to see in that panel.

Obviously it's easy enough to turn the panel back on in the future if circumstances change.

**Comment by blalbrit** [comment]
Agreed with above cc. @caaster . We don't have any way of linking annotation lists from PURL/IIIF manifests (unfortunately). Please keep in mind that Parker on the Web does, however, as it uses external manifests to allow for this.
