### ISSUE TITLE
Query pass-through scenario B: Navigate via prepared search link

### ISSUE THREAD

**Issue by ggeisler** [sul-dlss/sul-embed#1022]
Related to #1018. (In the mockup below, I'm showing the viewer in standalone mode for mockup convenience; just imagine it is in embed viewer mode, at the top of an exhibits item detail page instead.)

- [x] If the context of a search results page includes a text (as opposed to a facet) query, (based on there being a q= parameter value or whatever), add a new, "prepared search link" (B in the mockup below) just above the expandable snippets section. The link text is `Search for "<query terms>" in document text`, where we plugin the `q=` terms used in the query that produced the application's results page. Use  `body 1` typography for the link. It looks like the element should be a `<dt>`, since we're adding this link within an existing `<dl>`.

- [x] (This task item assumes that we will **not** have to show the Attribution panel by default.) When selected, this link opens the item detail page with the viewer at the top. The viewer should open with the search panel displayed, with a content search using the passed-through query terms executed.

- [x] Display a notification dot next to the side panel menu search icon, similar to what we do with the annotations icon when a document canvas has annotations.

<img width="1239" alt="Screen Shot 2019-06-17 at 12 40 27 PM" src="https://user-images.githubusercontent.com/101482/59631635-2990ec80-90fd-11e9-81c4-00ff9b3ec5e7.png">

**Comment by jvine** [comment]
Around the post-standup discussion about the opening state of the sidebar: the requirement to include the "prepared search" link with an indicator in the sidebar does not imply that we need to expose the sidebar. We don't force the sidebar open when annotations are present, though we show an indicator if the sidebar is open; same applies to a not-explicitly-passed-through search term. 

According to the screenshots in #1026, suppressing the rights panel has been implemented as intended:  to show no sidebar, no open panels on first load. User must click the toggle to open the sidebar in its default state (information panel open), and at that point will see the indicator on the search icon.

If they have *explicitly* passed through a search, the search panel is open on load.
