### ISSUE TITLE
Query pass-through scenario C: Navigate via snippet

### ISSUE THREAD

**Issue by ggeisler** [sul-dlss/sul-embed#1023]
Related to #1018.

We currently include a "sample snippets" section in each result item on the search results page of relevant exhibits:

<img width="690" alt="Screen Shot 2019-06-17 at 1 00 35 PM" src="https://user-images.githubusercontent.com/101482/59632841-0582da80-9100-11e9-8117-5c687eb31e6a.png">

As part of the new query pass-through scenarios, it seems useful to enable the user to select a specific snippet and be taken to the embed viewer directly to the page of the document with that snippet.

I don't think can actually use content search to navigate directly to the snippet, but do we have any parameters associated with each snippet that we can leverage to enable this scenario? For example, do we know the canvas a snippet is on when the snippets are returned?

The goal is to enable the user to select a link associated with a snippet shown in the exhibit search results (e.g., the "[view >>]" link in the mockup below) and be taken to the exhibit item's detail page with the viewer open to the search panel (empty search context). For example, assume that the second snippet in the mockup on the left is on page 35 of the document. The user selects the "[view >>]" link associated with snippet 2 and is taken to the viewer with page 35 displayed:

<img width="1475" alt="Screen Shot 2019-06-17 at 1 10 42 PM" src="https://user-images.githubusercontent.com/101482/59633534-87273800-9101-11e9-93e2-b46944606f41.png">

If we do know the canvas each snippet is associated with, then this is possibly related to https://github.com/ProjectMirador/mirador/issues/2664.

**Comment by cbeer** [comment]
I can confirm we don't currently have the necessary information in the exhibits index to drive this behavior.
