### ISSUE TITLE
Update viewer configuration/instantiation related to Attribution panel

### ISSUE THREAD

**Issue by ggeisler** [sul-dlss/sul-embed#1024]
Based on conversations with @caaster and @mejackreed it seems the requirement for users to see the attribution information applies only to the Warhol collection (possibly Bassi, but it is okay to assume not unless and until we hear from them, and for sure not FRDA), and Jack thinks it is possible to deal with objects from a collection as a special case when showing the viewer. This seems to open up a new approach where we can:

- [x] Change the default configuration of the viewer to show no open panels.

- [x] If we know we are loading an object from Warhol (https://purl.stanford.edu/dc876nn4469), open the Attribution panel when the viewer is instantiated.

- [x] If we are dealing with a request via the "prepared search link" in #1022, open the Search panel when the viewer is instantiated, as described in that ticket.

@mejackreed Please correct me if I misinterpreted your thoughts.

@jvine Let us know if any of this doesn't seem like a good idea to you.

**Comment by jvine** [comment]
Agree with this, but also wonder if this one collection might be remediated to require the clickthrough auth pattern at some point (same for Bassi). 

Also, yay.

**Comment by ggeisler** [comment]
Good point. The clickthrough pattern feels like the correct way to handle it, for sure.

**Comment by jkeck** [comment]
I believe this has been resolved.  Please re-open if I've missed something.

**Comment by caaster** [comment]
I've verified that the following two items are working as expected in UAT:
- Change the default configuration of the viewer to show no open panels.
- If we know we are loading an object from Warhol (https://purl.stanford.edu/dc876nn4469), open the Attribution panel when the viewer is instantiated.

When M3-to-sul-embed is in prod, and PRs have been pushed to exhibits/new prod release, I will be able to verify:
- If we are dealing with a request via the "prepared search link" in #1022, open the Search panel when the viewer is instantiated, as described in that ticket.
