### ISSUE TITLE
In IE 11, the scrollTo widget scrolls the whole browser window, not just the immediate scrollable container

### ISSUE THREAD

**Issue by cbeer** [sul-dlss/sul-embed#1035]
### Browser / Environment
 MS Edge 42

**Comment by jkeck** [comment]
I'm gonna take a quick try at a polyfill.

**Comment by jkeck** [comment]
`smoothscroll-polyfill` didn't pan out and didn't change the behavior at all (which may be expected since IE/Edge does have the feature, just implements it in a weird way)

**Comment by mejackreed** [comment]
Confirmed that Edge is fixed (80) but issue is present in IE11

**Comment by jcoyne** [comment]
IE is EOL, so closing.
