### ISSUE TITLE
Getting an error on download

### ISSUE THREAD

**Issue by blalbrit** [sul-dlss/sul-embed#1047]
### Expected behavior
When clicking on the download option, should be delivered a downloadable jpeg

### Actual behavior
Get a "this page isn't working" error. See below from https://stacks.stanford.edu/image/iiif/qb472dd2140%2FSt-Petersburg-ns-23%2C-f.-12a/full/372,/0/default.jpg?download=true
![Screenshot 2019-07-01 17 28 20](https://user-images.githubusercontent.com/796990/60474294-f171c980-9c25-11e9-81b4-687d1d6b1e07.png)

compare this with the same IIIF URL without ?download=true: https://stacks.stanford.edu/image/iiif/qb472dd2140%2FSt-Petersburg-ns-23%2C-f.-12a/full/372,/0/default.jpg which delivers the image as expected
![Screenshot 2019-07-01 17 28 37](https://user-images.githubusercontent.com/796990/60474322-19f9c380-9c26-11e9-8a40-6113c7f945cd.png)

### Steps to reproduce the behavior
1. Go to PURL https://purl.stanford.edu/qb472dd2140
2. Select Download from Window Options
3. Click on a size to download

### Browser / Environment
Chrome Version 75.0.3770.100
macOS Sierra 10.12.6

**Comment by blalbrit** [comment]
Could be the depositor's filenaming `St-Petersburg-ns-23,-f.-11b.jp2` ? Not sure why that would not impact viewing but only download.

**Comment by blalbrit** [comment]
Same issue with https://purl.stanford.edu/ks035ts6306

**Comment by blalbrit** [comment]
No problem with download in UV: http://universalviewer.io/uv.html?manifest=https://purl.stanford.edu/qb472dd2140/iiif/manifest

**Comment by cbeer** [comment]
This seems like a browser-specific issue with Chrome; Firefox + Safari behave normally.

**Comment by cbeer** [comment]
I think Chrome doesn't like commas in the file name. We'll have to read the spec and see what, if any, escaping can be done here.

**Comment by jkeck** [comment]
We could remove the `?download=true` flag in the meantime.  I'm not sure why the download path causes the failure while the other doesn't, but it would still allow users to download the images in the meantime.
