### ISSUE TITLE
Border on embedded viewer not displaying

### ISSUE THREAD

**Issue by ggeisler** [sul-dlss/sul-embed#1055]
Not sure if this was discussed while I was away but I'm not seeing a border around the viewer, although it appears there is a 1px border defined in the CSS:

<img width="1224" alt="Screen Shot 2019-07-05 at 1 40 43 PM" src="https://user-images.githubusercontent.com/101482/60744437-be338100-9f2a-11e9-9479-b4e99a65b608.png">

I think we need the border to display to give the viewer a clear visual definition, especially on the sides of the titlebar and the left side where the side panel menu just bleeds into the application background.

**Comment by ggeisler** [comment]
FWIW here's a screenshot of how the viewer looked in a Purl page before the IIIF conference (I made this for the User workshop slides):

<img width="1055" alt="Screen Shot 2019-07-10 at 4 03 28 PM" src="https://user-images.githubusercontent.com/101482/61010745-6a5ed880-a32c-11e9-9437-c49ae7b566b6.png">

It looks like it either had a border or a shadow to give the edges definition. Definitely is different from how it looks on a Purl page now (e.g. compare the edges of the white title bar).

**Comment by camillevilla** [comment]
What's the desired border styling?

**Comment by camillevilla** [comment]
(specifically: do we like the shadow-y border thing? )

**Comment by ggeisler** [comment]
Yes, if you can get something that looks very similar to the screenshot, which does appear to have a slight shadow, I think that might work well. Though we might reserve final judgment until we can see it in real context.
