### ISSUE TITLE
download issue with image thumbnail

### ISSUE THREAD

**Issue by hannahfrost** [sul-dlss/sul-embed#1078]
User feedback about an error with accessing an image is leading to some questions about a stacks URL error and discrepancy with IIIF manifest.

Object: https://purl.stanford.edu/rv052vk1828

First, note that the rights on this image as currently expressed in rightsMD  are marked as no-download and this is known to be incorrect; it should be downloadable and that will be corrected. 

However, the current user experience with the no-download settings in place is not correct/bad and it would be good to know how it may have gotten to this state and how it could fail more gracefully. I'm also wondering if there are other thumbnails in this state, if is possible to find/fix them, and if there is a more graceful behavior and message for the user if the stacks URL accessed via the download link is malformed along these lines. 

Could this happen if the item is published as no-download in some ad hoc fashion (which may have been the case) without some other critical workflow happening? Or something else?

### Expected behavior

A user should be able to download a thumbnail (400x) from an object with no-download settings by clicking the thumbnail file link in the download panel in sul-embed.

### Actual behavior

Upon clicking the link in the download panel, a user gets a black screen with a small empty square. See screenshot. There is no error message indicating that there is a problem. The stacks URL is https://stacks.stanford.edu/image/iiif/rv052vk1828%2Frv052vk1828_0001/full/400,/0/default.jpg?download=true.

<img width="844" alt="Screenshot 2019-09-15 17 53 39" src="https://user-images.githubusercontent.com/1801076/64930125-78285280-d7e2-11e9-9a4d-36662b0df844.png">

However, the IIIF manifest for the item (https://purl.stanford.edu/rv052vk1828/iiif/manifest) is correct with regards to the thumbnail; it contains the link to the thumbnail, which is in stacks:
https://stacks.stanford.edu/image/iiif/rv052vk1828%2Frv052vk1828_0001/full/!400,400/0/default.jpg

### Browser / Environment
Version 76.0.3809.132

**Comment by cbeer** [comment]
Thanks @hannahfrost; there was an issue with our mirador download plugin and restricted, portrait-aspect-ratio, no-download images.

**Comment by hannahfrost** [comment]
Thanks for taking care of that!
