### ISSUE TITLE
M3 UX feedback 

### ISSUE THREAD

**Issue by anarchivist** [sul-dlss/sul-embed#1083]
From Kris K.:

> The new viewer generally is a bit confusing and navigation buttons are hidden or very light/no contrast so they don't show up.
> The panel with the search function is also "hidden" but findable by being curious and looking under the three lines in the corner.
> I'm having a hard time finding how to download the pdfs from the viewer (checking to see if the pdf will download is part of the QA checklist) - after looking at 15 objects, and by pure whim, I discovered that the three dots in a line contains the download option. But then it appears I cannot download the entire pdf? Just one page at a time? Is there another way to do this?

See also #1082

**Comment by mejackreed** [comment]
@anarchivist is this resolved now that #1082 is shipped and we updated the button design?

**Comment by anarchivist** [comment]
Yes, I think so. Thanks!
