### ISSUE TITLE
iFrame widget not sizing height as expected

### ISSUE THREAD

**Issue by ggeisler** [sul-dlss/sul-embed#1109]
When copying iFrame code from the Mirador3 Share modal and then adding it to the iFrame widget in Spotlight, the height of the iFrame is not respected. @jkeck thinks it might be related to the lack of the "maxheight" attribute on the provided iframe code.

Here's what I get when using the 4 available sizes in Spotlight:

![Screen Shot 2020-02-10 at 4 58 13 PM](https://user-images.githubusercontent.com/101482/74204633-d68a1d80-4c28-11ea-9be3-05970f430c4b.png)

**Comment by jkeck** [comment]
This has been resolved in SUL Embed.
