### ISSUE TITLE
Zoom buttons in sul-embed viewer do not work

### ISSUE THREAD

**Issue by caaster** [sul-dlss/sul-embed#1167]
### Expected behavior
Zoom buttons in sul-embed viewer should zoom in and zoom out.

### Actual behavior
When I click on the "plus" or the "minus" controls on the sul-embed viewer, the image disappears.

### Steps to reproduce the behavior
When I click on the "plus" or the "minus" controls on the sul-embed viewer, the image disappears.
NOTE: the zoom does work if you use the mouse wheel instead.

### Browser / Environment
Chrome, Safari & Firefox all produce the same behavior.

**Comment by camillevilla** [comment]
A fix has been deployed, but it may take a hard refresh for the fixed viewer to load.
