### ISSUE TITLE
Design for full object download

### ISSUE THREAD

**Issue by mejackreed** [sul-dlss/sul-embed#1187]
A placeholder ticket for design needed to present "full object download" url to end users in a sul-embed context.

We may want to consider support for:

pdf, image, geo, and 3d viewer concepts.

**Comment by ggeisler** [comment]
@mejackreed Is it technically feasible to customize the label for the "full object download" link based on the type of object that is loaded in the viewer?

For example, below are three different types of objects. See the last download link in each Download window. These are **not** meant to be final text, but examples of using different text labels based on the type of object loaded in the viewer. Is that feasible?

<img width="936" alt="Screen Shot 2020-08-26 at 3 02 37 PM" src="https://user-images.githubusercontent.com/101482/91361499-474fec00-e7ad-11ea-88a3-6dabf28f2cc9.png">


---

<img width="936" alt="Screen Shot 2020-08-26 at 2 50 31 PM" src="https://user-images.githubusercontent.com/101482/91360830-03101c00-e7ac-11ea-8237-6d0c1b909d4a.png">

---

<img width="936" alt="Screen Shot 2020-08-26 at 3 08 30 PM" src="https://user-images.githubusercontent.com/101482/91361903-21771700-e7ae-11ea-81f7-532ae458a8b1.png">

**Comment by mejackreed** [comment]
@ggeisler 

>Is it technically feasible to customize the label for the "full object download" link based on the type of object that is loaded in the viewer?

Sort of? For IIIF viewed content via Mirador we could know that it is a IIIF image thing, but we don't really know much more than that. We could look at all of the files and types indvidually, and try to figure it out, but most of the time in this case it is just going to be:

1. Images (jp2s)
2. Images + OCR text
3. Images + PDF of everything

This doesn't account for our other types of content which aren't shown via Mirador and would come through the other viewer types: 
 - pdf - bh502xm3351
 - 3d - bk914zc7842
 - GIS - cz128vq0535
 - file - wt101ks3240

> Also, do we know the size of the zip file when we instantiate the modal?

No we never know the size. 😢
