### ISSUE TITLE
Jest tests aren't raising errors on GitHub CI

### ISSUE THREAD

**Issue by mejackreed** [sul-dlss/sul-embed#1246]

**Comment by edsu** [comment]
I'm reopening this as it appears that jest test failures don't surface as an action failure, and display as green as long as the ruby tests pass.

**Comment by marlo-longley** [comment]
Not sure if helpful but I remember doing similar work here where we had to explicitly exit the process: https://github.com/sul-dlss/sul-requests/pull/1503/files#diff-ee98e028c59b193d58fde56ab4daf54d43c486ae674e63d50ddf300b07943e0f
