### ISSUE TITLE
CDL: not displaying due date/time when there are multiple CDL items

### ISSUE THREAD

**Issue by saseestone** [sul-dlss/sul-embed#1278]
After a user checks out a CDL item, the due date and time isn't displaying in the viewer when there are multiple CDL items on the record.

Example multi-CDL item record: https://searchworks.stanford.edu/view/13745149
Example single CDL item record (and due date is displaying correctly): https://searchworks.stanford.edu/view/13750779

**Comment by saseestone** [comment]
View of a checked out multi-CDL item: 
![image](https://user-images.githubusercontent.com/14897546/122290638-cfbc8c00-cea8-11eb-8f02-528cec55910f.png)

**Comment by hudajkhan** [comment]
@saseestone , @marlo-longley and I were  looking at the links you provided, but neither appear to be available through CDL anymore. @marlo-longley found a few examples with CDL through Argo, but we are not sure if they have multiple CDL items.  Do you have any current examples that have multiple CDL items? Thanks!

**Comment by marlo-longley** [comment]
In case it helps, we used this facet in Argo: https://argo.stanford.edu/catalog?all=true&f%5Brights_descriptions_ssim%5D%5B%5D=controlled+digital+lending

Thanks!

**Comment by astridu** [comment]
Is it supposed to look like this?
![image](https://user-images.githubusercontent.com/42216982/230507704-febdee49-9d73-4036-9b97-b1e37a1f557d.png)

**Comment by hudajkhan** [comment]
@astridu that makes sense based on the issue description

**Comment by corylown** [comment]
@saseestone can this be closed now that we're no longer supporting CDL?
