### ISSUE TITLE
Embed code (non-Mirador) should be a fully closed iframe tag

### ISSUE THREAD

**Issue by anarchivist** [sul-dlss/sul-embed#1280]
We received a report that a user was having difficulty editing a LibGuides page after adding an embed code for an AV object by cutting and pasting the embed code presented in the Share panel. While the LibGuides admin UI warns the user that the embed code contains an open tag, it's easy to dismiss this warning. 

The existing embed code provided for AV, file, geo, etc. viewers has a self-closing tag (`<iframe ... />`); we should be using a fully closed tag (`<iframe ...></>`) instead.

**Comment by cbeer** [comment]
Is this old feedback? I thought we fixed this last year with https://github.com/ProjectMirador/mirador-share-plugin/pull/43

**Comment by anarchivist** [comment]
@cbeer No, see the title (`Embed code (non-Mirador) ...`). This impacts viewers that are *not Mirador* in sul-embed:

<img width="1243" alt="Screen Shot 2021-06-22 at 10 31 38 AM" src="https://user-images.githubusercontent.com/73732/122972531-198ff100-d345-11eb-80d9-c000601da61a.png">

**Comment by cbeer** [comment]
oops. I missed the "non".
