### ISSUE TITLE
CDL: side panel displaying twice

### ISSUE THREAD

**Issue by saseestone** [sul-dlss/sul-embed#1301]
After a user checks out a CDL item, if they select to view the side panel, it appears twice:

![image](https://user-images.githubusercontent.com/14897546/137189029-8b4a46e6-1c56-437b-bb90-957fbb19ed3b.png)

Jira ticket with a gif: [SW-4045](https://jirasul.stanford.edu/jira/browse/SW-4045)

URL for a CDL item: https://searchworks.stanford.edu/view/3087568

**Comment by cbeer** [comment]
> cbeer: i took a look at https://github.com/sul-dlss/sul-embed/issues/1301 and it’s caused by a super weird mirador thing
> https://github.com/ProjectMirador/mirador/pull/3399 now renders children… but plugins get + need the children prop in the first place
