### ISSUE TITLE
Add a download=true parameter to associated renderings in embedded M3 viewer

### ISSUE THREAD

**Issue by anarchivist** [sul-dlss/sul-embed#1305]
We received user and staff feedback about a [specific SDR object](https://purl.stanford.edu/dv905mk4969), a scanned thesis. As an SDR `book` object, it has an associated PDF that's linked in the manifest as a `rendering`. The problem is that the associated PDF is over 2 GB, and most browsers' PDF rendering engines seem to fail for files around >=300 MB. Users report this as browsers (both Chrome and Firefox) showing a loading bar that never finishes (see, e.g. [VUF-8503](https://jirasul.stanford.edu/jira/browse/VUF-8503)). Downloading the PDF and opening it in a local viewer leads to no issues.

Given that we are already passing a `download=true` parameter for a variety of image sizes in the download dialog which leads Stacks to set a `Content-Disposition: attachment ...` header to force the browser to download the files, we should add also this parameter when we generate the link to the rendering as well.  @camillevilla thought that this may need an upstream change in the Mirador download plugin.

**Comment by corylown** [comment]
I believe that the now merged https://github.com/ProjectMirador/mirador-dl-plugin/pull/62 closes this issue.
