### ISSUE TITLE
Media objects with many files crash Chrome browser tab

### ISSUE THREAD

**Issue by anarchivist** [sul-dlss/sul-embed#1334]
Originally reported as [PURL-1121](https://jirasul.stanford.edu/jira/browse/PURL-1121)

### Expected behavior

When I view https://purl.stanford.edu/xp512bd8714, I should be able to navigate this object's many parts. Once I authenticate, I should be able to play back the various component resources.

### Actual behavior

In Chrome, the browser may load the page for the purl, but eventually crashes with an "Aw, Snap!" error (error code 5). This may happen more readily after you authenticate to be able to play one or more media file back. 

### Steps to reproduce the behavior

* Load the object in Chrome, either via PURL, SearchWorks, or SUL Embed directly:
  * https://purl.stanford.edu/xp512bd8714
  * https://searchworks.stanford.edu/view/xp512bd8714
  * https://embed.stanford.edu/iframe?url=https://purl.stanford.edu/xp512bd8714
* If the browser does not crash soon after loading, authenticate to allow playback of one or more files
* If you have Chrome's internal Task Manager window open, you will see it spawn many dedicated workers for this specific tab.

### Browser / Environment

Chrome 100.0.4896.127 / MacOS 10.15.7
Chrome (canary) 103.0.5010.0 / MacOS 10.15.7

**Comment by marlo-longley** [comment]
@thatbudakguy and I ran tests across multiple browsers and versions of Chrome. Once we updated to Chrome Version 106.0.5249.61 (Official Build) (x86_64), the issue was not present. We can consider this closed.
