### ISSUE TITLE
Audio files are not playing back in Chrome 101/102

### ISSUE THREAD

**Issue by anarchivist** [sul-dlss/sul-embed#1338]
Reported as [PURL-1130](https://jirasul.stanford.edu/jira/browse/PURL-1130)

### Expected behavior

World/world or Stanford-only media objects with audio content should play in Chrome.

### Actual behavior

Audio files are not playing back in Chrome 101/102 (confirmed on 102.0.5005.61). Developer console reports "this.el_.requestVideoFrameCallback is not a function" error.

This appears to be videojs/video.js#7772, which is fixed in video.js v7.20.1. 

### Steps to reproduce the behavior

1. View a world/world object e.g. https://purl.stanford.edu/bc275mm5153
2. Try to hit play
3. Nothing happens
4. Look at developer console; see JS error.

### Browser / Environment

Mac OS 10.15.7, Chrome 102.0.5005.61

**Comment by cbeer** [comment]
See https://github.com/videojs/video.js/issues/7772

**Comment by marlo-longley** [comment]
Right now 7.19.2 is the latest release; 7.20.x are in pre-release mode. That's why we aren't those versions in updates from npm.

**Comment by anarchivist** [comment]
We'll sit on this for a week or two to wait for VideoJS to ship a new release. We can deploy with a prerelease sooner if need be.

**Comment by oceanofsound** [comment]
Any update on this bug?

**Comment by cbeer** [comment]
Fixed by #1364 / video-js 7.20.2 release.
