### ISSUE TITLE
Migrate Universal Analytics (UA) to Google Analytics 4 (GA4)

### ISSUE THREAD

**Issue by corylown** [sul-dlss/sul-embed#1383]
Universal Analytics (UA) properties will [stop collecting data as of July 1, 2023](https://support.google.com/analytics/answer/11583528?hl=en). The data in the existing UA property will remain available for an unspecified period of time. In order to collect data after July 1, 2023 we will need to create a new GA4 property and add the newer `gtag.js` snippet to the application in order to collect data into the new GA4 property.

Spreadsheet that tracks properties and whether each property is tracking events: https://docs.google.com/spreadsheets/d/1WWt3l-RFqfb_L2j01Y7JBUWJ2OnX0Hi4xLmIW8abNLw/edit?usp=sharing

- [x] [Add a Google Analytics 4 property](https://support.google.com/analytics/answer/9744165#zippy=%2Cin-this-article)
- [x] [Add the Google tag to the application](https://support.google.com/analytics/answer/9304153#zippy=%2Cadd-your-tag-using-google-tag-manager%2Cadd-the-google-tag-directly-to-your-web-pages)
- [x] [Set up event tracking as desired](https://support.google.com/analytics/answer/11091025#zippy=%2Cin-this-article). NOTE: _everything_ is an event in GA4 and it automatically collects some events.
- [ ] Optionally, download and archive the historical UA data.

NOTE: There is currently a [setting available](https://support.google.com/analytics/answer/11150547) that will send events from `analytics.js` (UA) to GA4 properties. However, Google does not guarantee this will continue to work after July 1, 2023. This is not recommended as a migration path for event tracking.

**Comment by marlo-longley** [comment]
Note: the events being tracked on the existing UA property are all Mirador events, e.g. `mirador/SET_CANVAS`

**Comment by marlo-longley** [comment]
This is the new embed code: 
```

<!-- Google tag (gtag.js) -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-80J719XWE5"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-80J719XWE5');
</script>
```

**Comment by marlo-longley** [comment]
@corylown -- do you know where we stand on your optional step of archiving the old analytics? This could be closed by #1417. I marked the Migrated? column to YES in the spreadsheet as well.

**Comment by corylown** [comment]
@marlo-longley -- Jacob Hill is going take the lead on any archiving we might want to do so we don't need to worry about that for now.

**Comment by marlo-longley** [comment]
Closing as this is live in production and debug mode is working for all other instances.
