### ISSUE TITLE
Web-archive seed presentation should link only to the SWAP url from the "link" icon in the base of the viewer

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/sul-embed#1415]
### Expected behavior
When a web-archive seed is presented in sul-embed, there's a link at the base of the viewer that should go to the SWAP link for that seed:

<img width="186" alt="Screen Shot 2023-01-11 at 11 09 15 AM" src="https://user-images.githubusercontent.com/8975583/211915539-23196e0a-bb72-41af-bec2-39f80658ee20.png">

### Actual behavior

The link that appears there seems to be a concatenation of all the URLs stored in the "Bibliographic Information" section of the Purl, which presumably corresponds to a particular block of MODS.

See 

- https://purl.stanford.edu/bt240zr7381 -- the link includes four URLs strung together
- https://purl.stanford.edu/bc317zb8156 -- the link includes two URLs strung together

### Steps to reproduce the behavior

This seems to be an issue on all webarchive seeds, which should all be using the same metadata structure. I believe that the link in the base of the viewer should be the same as the link in the thumbnail.

### Additional information

For reasons that I do not understand, web archive seeds where the public XML has not been updated recently do not show this link icon in the base of the viewer. See https://purl.stanford.edu/bj114ky2153 (last published 2020-08-30). When items are republished with no change to the internal SDR metadata, the viewer starts to show a link, presumably because the format of the republished public XML now matches some path that the viewer is checking.

However, given that the base of the viewer has apparently not been displaying a link until recently, one possible alternative to fixing the link is to remove it entirely. The relevant links are already within the body of the viewer.

**Comment by cbeer** [comment]
This is the ticket that introduced the external link icon:
https://github.com/sul-dlss/sul-embed/issues/287

I guess we're converting more things to dc:identifier then we used to?
