### ISSUE TITLE
Question: should the file content viewer have an in-viewer filename search box?

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/sul-embed#1422]
**Context and current behavior**

When viewing file content (i.e. content type="file") a box appears in the top bar of sul-embed where a user can enter text. This operates more as a filter than a search, as the list of files automatically filters down to file names that match the text being entered:

https://user-images.githubusercontent.com/8975583/212975886-aa33171c-cfa2-4f4d-964e-3658a6d80e84.mov

Note that the search bar appears only when a druid contains 10 or more files:

- purl with 10 files and a search bar: https://sul-purl-stage.stanford.edu/sx562mk0566

https://user-images.githubusercontent.com/8975583/213039193-6863aa95-8148-4edf-bbfb-ac3c77b3663b.mov

- purl with 9 files and no search bar: https://sul-purl-stage.stanford.edu/vg607bw5557

https://user-images.githubusercontent.com/8975583/213039228-0e265cbc-8e15-4c88-9b6d-124f8c251371.mov
 
**Question**

Should this search be maintained when implementing the hierarchical file display? 

Some considerations:

- Current search could be useful in filtering large file lists to a specific file type or naming convention: ([purl with 500 files](https://purl.stanford.edu/db586ns4974))
- Current search is inconsistent in when it appears: since it won't appear if there are 9 or fewer files, you can't filter small lists 
- Current implementation of search is not compatible with hierarchically arranged file lists and would require more extensive code changes to be maintained in a hierarchical display
- Browser search (Ctrl or Cmd + F) picks up file names inside sul-embed, so it is possible to search for names without the embed search box; however, the browser search will not filter the list to show only matches
- Filtering file names does not change download functionality: downloads within the viewer must be made one file at a time; there is no way to download only the files that appear in the filter

**Comment by mjgiarlo** [comment]
Andrew will close this issue soon with some closing thoughts.

**Comment by andrewjbtw** [comment]
The answer to this question turned out to be yes, and search was rewritten to support hierarchy.

For posterity, the reasoning was basically:

- user feedback indicated search was useful
- analysis of all existing "file" objects showed that nearly 1000 already employ search, meaning that they have 10 or more files in a list. We did not want to remove that feature.
