### ISSUE TITLE
Media viewer missing from PURL on some (all?) objects when viewed in Safari

### ISSUE THREAD

**Issue by oceanofsound** [sul-dlss/sul-embed#1425]
This issue appears to be localized to Safari (Chrome and Firefox are ok). Plugging any PURL into Safari - Stanford only, world, reading room only - will bring up a PURL without a media player. However, if that same object has been released to SearchWorks, the viewer does appear within the record. Example:

https://purl.stanford.edu/gm665jd4643
(https://searchworks.stanford.edu/view/gm665jd4643

**Comment by jcoyne** [comment]
I can confirm I also see the bug. What is really interesting is that https://embed.stanford.edu/iframe/?url=https%3A%2F%2Fpurl.stanford.edu%2Fgm665jd4643 (the embeded frame source) works fine in safari

**Comment by jcoyne** [comment]
I believe this is fixed now. We had fixed this problem already, but we hadn't yet deployed the fix. Thank you for your report.
