### ISSUE TITLE
was-seed viewer throws 500 when archived site URL isn't correct

### ISSUE THREAD

**Issue by edsu** [sul-dlss/sul-embed#1460]
### Expected behavior

When the PURL XML contains an archived website URL that isn't properly formatted then sul-embed should probably display something helpful about the problem?

### Actual behavior

When the PURL XML contains an archived website URL that lacks a `*` it throws a 500 error:

<img width="1469" alt="Screenshot 2023-02-01 at 3 05 59 PM" src="https://user-images.githubusercontent.com/33829/216151721-b34b1bba-5042-458b-af84-2ac0527009d5.png">

### Steps to reproduce the behavior

Load up some PURL XML for a was-seed object containing a URL like this into the sandbox viewer:

```xml
<location>
  <url displayLabel="Archived website">https://swap.stanford.edu/was/20220831210052/https://wexarts.org/talks-more/tongues-untied</url>
</location>
```

### Browser / Environment

Firefox/MacOS

See https://github.com/sul-dlss/was_robot_suite/issues/279 for related work to prevent was-seed objects from getting published with incorrect URLs.

**Comment by jcoyne** [comment]
Sample URL https://embed.stanford.edu/iframe?url=https://purl.stanford.edu/qw622dx4390

**Comment by jcoyne** [comment]
@edsu the purl for this item has https://swap.stanford.edu/was/20220831210052/https://wexarts.org/talks-more/tongues-untied as the archived URL.  However, most archived urls that I've seen have a `*` in them. Should this be required?

**Comment by edsu** [comment]
Yes, it currently is required for the viewer to work, since it appears to be [keying off](https://github.com/sul-dlss/sul-embed/blob/master/app/viewers/embed/viewer/was_seed.rb#L33) the `*` to determine the Timemap URL to fetch to get the list of snapshots. Unfortunately there's nothing in the workflow to ensure that it is formatted correctly.

**Comment by jcoyne** [comment]
@edsu It's unclear to me what the action should be for this ticket?  Is this something that can be fixed in data validation in cocina-models?
