### ISSUE TITLE
Disambiguate "Video file" in download list of media objects

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/sul-embed#1527]
https://purl.stanford.edu/bd111gd4290

Thumbs should probably not be made available in the download list for world objects (it’s confusing because they have the same title as the streaming video file). Need to change the way thumbs are either generated post-accessioning, or the way they’re handled in the SMPL accessioning process. Cocina has a field that allows you to label the thumb file (every file has a label field now) differently but none of the displays are capable of reading it yet.

**Comment by dinahhandel** [comment]
I have proposed disambiguation/mapping here: https://docs.google.com/document/d/1dvdOzZ50V1AAZV_o9gLqgIduYlA-VZG-3mYgykqfrJY/edit

**Comment by mjgiarlo** [comment]
Waiting for file language implementation, e.g., to disambiguate transcript languages.

**Comment by andrewjbtw** [comment]
For an item with multiple language captions, including language tags: https://argo-stage.stanford.edu/view/druid:wm783fb6812

**Comment by mjgiarlo** [comment]
Depends on #1753 1753
