### ISSUE TITLE
Edge doesn’t render the PDF viewer 

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/sul-embed#1528]
### Expected behavior
Displays PDF

### Browser / Environment
Edge

**Comment by thatbudakguy** [comment]
note that edge and its "insider" developer-oriented builds can be installed on macOS and linux for testing purposes: https://www.microsoft.com/en-us/edge/download/insider?form=MA13FJ

**Comment by justinlittman** [comment]
Works for me. @jcoyne Can you replicate?

![image](https://github.com/sul-dlss/sul-embed/assets/588335/d14262b2-8782-48a6-b85a-eaf0ac7b5165)

**Comment by jcoyne** [comment]
Yes, works for me too. This ticket was created out of hearsay, so I'm going to close it.
