### ISSUE TITLE
Display something in the background when playing an audio

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/sul-embed#1532]
### Expected behavior
Ideally, some kind of visual indication that the user is listening to an audio track. A static image of a waveform, a dynamic waveform of the music playing? A dynamic waveform would have the added result of indicating to the user if the was silence during the track.

### Actual behavior
Currently, the player is black for some items and the only indication something is playing is the play bar at the bottom of the screen. 

![Image](https://github.com/sul-dlss/sul-embed/assets/9371978/3d92bb26-7f4c-4695-a4a5-1d4af19db79b)

Other items do have a visual already, e.g., https://purl.stanford.edu/vc092km4494, and the changes associated with this issue should *not* alter that behavior.

### Steps to reproduce the behavior
Play https://purl.stanford.edu/jp542sf2726 in browser

### Browser / Environment
Chrome/iOS

**Comment by dinahhandel** [comment]
I believe this ticket is ready, pending a design from @alundgard

**Comment by jcoyne** [comment]
We should look at https://videojs.com/guides/options/#audiopostermode and see if that will fix this.

**Comment by jcoyne** [comment]
@andrewjbtw points out that some audio already has an image.  We don't want to disable this: https://purl.stanford.edu/vc092km4494

**Comment by andrewjbtw** [comment]
There is also a ticket related a problem with the player controls on mobile when audio has a thumbnail: https://github.com/sul-dlss/media/issues/156

We might have to fix that before we can put a default image on audio.

**Comment by alundgard** [comment]
Here is the SVG export (better resolution).


![Image](https://github.com/sul-dlss/sul-embed/assets/2343316/442dd702-6779-43ec-9f3a-a37631b48ea3)
