### ISSUE TITLE
Improve display of citation-only media objects

### ISSUE THREAD

**Issue by alundgard** [sul-dlss/sul-embed#1551]
Currently, the player doesn't indicate when a media object is "citation-only" (i.e., not stream-able or download-able).
This results in a media object display that appears to be malfunctioning. For example, this object [[https://purl.stanford.edu/cd225xb4022](https://purl.stanford.edu/cd225xb4022)] appears (to the user) to be a broken audio stream.

**Comment by alundgard** [comment]
Related to #1536.
- See the Access Banner Prototype in the [Figma Design](https://www.figma.com/file/ADNitlk4aWHDiPDWD1dHdF/Media-Work-Cycle---Media-Player?type=design&node-id=0-1&mode=design). [To launch the interactive prototype in Figma, click the "Present" play arrow in the top-right corner. From this tab, click Access Banner Prototype under the "Flows" panel.]
- Also, see the Access Banner restriction messages (subject to change, pending stakeholder feedback).
![Image](https://github.com/sul-dlss/sul-embed/assets/2343316/8ec0eec3-8c3f-482a-86b6-26ed1ad123dd)
- Contact me for additional context and/or design revisions due to technical feasibility.

**Comment by jcoyne** [comment]
Test on https://sul-purl-stage.stanford.edu/cy304fm5998 and https://sul-purl-stage.stanford.edu/mr390dt8776
