### ISSUE TITLE
Provide higher resolution images and allow zoom for images that are associated with a media object

### ISSUE THREAD

**Issue by dinahhandel** [sul-dlss/sul-embed#1564]
### Expected behavior
The desired outcome is to present higher resolution images and allow the user to zoom in if needed. 

### Actual behavior
Images of the original housing of archival media, along with disc labels, cassette inserts, album covers, and liner notes are typically included as part of a media object. The purpose of providing these images is to allow users to view the writing, notes, and drawings that are considered part of the archival media object. In the current media player, users are unable to see the images clearly and are unable to zoom in to read the small text, which impedes researcher and scholarship, and presents accessibility issues.

It appears that across all access restrictions, a low resolution image file is provided in the media player. 

### Steps to reproduce the behavior
Examples of this issue: https://purl.stanford.edu/bm996pp6037, https://purl.stanford.edu/cz768mr8354, https://purl.stanford.edu/df142py2033.

**Comment by jcoyne** [comment]
I would like to hear Andrews (and others) input on what it means to be a "Media" object vs an "Image" object.  In the past we've said that Image objects would have one type of viewer and media objects would have a different type.  It sounds to me like this ticket is asking us to move away from that pattern and adopt a pattern where each object can have multiple types of viewers. How will we know which viewer we should present to the user first?  How will they switch to a different viewer.  How will we identify which images should use a "deep zoom" viewer?  Do we have the ability to manage access controls in the way we need to for each of the files (e.g. world/stanford/no-download) and can we reflect that in the user experience in a way that is understandable to the user.

**Comment by andrewjbtw** [comment]
As I understand the goal, it's to make it possible to read labels on images when text is small. I don't know enough about our image delivery to know if that requires a full-fledged image viewer or if there is something that can be done within the media player to present more than one image size. It looks like images are always limited to 400px in the media viewer.

The images themselves meet the requirements for the image viewer and likely don't need different management tools than what's already in Argo in terms of structural metadata, but this would need to be confirmed.

**Comment by jcoyne** [comment]
@andrewjbtw I believe this is specifically for the case of "download:none" rights.  I don't know a way we can provide a larger image and not run afoul of the rule that says "download:none" allows only viewing a small version.

**Comment by dinahhandel** [comment]
I understand what you are saying about a media versus image viewer, @jcoyne. I think it would not be desirable to switch viewers within the object, or for there to be any questions about which viewer to present to the user. However, I believe this is the case with images regardless of the access restrictions of the media object. Are you suggesting this request is not technically possible? It would be good to understand that.

**Comment by dinahhandel** [comment]
It would be great to have a story-time session for this @mjgiarlo is that something you schedule or should I?

**Comment by mjgiarlo** [comment]
@dinahhandel Happy to schedule it. I'll reach out on Slack.

**Comment by dinahhandel** [comment]
See [storytime notes from November 2, 2023](https://docs.google.com/document/d/1g09YWvrJOx_fBUmvkgaCheQ1zGwE2krmnu5HgL0EZ4Q). @alundgard needs to make design pass/decision on keyboard controls (zoom and pan) design.

**Comment by alundgard** [comment]
After consulting with the POs, it doesn't seem that our use case requires a design significantly different from the [Mirador image viewer controls](https://purl.stanford.edu/bb627py6670): Zoom in, Zoom out, Reset zoom, Forward/Backward (if applicable).

As a stretch goal, it may be nice to add a tooltip to reveal the additional [OpenSeadragon controls](https://openseadragon.github.io/examples/ui-keyboard-navigation/) to users. Tooltips are tricky for accessibility, so I'm wary of making that a hard requirement. But if we are interested, I'm happy to put together a tooltip design mockup. This doesn't block moving forward with the Mirador controls.

**Comment by mjgiarlo** [comment]
Fair warning to developers: we have some concerns about work on this complicating our ability to ship the new media player, so the PR for this issue may linger in In Progress for a bit.
