### ISSUE TITLE
Investigate caching settings

### ISSUE THREAD

**Issue by thatbudakguy** [sul-dlss/sul-embed#1578]
We've had multiple reports of users experiencing undesirable caching and using alternative methods (incognito, etc.) in order to view changes to purl pages.

Some possibly related tickets:
#700 
#1028
#1496

**Comment by justinlittman** [comment]
The max-age on the response is set to 1 year. What is the desired behavior?

**Comment by jcoyne** [comment]
probably should use an ETag and have the client send If-None-Match

**Comment by justinlittman** [comment]
We already do this for purl: https://github.com/sul-dlss/purl/blob/main/app/controllers/purl_controller.rb#L14

However, to the best I can tell this doesn't work as expected. For https://purl.stanford.edu/bb009sj6832:

Request:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBME54QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--abd88290aef148913dbde3541eacf81aaf1ca93c/image.png)


Response:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMGh4QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--016a3c9d1985bf72f76d14bcf3513c8223fe1d6a/image.png)

**Comment by justinlittman** [comment]
I suspect that the problem is that the stale check isn't working due to the `-gzip` added by Apache.

**Comment by jcoyne** [comment]
<img width="932" alt="Screenshot 2023-10-25 at 4 00 24 PM" src="https://github.com/sul-dlss/sul-embed/assets/92044/7f210236-4cfd-45ed-b3cc-45e5df109c73">
@justinlittman I can't see what you're sharing

**Comment by jcoyne** [comment]
I'm wondering if the problem is due to using `max-age` in addition to ETags, where it's not bothering to check since max-age hasn't expired.

**Comment by jcoyne** [comment]
@justinlittman I would have expected the controller to use `fresh_when` to do the etag caching. If not, at least `return head :not_modifed` somewhere.

**Comment by justinlittman** [comment]
<img width="812" alt="image" src="https://github.com/sul-dlss/sul-embed/assets/588335/6283f3ab-5378-4494-b3fe-97ebad83c3ff">

**Comment by justinlittman** [comment]
I've confirmed in UAT that the browser received and sends the etag with the -gzip and that Rails gets the `If-None-Match` with the gzip response.

**Comment by justinlittman** [comment]
Fix for purl.
