### ISSUE TITLE
Viewer should be able to choose captions in different languages

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/sul-embed#1588]
We need a test object for this.

No longer blocked by #1498 because even without the full settings interface, the user is presented with a choice of language.

**Comment by dinahhandel** [comment]
Test objects: https://argo.stanford.edu/catalog?f%5Bcollection_title_ssim%5D%5B%5D=Nuremberg+Trial+Archives&f%5Bcontent_file_mimetypes_ssim%5D%5B%5D=text%2Fvtt&f%5Bcontent_type_ssim%5D%5B%5D=media

**Comment by jcoyne** [comment]
@andrewjbtw @dinahhandel do we have any way to pull that object to the SDR stage environment?

**Comment by andrewjbtw** [comment]
Yes, I just made one: https://argo-stage.stanford.edu/view/druid:wm783fb6812

**Comment by andrewjbtw** [comment]
But looking at our multilingual items, I wonder if that's the structure we really want? We have one file/fileset per language currently. But won't we want just one media file and multiple caption files if we're going to toggle between languages?

**Comment by andrewjbtw** [comment]
I've just restructured https://argo-stage.stanford.edu/view/druid:wm783fb6812 so that there is only the original video file (no captions burned in) and it's alongside both caption files in the same resource.

I don't see any language identification in the VTT files so we will have to come up with a way to handle that.

**Comment by dinahhandel** [comment]
I see language ID'd in the filename, would that be enough information? eng = English, ger = German, rus = Russian. Luckily this is the only collection that has multilingual caption files, unfortunately it is high visibility.

**Comment by andrewjbtw** [comment]
Returning to this, we decided to go with 

- "role" = "caption" 
- "language" = "[a BCP 47]" tag

These two test items have that metadata set now 

- https://argo-stage.stanford.edu/view/druid:wm783fb6812
- https://sul-purl-stage.stanford.edu/nf861hn5388
