### ISSUE TITLE
I do not see captions displayed for test audio object when using Safari Version 16.6 (18615.3.12.11.2)

### ISSUE THREAD

**Issue by dinahhandel** [sul-dlss/sul-embed#1635]
### Expected behavior
I have selected to display english captions and expect to see captions display in the media player. Note that there are no reported issues with displaying captions for this test audio object in Chrome or Firefox. 

### Actual behavior
No captions display when english captions are selected.

### Steps to reproduce the behavior
Open https://sul-purl-stage.stanford.edu/xs884bk3832 in Safari

### Browser / Environment
Safari Version 16.6 (18615.3.12.11.2)

**Comment by jcoyne** [comment]
> The <audio> element doesn't directly support WebVTT. You will have to find a library or framework that provides the capability for you, or write the code to display captions yourself. One option is to play your audio using a [<video>](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/video) element, which does support WebVTT.

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/audio#accessibility_concerns

It seems like this does work in Firefox + Chrome though.
