### ISSUE TITLE
Caption shows user option to select "unknown" language CC for test video object in Safari

### ISSUE THREAD

**Issue by dinahhandel** [sul-dlss/sul-embed#1637]
### Expected behavior
Caption text should be white and overlayed on a solid black background. The CC selection menu should only display available languages and for this object, only display english. 

### Actual behavior
Option for unknown language CC shows up
![Screenshot 2023-10-31 at 2 25 30 PM](https://github.com/sul-dlss/sul-embed/assets/9371978/8b8f454a-4e9d-4e1c-b81c-2bc9bf17a75b)

Background to captions is translucent in Safari
![Screenshot 2023-10-31 at 2 26 14 PM](https://github.com/sul-dlss/sul-embed/assets/9371978/c2a80bb1-3f2c-4d96-b3f9-ece55eb4e336)

As opposed to Chrome, where the background is black 
![Screenshot 2023-10-31 at 2 27 04 PM](https://github.com/sul-dlss/sul-embed/assets/9371978/99c0595d-5139-446a-8423-a95d840dfb18)

### Steps to reproduce the behavior
Play https://sul-purl-stage.stanford.edu/qb933xv2993 in Safari, select the CC button 

### Browser / Environment
Safari Version 16.6 (18615.3.12.11.2)

**Comment by jcoyne** [comment]
The "Unknown" language seems to be a bug in Safari: https://github.com/videojs/video.js/issues/2808#issuecomment-157440270

**Comment by jcoyne** [comment]
The caption transparency is a user preference set in the Accessability settings. See https://support.apple.com/lv-lv/guide/mac-help/mh43180/mac

**Comment by mjgiarlo** [comment]
This needs more analysis re: where the unknown language bit is coming from.

**Comment by andrewjbtw** [comment]
According to the [technical metadata for the sample file](https://argo-stage.stanford.edu/view/druid:qb933xv2993) (scroll down to the technical metadata section and expand it), the MP4 has:

- a video stream
- an audio stream
- a timecode track

Could the timecode track be what's triggering the "Unknown" to display?

**Comment by hudajkhan** [comment]
This link also seems related (discovered by following @jcoyne 's links above): https://developer.apple.com/library/archive/qa/qa1801/_index.html

**Comment by hudajkhan** [comment]
When trying to test this locally (using two different methods, explained below), when the track tag is present under video, the "unknown" caption option does not show up.  As the link above indicates, the issue may be that the provided HLS/playlist information (from Wowza) needs to explicitly declare the absence or presence of captions.  (It is unclear whether declaring absence in the HLS/playlist but explicitly declaring the caption track inside the video element, as the code currently does, would address this issue).

The two methods I tried:
a) Setting up a basic html page using the video js code used by sulembed, downloading a video file and its vtt caption file (specifically for https://purl.stanford.edu/dw293cz3962), setting up a track element as shown below, and then bringing up the page.  Captions work, showing "off", "auto recommend" and "English" but no "unknown". Removing the track element completely does not provide any subtitle options but also does not show "unknown":
 
`<track kind="captions" src="videotest/videoclip.vtt" srclang="en" label="English" default>`

(b) Rigging up the media component tag rspec file to use a fixture method that returns the XML for the PURL indicated above, and then having the test output the page html.   Setting up a page with that HTML didn't work b/c of the external m3u8 file.  Setting the source for the video and vtt in this file to my local copies brought up the video.  Captions were visible but no "unknown" caption option. 

I'll be looking at the Wowza side of things a bit more, and will double check if there are time codes present in some of the other "unknown" caption option examples.

**Comment by jcoyne** [comment]
It seems like adding a custom property to the Wowza server should take care of this: https://www.wowza.com/docs/how-to-turn-off-the-alternate-track-button-in-apple-ios-devices

**Comment by hudajkhan** [comment]
I did some more configuration in my local sul embed to make it point to a local copy of a Wowza playlist where I'd added the "CLOSED-CAPTIONS=NONE" to the "EXT-X-STREAM-INF" tag.  That did turn off the "unknown captions" option.

Based on @jcoyne 's suggestion above, I added the custom property to the staging Wowza instance, which results in "CLOSED-CAPTIONS=NONE" being added to the playlist m3u8 file for a video.  The "unknown" option is not visible on a few of the examples I checked, while the other caption options are still visible. 

Examples: https://sul-purl-stage.stanford.edu/pf759xf5671 , https://argo-stage.stanford.edu/view/druid:cm856pm4228 etc.

**Comment by hudajkhan** [comment]
To include this in the application.xml for stacks under conf, we need to find the element Root/Application/HttpStreamer/Properties and add the following XML

```
<Property>
					<Name>cupertinoClosedCaptionValue</Name>
					<Value>NONE</Value>
					<Type>String</Type>
				</Property>
```

**Comment by hudajkhan** [comment]
This has been closed by the puppet configuration issue, but it may take a while for the changes to be reflected in stage/production.  I'll come back here and comment when I can see the appropriate flag in staging.

**Comment by hudajkhan** [comment]
Applied and working in stage!

**Comment by hudajkhan** [comment]
I also see "CLOSED-CAPTIONS=NONE" coming through in a production [m3u file ](https://sul-mediaserver.stanford.edu/stacks/_definst_/dw/293/cz/3962/mp4:dw293cz3962_SAASEI_-_Amy_Peng_sl.mp4/playlist.m3u8?stacks_token=9VPaLPOB7RpoYuT6QOiFNApNrImdNkKxBQ83mVw9UBFE%2Fio8Qd3hlGtMGLdlWUJoI%2Bk5ksKpnftYoljNYpPvq%2BM4amSZLYlN%2BxX3oZqXyLWaCg6WN1J5VetLq0%2FJ3yWLrQ4ckZPiXrGYAEcnPs%2Fhdv3M4qL3B1M6KNC5jfwS%2BzvK1voy%2BV8W295MCtBNQig%2FAIah5uZSt2B%2Bs2Cc2VVxTlVTaPjd57eqcJT9jTULXB5%2FXd5sK2ZjPNE9kdjTtHSsbv%2BVhhfL8sYm%2B%2Fzznffz4bvHEyUrZO%2BUe5FeKf%2FA6WSXSny0VuGuzmYFJHlr6KQvmGJutLJMQdjJvQiWzm8TBoH2%2Bc%2F0--udSffphop6p2ZKJ0--q0PY1BWen1wOpzhhuPddqw%3D%3D)

**Comment by dinahhandel** [comment]
Awesome, thanks for all your work on this, @hudajkhan !
