### ISSUE TITLE
Issues with caption display in Safari on iOS 16.6.1

### ISSUE THREAD

**Issue by dinahhandel** [sul-dlss/sul-embed#1638]
### Expected behavior
There should be no difference in functionality between web-browser on a computer and mobile web browsers.

### Actual behavior
couple of comments about Safari on iOS

- I can't get captions to display on audio only content

- I can get captions to display on video content, but I usually have to toggle between 'Off,' 'English Captions,' and 'CC' (it definitely doesn't easily come on, and I can see a user getting frustrated)

- the captions that are displayed on videos have a grey background, not a black background

### Steps to reproduce the behavior
Audio content example: https://sul-purl-stage.stanford.edu/xb302rj8598 and video content: https://sul-purl-stage.stanford.edu/qb933xv2993

### Browser / Environment
Safari on iOS 16.6.1

**Comment by jcoyne** [comment]
The caption transparency is set by the accessability settings on iOS:

![Image](https://github.com/sul-dlss/sul-embed/assets/92044/f22b4cee-24e4-4595-9195-1bfb995a8a05)

**Comment by mjgiarlo** [comment]
Dinah will look into reproducing this.

**Comment by dinahhandel** [comment]
Confirming that I am unable to get captions (or the audio) to play for https://sul-purl-stage.stanford.edu/xs884bk3832 on Safari mobile. Out of the three issues reported above, the inability to play captions for audio in Safari (mobile) is the only issue worth pursuing.
