### ISSUE TITLE
Broken image in right drawer when there is no thumbnail

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/sul-embed#1640]
Seen in https://embed-stage.stanford.edu/iframe?new_component=true&url=https://sul-purl-stage.stanford.edu/nr582tm3161&_v=1698775996
<img width="379" alt="Screenshot 2023-10-31 at 2 23 53 PM" src="https://github.com/sul-dlss/sul-embed/assets/92044/f2873d5d-6add-41cc-b443-d306383395a0">

**Comment by mjgiarlo** [comment]
If no thumbnail, use audio or video icon.
