### ISSUE TITLE
Unknown CC is automatically selected when video plays in Safari 16.6

### ISSUE THREAD

**Issue by dinahhandel** [sul-dlss/sul-embed#1641]
### Expected behavior
Default behavior is that captions do not display until a user has selected them.

### Actual behavior
Unknown CC is automatically selected when video begins to play. This issue is only present for the one example provided. 

### Steps to reproduce the behavior
Open https://sul-purl-stage.stanford.edu/qc898xy1175 in Safari and press play

### Browser / Environment
Safari 16.6

**Comment by mjgiarlo** [comment]
Duplicates another ticket
