### ISSUE TITLE
Stanford Only PDF views don't work

### ISSUE THREAD

**Issue by edsu** [sul-dlss/sul-embed#1642]
Views of Stanford Only PDFs don't work when the user is logged in. Based on the research (see below) this might get fixed if:

- [ ] pdfjs sends credentials when fetching Stanford Only PDFs (see below for an example of this).
- [ ] Stacks responds to requests for Stanford Only files with a `Access-Control-Allow-Origin: https://embed-stage.stanford.edu` CORS header. This is ticketed in https://github.com/sul-dlss/stacks/issues/1066

One wrinkle is that PURL views for Stanford Only items don't currently require users to be logged in to see the page. If they aren't logged in I'm not sure that pdfjs will be able to navigate the login process.

---

When an item is of type `document` sul-embed will try to render it in page with pdfjs. This works when the PDF is `World` viewable, however @andrewjbtw reported that it doesn't work when the item is set to be viewable `Stanford Only`. For example:

* prod: https://purl.stanford.edu/gq661wq7355 
* stage: https://sul-purl-stage.stanford.edu/kp686sg8638

![Screenshot 2023-10-31 at 3 39 51 PM](https://github.com/sul-dlss/sul-embed/assets/33829/1471249b-94e1-4e30-8a2b-fa39b75ebedb)

Initially we thought this might be related to the recent upgrade to pdfjs-dist, but rolling back that change in stage didn't fix the problem.

Inspecting the browser dev tools console shows a CORS error in both prod and stage:

```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://stacks.stanford.edu/file/auth/gq661wq7355/00%20Woodwint%20Quintet%202%20-%20Score.pdf. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing). Status code: 302.
``` 

![Screenshot 2023-10-31 at 12 42 24 PM](https://github.com/sul-dlss/sul-embed/assets/33829/a221d46b-6e2c-4adb-a2ca-7f203df7c3fa)

This is because the browser has loaded a page from purl.stanford.edu which is using pdfjs to try to load a resource from stacks.stanford.edu, but the Cross Origin Resource Sharing (CORS) headers on that response do not allow for that. 

I can see [there is code](https://github.com/sul-dlss/stacks/blob/master/app/controllers/media_controller.rb#L40-L43) in Stacks to send the correct CORS headers for `World` viewable items. But when a resource is `Stanford Only` the Shibboleth Apache module does a 302 redirect which does not provide the `Access-Control-Allow-Origin` header.

```
$ curl -i https://stacks.stanford.edu/file/auth/gq661wq7355/00%20Woodwint%20Quintet%202%20-%20Score.pdf
HTTP/1.1 302 Found
Date: Tue, 31 Oct 2023 19:27:24 GMT
Server: Apache/2.4.41 (Ubuntu)
Strict-Transport-Security: max-age=31536000; includeSubDomains
Set-Cookie: _shibstate_1698780444_1597=https%3A%2F%2Fstacks.stanford.edu%2Ffile%2Fauth%2Fgq661wq7355%2F00%20Woodwint%20Quintet%202%20-%20Score.pdf; path=/; secure; HttpOnly
Expires: Wed, 01 Jan 1997 12:00:00 GMT
Cache-Control: private,no-store,no-cache,max-age=0
Location: https://login.stanford.edu/idp/profile/SAML2/Redirect/SSO?SAMLRequest=fZJLb4MwEIT%2FCvI9mEdTFCsg0eTQSGmDAu2hl8qBJVg1NvWaPv59SUjb5JKTD579Zme0c%2BSt7Fja20Zt4b0HtM5XKxWy40dMeqOY5iiQKd4CMluyPH1Ys8D1WGe01aWWxEkRwVih1UIr7FswOZgPUcLTdh2TxtoOGaVoefmG7vCoWpvKhaqneSN2Oy3BNi6ipgd0QLNNXhBnOewiFD9Q%2FxlS74W6RIiqo8MmtZBwmt9CJQyUlub5hjirZUxe6ygKA396G1Y%2B9%2BqQT8uI19WsDusayiqKBhliDyt1QNuYBF4QTnxvEvqFP2NBxIKbF%2BJkp8B3QlVC7a%2B3sxtFyO6LIpuMmZ7B4DHPICDJ%2FNAxOxqbs9avY%2Flv1SS5Viz%2BFTunZzajZ8ceB%2B5qmWkpym8nlVJ%2FLgxwCzHxCU3GkcuzSH4A&RelayState=cookie%3A1698780444_1597
Content-Length: 746
Content-Type: text/html; charset=iso-8859-1

<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>302 Found</title>
</head><body>
<h1>Found</h1>
<p>The document has moved <a href="https://login.stanford.edu/idp/profile/SAML2/Redirect/SSO?SAMLRequest=fZJLb4MwEIT%2FCvI9mEdTFCsg0eTQSGmDAu2hl8qBJVg1NvWaPv59SUjb5JKTD579Zme0c%2BSt7Fja20Zt4b0HtM5XKxWy40dMeqOY5iiQKd4CMluyPH1Ys8D1WGe01aWWxEkRwVih1UIr7FswOZgPUcLTdh2TxtoOGaVoefmG7vCoWpvKhaqneSN2Oy3BNi6ipgd0QLNNXhBnOewiFD9Q%2FxlS74W6RIiqo8MmtZBwmt9CJQyUlub5hjirZUxe6ygKA396G1Y%2B9%2BqQT8uI19WsDusayiqKBhliDyt1QNuYBF4QTnxvEvqFP2NBxIKbF%2BJkp8B3QlVC7a%2B3sxtFyO6LIpuMmZ7B4DHPICDJ%2FNAxOxqbs9avY%2Flv1SS5Viz%2BFTunZzajZ8ceB%2B5qmWkpym8nlVJ%2FLgxwCzHxCU3GkcuzSH4A&amp;RelayState=cookie%3A1698780444_1597">here</a>.</p>
```

Some seem to remember being able to view Stanford Only PDFs in purl. But it's hard to see how that would be the case, unless something significantly has changed in Stacks or Shibboleth since then.

**Comment by edsu** [comment]
After some discussion in purl+metrics standup today, @thatbudakguy suggested that he would check in with @cbeer to see if he remembers this working in the past.

**Comment by edsu** [comment]
Updating our use of `PDFJSLib.getDocument()` to pass along credentials with `useCreditals: true` in a5fe857fd84ca85066078710d96890626f687078 gets this a bit further, but lands us with another CORS error:

```
Access to fetch at 'https://sul-stacks-stage.stanford.edu/file/druid:kp686sg8638/00%20Woodwint%20Quintet%202%20-%20Score.pdf' from origin 'https://embed-stage.stanford.edu' has been blocked by CORS policy: The value of the 'Access-Control-Allow-Origin' header in the response must not be the wildcard '*' when the request's credentials mode is 'include'.
```

<img width="1589" alt="Screenshot 2023-11-01 at 12 53 46 PM" src="https://github.com/sul-dlss/sul-embed/assets/33829/7d3122ce-2bbf-4879-b2eb-313fb4caaed4">

So I guess stacks would need to be updated to send `Access-Control-Allow-Origin: https://embed-stage.stanford.edu` in cases where the object is viewable `Stanford Only`? I wonder if this is worth an experiment?

**Comment by peetucket** [comment]
As discussed at standup this morning, I wonder if the restricted media player use case is a template for what part of what we need to do here.  What happens there is sul-embed detects there is a rights restriction and shows a message to the user instead of the actual media (which wouldn't work, just like the restricted PDFs don't work).  The message directs users to log in via dual-auth.  Once they do this, stacks can correctly serve the media to the player, and it works as expected.

What I don't understand is why when already authed, PDFs still don't work.  Ed's suggestions all seem good to me.

Here is a Stanford only example audio file: https://purl.stanford.edu/bb130xk0485

If you are already authed, it will look like it is just working.  If you open a new browser (or private window), you'll see this:

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMG5qQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--13051f7ef7ae7bb144f0d9356ee0896386a8cc08/Screen%20Shot%202023-11-16%20at%203.47.36%20PM.png)

Coming from https://github.com/sul-dlss/sul-embed/blob/main/app/components/embed/media_tag_component.rb#L115-L128

It looks like the code is inspecting the rights of the files coming from the stacks to determine if we should show the message or not.

**Comment by edsu** [comment]
@peetucket I think you're right that adding this "flow" from the media viewer to the PDF viewer will ensure that the user is logged in, and then if we send the credentials, and Stacks sends the more explicit CORS header it should work properly?

Based on [the comment](https://github.com/sul-dlss/sul-embed/blob/main/app/components/embed/media_tag_component.rb#L130) that @jcoyne added around that access restricted overlay code it sounds like the approach might be in flux? Perhaps pushing this work forward requires some coordination with that workcycle team?

**Comment by peetucket** [comment]
Yes, I would think we would want to coordinate/switch this to the other workcycle team.  They are likely to have a better understanding of how it was implemented in the past for media.

**Comment by lwrubel** [comment]
Here's the ticket in the backlog that's related to designing the auth flow and keeping it aligned with the approach the Media team is working on: https://github.com/sul-dlss/sul-embed/issues/1757

**Comment by peetucket** [comment]
Note: still does not work when PDF is viewed with `<embed>` tag (as tested by embedding that PURL locally when running https://github.com/sul-dlss/sul-embed/pull/1832).  So I think we need this change regardless of how we end up viewing PDFs in sul-embed.

**Comment by edsu** [comment]
@peetucket thanks for checking. I'm assuming you were logged in?

**Comment by peetucket** [comment]
> @peetucket thanks for checking. I'm assuming you were logged in with Stanford SSO? If you were viewing purl on `localhost` the request to a `stanford.edu` host to fetch the PDF wouldn't include the cookie? To really test I think you'd want to see if it works from a purl at a `stanford.edu` address?

Yes, I think you are right.  We will want to deploy so the server request comes from a stanford.edu address.  On localhost I tried both logged in and not logged in and neither worked.

**Comment by edsu** [comment]
If we are going to move forward with embedding PDFs I wonder if we could declare this issue closed and proceed to work on #1757 which will be required for the display of Stanford Only PDFs?

**Comment by edsu** [comment]
I can see that Stacks already [has logic](https://github.com/sul-dlss/stacks/blob/main/app/controllers/media_controller.rb#L35-L43) to set `Access-Control-Allow-Origin` to `embed.stanford.edu` for WOWZA media streaming.

I think @peetucket's proposed change in https://github.com/sul-dlss/stacks/pull/1063/files#diff-508dc4a435ef4322de1c14f240d813c4c9d892d9dc837389a1ee57641b66c607R30 will take care of part 2 of this ticket: "Stacks responds to requests for Stanford Only files with a Access-Control-Allow-Origin: https://embed-stage.stanford.edu CORS header."

**Comment by peetucket** [comment]
> I can see that Stacks already [has logic](https://github.com/sul-dlss/stacks/blob/main/app/controllers/media_controller.rb#L35-L43) to set `Access-Control-Allow-Origin` to `embed.stanford.edu` for WOWZA media streaming.
> 
> I think @peetucket's proposed change in https://github.com/sul-dlss/stacks/pull/1063/files#diff-508dc4a435ef4322de1c14f240d813c4c9d892d9dc837389a1ee57641b66c607R30 will take care of part 2 of this ticket: "Stacks responds to requests for Stanford Only files with a Access-Control-Allow-Origin: `https://embed-stage.stanford.edu` CORS header."

So actually I am not sure it will, since this header is only being added for the `auth` endpoint, not the actual serving of files.  We are also moving away from the PR towards a more generic IIIF probe service. However, if we do need the CORs headers, we could try adding just that header for the `FileContoller#show` endpoint.

**Comment by edsu** [comment]
We've decided to close this since we have #1919 to ensure that users know that they need to log in to view a Stanford Only PDF. Once a user is logged into Stacks we can choose to [embed the PDF](https://github.com/sul-dlss/sul-embed/blob/main/config/settings.yml#L65) which does not require CORS changes in Stacks.
