### ISSUE TITLE
Designs for narrow viewports

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/sul-embed#1658]
Below 880px or so the view starts to break down.  We should have designs for how the viewer should adapt.

**Comment by alundgard** [comment]
The width of the left companion window (sidebar) should not resize responsive to viewport width. Following Mirador, the sidebar's vertical tab group always has a width of 50px, while the sidebar content has a width of 235px. This ensures that sidebar content is always legible.
![Image](https://github.com/sul-dlss/sul-embed/assets/2343316/0a371269-90c1-423d-830c-9fafd1cc6d84)

**Comment by alundgard** [comment]
For the modal dialog boxes (not the popover menu), let's do this for now:

Margin around the dialog box: 32px
Min-width: min-width of the viewer minus 64px
Max-width: 600px
Height: height of the viewer minus 64px
