### ISSUE TITLE
Info companion window on media player should contain bibliographic information 

### ISSUE THREAD

**Issue by dinahhandel** [sul-dlss/sul-embed#1664]
### Expected behavior
Just as it does in Mirador, the info icon companion window should contain bibliographic information about the object. The information that displays in the mirador viewer is a good guideline for this. 

### Actual behavior
Currently the media player's updated design has an info panel that contains information about accessibility. We propose that accessibility information should be elsewhere.

**Comment by dinahhandel** [comment]
@lwrubel did you mean to close this ticket?

**Comment by lwrubel** [comment]
Ack, definitely no! Was moving cards on our ZenHub board and must have hit something accidentally. Thank you for catching and re-opening.

**Comment by dinahhandel** [comment]
Confirming from a slack thread: we should render the IIIF metadata in the info panel.

**Comment by dinahhandel** [comment]
@andrewjbtw it occurs to me that our stage objects might be lacking in MODs metadata. Is that something you could add for a few items?

**Comment by andrewjbtw** [comment]
Yes - I think it's about 50/50 which have MODS and which don't. I'm going to backfill at least the ones that match production objects.
