### ISSUE TITLE
Add accessibility icon to right side of header navigation bar to create accessibility modal and update accessibility language

### ISSUE THREAD

**Issue by dinahhandel** [sul-dlss/sul-embed#1666]
### Expected behavior
A user can see and click an accessibility icon on the header navigation bar and it opens a modal with accessibility information.

The language for requesting a transcript caption should always display. "To request a transcript or other accommodation for this media item, please send a request along with a link to this item to purl-feedback@lists.stanford.edu." When the user clicks that email link, pre-populate the email subject with the page's druid.

The language for whether there is already a downloadable transcript should only appear if the following conditions are met: There is a file resource, the label of that file resource contains "transcript", and the rights of the resource file allow world or Stanford download. If the conditions are met, the language should read: "Click the share & download icon to download a transcript"

If we can't employ this logic and conditionally display a message in the accessibility modal, the language should read: "A transcript may be available for download. Click the share & download icon to see if a download is available.

**Comment by alundgard** [comment]
Related to #1673.

See the "Single Companion Window Desktop" prototype in the [Figma Design](https://www.figma.com/file/ADNitlk4aWHDiPDWD1dHdF/Media-Work-Cycle---Media-Player?type=design&node-id=0-1&mode=design
). [Click the "Present" play arrow in the top-right corner and select this prototype.]

**Comment by dinahhandel** [comment]
I'm noticing that in the current implementation, the text is incorrect within the accessibility modal. There is an OR and it isn't clear that the druid will show up in the email subject. Is that because those features/logic weren't possible to achieve (only show a message about download if there is a downloadable transcript)? 
![Screenshot 2023-11-08 at 10 56 55 AM](https://github.com/sul-dlss/sul-embed/assets/9371978/5c93034e-5c18-4c37-bb47-8310ab81eba9)


If so, the text should read: 

To request a transcript or other accommodation for this media item, please send a request along with a link to this item to [purl-feedback@lists.stanford.edu](mailto:purl-feedback@lists.stanford.edu).

A transcript may be available for download. Click the share & download icon to see if a download is available.

**Comment by dinahhandel** [comment]
Now I see https://github.com/sul-dlss/sul-embed/issues/1705. It would be helpful if that were linked from the original ticket.
