### ISSUE TITLE
Add aria-label or aria-labelledby to the tab buttons on media viewer

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/sul-embed#1669]
The 3 for the left bar and the two for the right bar and the hamburger menu.

https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-labelledby

**Comment by aaron-collier** [comment]
@jcoyne Just to clarify as I'm new to sul-embed, are the 3 tab buttons in the hamburger menu referenced the information, copyright, and index buttons as seen here? What about the 2 in the right bar, i'm not seeing a right bar currently, thank you.

![Image](https://github.com/sul-dlss/sul-embed/assets/2294288/432e6a7b-99cf-4d73-a240-7111b57d86cf)

**Comment by aaron-collier** [comment]
@jcoyne disregard, paring with @mjgiarlo moved me along here.
