### ISSUE TITLE
Display which reading room access is restricted to

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/sul-embed#1671]
Currently stacks just returns `{"status":["location_restricted"]})` so there is no way of displaying the reading room name as designed.
https://stacks.stanford.edu/media/bb099mt5053/bb099mt5053_sl.m4a/auth_check

**Comment by andrewjbtw** [comment]
The information is in the rightsMetadata in the public XML.

**Comment by jcoyne** [comment]
@andrewjbtw Do we want to say "ars" or should we decode these locations into something more intelligible? If so, can you provide labels for 'spec', 'music', 'ars', 'art', 'hoover',  and 'm&m'?

**Comment by andrewjbtw** [comment]
- loc: ars - Archive of Recorded Sound
- loc: art - Art Library
- loc: spec - Special Collections
- loc: hoover - Hoover Institution Library & Archives
- loc: music - Music Library
- loc: m&m - Media & Microtext Center

**Comment by jcoyne** [comment]
Test on https://sul-purl-stage.stanford.edu/bq834ky5156
