### ISSUE TITLE
Accessibility audit of PDF viewer

### ISSUE THREAD

**Issue by lwrubel** [sul-dlss/sul-embed#1680]
Conduct an accessibility audit of the PDF viewer, to support creating tickets for remediation work.  

Example purl: https://purl.stanford.edu/bb065bh7591

**Comment by peetucket** [comment]
See https://docs.google.com/spreadsheets/d/155sBaCt9dJ3Hy-6mjx3leaCgIDdQ77EhMZabdOLhcRM/edit#gid=0 for process and some issues recorded from tools

**Comment by dbranchini** [comment]
I'm encountering an inconsistent issue with the VoiceOver (Apple product) screenreader. Sometimes it's skipping content and sometimes, it's not, but I can't see a pattern.
