### ISSUE TITLE
Accessibility audit of the geo viewer

### ISSUE THREAD

**Issue by lwrubel** [sul-dlss/sul-embed#1681]
Conduct an accessibility audit of the geo viewer, to support creating tickets for remediation work.

Example purl: https://purl.stanford.edu/fp756wn9369

See https://docs.google.com/spreadsheets/d/155sBaCt9dJ3Hy-6mjx3leaCgIDdQ77EhMZabdOLhcRM/edit#gid=0 for process and how to record

**Comment by lwrubel** [comment]
Intended for @dbranchini or @thatbudakguy to pick up when able.

**Comment by dbranchini** [comment]
Completed review of map viewers. It's captured fully on the [Accessibility Audit SS](https://docs.google.com/spreadsheets/d/155sBaCt9dJ3Hy-6mjx3leaCgIDdQ77EhMZabdOLhcRM/edit?usp=sharing), see tab labeled Maps.
