### ISSUE TITLE
Accessibility audit of the web archive viewer 

### ISSUE THREAD

**Issue by lwrubel** [sul-dlss/sul-embed#1682]
Conduct an accessibility audit of the web archive viewer, to support creating tickets for remediation work.

Example purl: https://purl.stanford.edu/gb089bd2251

**Comment by ndushay** [comment]
is this for Darcy?

**Comment by lwrubel** [comment]
Yes, this is intended for @dbranchini or @thatbudakguy.

**Comment by dbranchini** [comment]
Done, no issues specific to this viewer were found. Of course, archival content varies greatly and will likely vary in its accessibility compliance.
