### ISSUE TITLE
Send analytics data to the metrics service

### ISSUE THREAD

**Issue by thatbudakguy** [sul-dlss/sul-embed#1683]
We need to use [ahoy.js](https://github.com/ankane/ahoy.js) to communicate with the [new metrics API](https://github.com/sul-dlss/metrics).

For all viewers, we want to track:
- views (when the `/iframe` response is initially rendered, call `ahoy.trackView()`)
- downloads (call `ahoy.track('download', ...)`)
- where the event originates from (i.e. the domain outside the iframe)

**Comment by jcoyne** [comment]
@thatbudakguy should download events be tracked via Stacks?  Not all downloads have to originate from sul-embed.

**Comment by thatbudakguy** [comment]
is there a way to distinguish "the user asked to download this" from "some other program is requesting the file" in stacks?

it looks like we set the `download` attribute (in the file viewer at least) on the download links; is that what powers [the download detection in stacks](https://github.com/sul-dlss/stacks/blob/561e51eb4842206d325dafa103758ec3139fb910/app/controllers/file_controller.rb#L32-L36)?

**Comment by jcoyne** [comment]
yes, that attribute impacts the content-disposition. I'm wondering if the users want to know when their file is downloaded when someone posts a link to social media and doesn't get it from purl.

**Comment by thatbudakguy** [comment]
it sounds like that might not be too hard to do. i'll run this by the workcycle team and test it out locally.

**Comment by jcoyne** [comment]
I'm not sure what the "it" is you're referring to.

**Comment by thatbudakguy** [comment]
I guess what I'm worried about is platforms using the stacks URL to serve, display, or otherwise use the content that isn't "the user asked to download this". Don't we need to make sure to only track a file download if the user was explicitly invoking a download action? the presence of the download attribute seems like the right way to unambiguously indicate that.

**Comment by thatbudakguy** [comment]
@jcoyne looking at stacks a bit more, I can see now that there's:
* `/object/:id`, which is `ObjectsController#show`, that downloads a .zip of all the files
* `/file/:id/*file_name`, which is `FilesController#show`, that serves a single file

it seems like the first one, at least, is an unambiguous "this object was downloaded", since it's the whole object, and the user gets a zipfile. the second one i'm less sure about, because if the disposition _wasn't_ provided, we could just be serving the file for use in a viewer or some other thing that isn't an explicit download to the user's machine.

what do you think?

**Comment by thatbudakguy** [comment]
based on discussion post-standup today, the team is comfortable calling both these scenarios a "download" (and each of them is equivalent; i.e. 1 "download" event) so I think we can move ahead with this plan.

**Comment by thatbudakguy** [comment]
closing this; remaining work is in stacks: https://github.com/sul-dlss/stacks/issues/1048
