### ISSUE TITLE
Modal body should scroll  vertically on media viewer

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/sul-embed#1703]
Similar to the behavior in mirador

![Image](https://github.com/sul-dlss/sul-embed/assets/92044/6cbd633a-72e5-454b-a914-898c17e28055)

**Comment by mjgiarlo** [comment]
This is for the share modal in the new media player, not the download modal which does scroll vertically already.

**Comment by jcoyne** [comment]
This now has a scroll
