### ISSUE TITLE
Add default poster for locked media with no thumbnail

### ISSUE THREAD

**Issue by alundgard** [sul-dlss/sul-embed#1706]
When media objects are (b)locked due to access restrictions, an access restriction message is shown to users. Also, an empty (blank white) native video player is still rendered. This player appears to users as broken: non-interactive, non-functional.
- When the media object has a corresponding thumbnail image, use this thumbnail as the "poster" rendered in the native video player. (NB: the player should remain non-functional, as the media content is still locked.)
- When the media object has no thumbnail image, use the default `locked-media-poster.svg` thumbnail for locked media attached below.
![Image](https://github.com/sul-dlss/sul-embed/assets/2343316/10a2f9ac-2f08-494b-b72a-a57d70817d0b)

**Comment by jcoyne** [comment]
Test with https://sul-purl-stage.stanford.edu/dp213qm6802

**Comment by jcoyne** [comment]
@alundgard I think there is a problem, as there doesn't seem to be a media player on the page for locked items: See https://sul-purl-stage.stanford.edu/dp213qm6802

**Comment by alundgard** [comment]
Strange... when I'm not authenticated, I see a player for the video link, but it's showing the audio placeholder thumbnail? And yes, I don't see a media player for the audio link. From your Slack thread, my understanding was that access restrictions block VideoJS, but the native player is still rendered. Is that only the case for reading room restrictions?

**Comment by jcoyne** [comment]
The audio image on videos was just a test branch I pushed up for testing.  The poster is shown by videojs, but we don't initialize videojs until the authentication is successful.
<img width="586" alt="Screenshot 2023-11-09 at 9 42 31 AM" src="https://github.com/sul-dlss/sul-embed/assets/92044/183852cc-a576-4aa1-9983-f1d2eb9282b3">
