### ISSUE TITLE
Text for no available files

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/sul-embed#1709]
What should we show if there are no visible files:

![Image](https://github.com/sul-dlss/sul-embed/assets/92044/a90b1fe6-6658-4291-be08-ad087e1d3b3e)

For example: https://sul-purl-stage.stanford.edu/cy304fm5998

**Comment by alundgard** [comment]
I checked with the POs. Let's do "No downloads available" in place of the "Files" header. Thanks!
