### ISSUE TITLE
Transcript view in media player 

### ISSUE THREAD

**Issue by dinahhandel** [sul-dlss/sul-embed#1710]
### Expected behavior
On the left hand companion window, add an icon to signify transcript display. When that icon is selected, the window remains open as the user clicks play, and the transcript displays and scrolls alongside the media. The transcript data would come from the .vtt file. 

Nice to have: 

1. The transcript is searchable in the media player. 
2. The transcript could be clicked and the user taken to that portion in the video ([like Able player](https://ableplayer.github.io/ableplayer/demos/video3.html)).

### Actual behavior
Currently, we only display the .vtt file as captions.

**Comment by alundgard** [comment]
See the "Transcript Display" and "Single Companion Window Desktop" prototypes in the [Figma Design](https://www.figma.com/file/ADNitlk4aWHDiPDWD1dHdF/Media-Work-Cycle---Media-Player?type=design&node-id=0-1&mode=design
). [Click the "Present" play arrow in the top-right corner and select these prototypes.]
![Image](https://github.com/sul-dlss/sul-embed/assets/2343316/f8a89e8b-d3f7-4bcf-84fd-a39ac3d2cd02)

Priority order of desired transcript features:

1. **Display transcript.** Auto-sync the transcript scroll with video playback. Highlight (light blue) the transcript segment currently playing. Auto-sync is active by default, and can be switched off via a button.

2. **Clickable transcript segments.** On hover, a transcript segment receives styling (light gray background), indicating that it is clickable. Clicking a segment jumps the video playback to its corresponding timestamp.

3. **Selectable language.** Via a dropdown in the transcript panel, a user can select to display a different language (if available). To be determined: whether the transcript and caption languages should always correspond, or whether the user can select a different language for each.

4. **Searchable transcript.** Ideally, via a Searchbar in the transcript panel. Or, via Ctrl+F in the web browser. A match for the user's search query jumps the transcript to the corresponding segment, and highlights the matching string.

**Comment by jcoyne** [comment]
I've split this ticket into separate pieces that are somewhat more manageable in size.

**Comment by mjgiarlo** [comment]
Because of ☝, we're closing this ticket.
