### ISSUE TITLE
File names for content accessed via the file viewer

### ISSUE THREAD

**Issue by dbranchini** [sul-dlss/sul-embed#1724]
Question:
Is it possible to add an additional field to deposited files so that we have a user-friendly (something more descriptive) name to display? It would be helpful to list the friendly name for all users, but especially screen reader users. Consider this file name "dw873kh6992_0001_box1_front.jpg", it doesn't tell users anything about this particular file, and a screen reader will read every letter and number separately. If you're perusing a whole list of items with names like this, it would be difficult to discern what you need. We have the description field too, but in some cases, especially when it's really long, it's not helpful either when someone is quickly scanning the files for something in particular or trying to make sense of what's there and how it's organized. 

Or could we simply (or do we already) encourage depositors to use friendlier names as their file name? Even file names such as MarineMammal_FL_OTUreps_1365_Fasta.txt are handled much better by a screen reader. It smartly picks out full words and reads them.

**Comment by andrewjbtw** [comment]
We can definitely encourage depositors to use friendlier file names when they have a choice, but there are many situations where depositors themselves have limited control over file names. The names could be set by the software they use to produce data, or in the case of born-digital special collections material, the filenames could have been set long before the items were donated to the library. There are 22 million files in SDR, though the total number visible in the file viewer is only about 200,000 as of today. I don't think we could expect more than a small percentage of those files to get description beyond the file name itself.

That said, there is a field in the data model that could be used to label individual files - separate from the label field that is already displayed - but it has not been fully implemented and will not display. It's currently being populated with the filename automatically when files are deposited, and self-deposit users do not have an interface for entering data in the field. There are a few design challenges to making that field editable and displayable in our various deposit and viewer interfaces. And a big metadata challenge.

**Comment by dbranchini** [comment]
Thank you, @andrewjbtw , for your thoughts on this idea. @thatbudakguy , do you have anything to add or is there anyone else we should seek feedback from?

**Comment by amyehodge** [comment]
I've previously noted that for self-deposit, we can't display more than 250 files in the form, which means in those situations users can't provide the optional description, which can be helpful in some cases. I agree with @andrewjbtw 's assessment.

**Comment by justinlittman** [comment]
@dbranchini Is there anything actionable or can this ticket be closed?

**Comment by dbranchini** [comment]
It sounds like there's nothing actionable. I hope that we can add some language to the depositor form/process to encourage friendlier file names moving forward. I'll close.
