### ISSUE TITLE
PDF accessibility - content (document itself) + viewer

### ISSUE THREAD

**Issue by dbranchini** [sul-dlss/sul-embed#1725]
In reviewing the pdf viewer, it came to my attention that the pdf itself (the content) is not read by a screen reader. This is partially a content question/issue and partially a viewer question. First, I wondered if the PDF examples I was provided were not OCR'ed, and therefore the screen reader skips them because it can't read them. OCR is required for a PDF to be accessible. (There are other requirements, but OCR is the baseline.) So I asked @andrewjbtw if he could point me to any PDFs that are already OCR'ed and currently accessed through the PDF viewer. His answer was this:

"When someone wants to make a PDF searchable within sul-embed, the workflow is to convert the PDF to images and run it through OCR (even if the PDF is already searchable) and then present it in the image viewer (which supports search of OCR)."

Note: searchable is not the same as accessible, but related. It's just not clear to me whether our current PDF viewer would handle an OCR'ed PDF any differently - meaning would it skip over the PDF anyway? Something else to note is that you can page through the document and zoom in/out using the screen reader (using the forward/back buttons), but you can't actually access any of the content while doing that. 

Because we provide a preview to the PDF for visual users, ideally we should also provide an equivalent experience for screen reader users, which includes blind users as well as other types of users, such as dyslexic users.  @alundgard , please let me know if you feel differently. 

I propose a fuller discussion about this.

**Comment by dbranchini** [comment]
These are the two PDFs that I used in my accessibility review of the PDF viewer:

- https://embed.stanford.edu/iframe?url=https://purl.stanford.edu/bb065bh7591&_v=1699395509
- https://embed.stanford.edu/iframe?url=https://purl.stanford.edu/cd243px7965&_v=1699395509

**Comment by andrewjbtw** [comment]
As I mentioned yesterday, many of our PDFs (including both examples above), already have text layers. The workflow I described of splitting PDFs into images in order to OCR those images is a workaround for the fact that our PDF viewer ignores the text in the PDFs. People follow that workflow even if the PDF already was OCR'd.

**Comment by andrewjbtw** [comment]
Here's a stage example of a PDF generated with OCR from scanned images: https://sul-purl-stage.stanford.edu/pr516jm0127

And here is the same document in the book viewer: https://purl.stanford.edu/tk236rn7575 In the book viewer, the search is using the same OCR but not directly from the PDF.

**Comment by andrewjbtw** [comment]
I've made a PDF test set on stage: https://argo-stage.stanford.edu/catalog?f%5Bis_governed_by_ssim%5D%5B%5D=info%3Afedora%2Fdruid%3Awf156nd2073

This PDF has no OCR: https://sul-purl-stage.stanford.edu/br379jx5150

The set also includes various different rights scenarios. It appears that only world-viewable, world-downloadable PDFs actually display in the viewer.

**Comment by lwrubel** [comment]
@dbranchini is creating a report to fulfill this ticket, to bring to a broader group of stakeholders.

**Comment by dbranchini** [comment]
https://docs.google.com/document/d/1ed4NZGF4TXJJF4lhWysCWufcO03F9WgUcqrXE0XVhM8/edit?usp=sharing
