### ISSUE TITLE
Accessibility audit of the replacement 3d viewer

### ISSUE THREAD

**Issue by lwrubel** [sul-dlss/sul-embed#1745]
Conduct an accessibility audit of the replacement 3d viewer, ModelViewer, based on an example in sul-embed, to lead to creating tickets for remediation work.

**Comment by dbranchini** [comment]
Completed review of the 3d viewer titled, <model-viewer>. It's captured fully on the [Accessibility Audit SS](https://docs.google.com/spreadsheets/d/155sBaCt9dJ3Hy-6mjx3leaCgIDdQ77EhMZabdOLhcRM/edit?usp=sharing), see tab labeled 3D.

**Comment by lwrubel** [comment]
@edsu is investigating any further needed tickets based on further research.

**Comment by dbranchini** [comment]
Two issues for further investigation:

- Keyboard-only navigation for zoom in/out 
- Stage views - better descriptions for each of the potential stage views upper/lower, left/right, and front/back views (instead of the default "viewing stage left", "viewing stage upper left back", etc.

**Comment by edsu** [comment]
Maybe these will break out into separate tickets, but I added these two follow on tasks to the checklist in #1486.
