### ISSUE TITLE
Create mapping of BCP 47 tags to label strings for file languages

### ISSUE THREAD

**Issue by mjgiarlo** [sul-dlss/sul-embed#1753]
We use BCP 47 tags in file languages, and when a resource has e.g. multiple captions in different languages, we want to render a user-friendly label like `English captions` or `Russian captions`. To accomplish this, given we have no reliably way to translate BCP 47 tags into label strings, we'll roll with a mapping for the most common language tags and their labels, such as:

```
en: English
ru: Russian
```

This is for @dinahhandel and @andrewjbtw

**Comment by hudajkhan** [comment]
I think this also relates to #1588 since the captions options are identified by BCP 47 codes in the PURL and the labels for these need to be displayed in the captions options in the video player.

**Comment by dinahhandel** [comment]
Here's what we should start with when it comes to language mappings:

en: English
ru: Russian
de: German
et: Estonian
lv: Latvian
es: Spanish

These are the only mappings we currently need.

**Comment by dinahhandel** [comment]
Is this ticket still relevant, given #1765?

**Comment by mjgiarlo** [comment]
@dinahhandel I think we can close it with the comment above.
