### ISSUE TITLE
Upgrade pdf.js to v4

### ISSUE THREAD

**Issue by thatbudakguy** [sul-dlss/sul-embed#1756]
Version 4 was released two weeks ago.

We would also like to revisit whether we're disabling lots of quality-of-life features that come with pdf.js, and turn them on so that they are available to users. The UI for our current viewer is very different from [the pdf.js v4 default](https://mozilla.github.io/pdf.js/web/viewer.html).

**Comment by lwrubel** [comment]
@thatbudakguy we noted in this ticket that we want to revist the features we have turned off in pdf.js, once we're on version 4. I don't see a ticket for that--would you want to create a ticket to reflect what the next step is with determining whether to use further features?

**Comment by thatbudakguy** [comment]
Copied the part of this ticket that didn't get done into https://github.com/sul-dlss/sul-embed/issues/1791.
