### ISSUE TITLE
Make login flow for PDF viewer consistent with Media player

### ISSUE THREAD

**Issue by lwrubel** [sul-dlss/sul-embed#1757]
To support Stanford-only viewing of PDFs in the pdf viewer, a design for the login flow and banners needs to be created. This is to be implemented once the viewer is upgraded to the latest version in #1756. Goal is to be consistent with what @alundgard has designed for the media player.

Media example: https://purl.stanford.edu/bb142ws0723

**Comment by andrewjbtw** [comment]
Here's an example in stage for a Stanford-downloadable PDF: https://sul-purl-stage.stanford.edu/xj550hm9593

You can see that when you go to the downloads list, you get sent through Stanford authentication to download the PDF. We're missing an authentication step to show the PDF in the viewer (if that ends up being possible).

**Comment by andrewjbtw** [comment]
Related ticket: https://github.com/sul-dlss/sul-embed/issues/1642

**Comment by dbranchini** [comment]
Alan designed the following for the login/logout user flow. https://www.figma.com/proto/ADNitlk4aWHDiPDWD1dHdF/Media-Work-Cycle---Media-Player?page-id=0%3A1&type=design&node-id=1131-7205&viewport=-5788%2C-197%2C1&t=osFnWykRUSnJuAuG-1&scaling=min-zoom&starting-point-node-id=1131%3A7205&show-proto-sidebar=1&mode=design.

**Comment by thatbudakguy** [comment]
Relevant UI code used in the media player:

https://github.com/sul-dlss/sul-embed/blob/main/app/javascript/src/controllers/auth_restriction_controller.js

and

https://github.com/sul-dlss/sul-embed/blob/e94ed320381c566a967800c71118b89e5a3e9fe1/app/components/embed/media_with_companion_windows_component.html.erb#L17-L50

**Comment by lwrubel** [comment]
Wait until work on Media viewer is completed, and then draw from that to implement.

**Comment by peetucket** [comment]
Some analysis written up here: https://docs.google.com/document/d/17nhSWDp28CocKsBdcZvtqAOMiNbLnVspBRXENSr6m84/edit

**Comment by lwrubel** [comment]
Closing as work is covered by https://github.com/sul-dlss/sul-embed/issues/1919
