### ISSUE TITLE
images of physical media appear to be in the center top of the window

### ISSUE THREAD

**Issue by dinahhandel** [sul-dlss/sul-embed#1760]
### Expected behavior
Is it possible to center the image of media instead of it being in the center but right along the top bar?

### Actual behavior
This is actually how the current media player also behaves, but I think it looks odd.

Current: 
![Screenshot 2023-11-16 at 3 45 05 PM](https://github.com/sul-dlss/sul-embed/assets/9371978/3a2765ee-0d20-486c-9b25-9d46bcdda163)

New in stage: 
![Screenshot 2023-11-16 at 3 45 28 PM](https://github.com/sul-dlss/sul-embed/assets/9371978/6a3aed18-ab99-4e20-b725-58207b2c8951)

**Comment by mjgiarlo** [comment]
Fixed by work on #1564
