### ISSUE TITLE
image indicating audio should display prior to user login

### ISSUE THREAD

**Issue by dinahhandel** [sul-dlss/sul-embed#1761]
### Expected behavior
There is an image used that indicates something is an audio media object. This image should display prior to the user logging in.

### Actual behavior
The current screen is blank/white and shows a scrub bar at the bottom.
![Screenshot 2023-11-16 at 3 57 39 PM](https://github.com/sul-dlss/sul-embed/assets/9371978/f642dffd-385c-41cf-96ec-02536e9368b4)

### Steps to reproduce the behavior
If already authenticated in, open in incognito window: https://sul-purl-stage.stanford.edu/yh788wh7909

**Comment by mjgiarlo** [comment]
This is specifically to display the default poster image for audio for audio-type objects that require user login. Because VideoJS handles posters currently, we recommend drawing a `<div>` or the like atop the audio element and hiding it after successful authentication.

**Comment by mjgiarlo** [comment]
We could try converting the default audio poster from an SVG to a PNG. That may be the easiest thing to do.

**Comment by mjgiarlo** [comment]
video/audio, restricted/world, has poster/lacks poster, pre-login/post-login, examples

<table>
<th>
 <td>Type
 <td>Access
 <td>Poster
 <td>Example URL
 <td>Pre-login display
 <td>Post-login display
<tr>
 <td>Video
 <td>Open
 <td>Has Poster
 <td>Object's poster
 <td>Object's poster
 <td>
<tr>
 <td>Video
 <td>Open
 <td>Lacks Poster
 <td>Default waveform poster
 <td>Default waveform poster
 <td>
<tr>
 <td>Video
 <td>Restricted
 <td>Has Poster
 <td>Locked poster
 <td>Object's poster
 <td>
<tr>
 <td>Video
 <td>Restricted
 <td>Lacks Poster
 <td>Locked poster
 <td>Default waveform poster
 <td>
<tr>
 <td>Audio
 <td>Open
 <td>Has Poster
 <td>Object's poster
 <td>Object's poster
 <td>
<tr>
 <td>Audio
 <td>Open
 <td>Lacks Poster
 <td>Default waveform poster
 <td>Default waveform poster
 <td>
<tr>
 <td>Audio
 <td>Restricted
 <td>Has Poster
 <td>Locked poster
 <td>Object's poster
 <td>
<tr>
 <td>Audio
 <td>Restricted
 <td>Lacks Poster
 <td>Locked poster
 <td>Default waveform poster
 <td>
</table>

**Comment by dinahhandel** [comment]
Correct, @mjgiarlo . Are you looking for an example of a Stanford only PURL where the object has a poster?

**Comment by mjgiarlo** [comment]
@aaron-collier would ☝🏻 be helpful or nah?

**Comment by jcoyne** [comment]
@mjgiarlo @dinahhandel I'm not sure the second to the last row is right. https://sul-purl-stage.stanford.edu/vb426ft3634 is the corresponding video one and we show the object thumbnail, so shouldn't we do the same for video?

**Comment by mjgiarlo** [comment]
@jcoyne 💬 
> @mjgiarlo @dinahhandel I'm not sure the second to the last row is right. [sul-purl-stage.stanford.edu/vb426ft3634](https://sul-purl-stage.stanford.edu/vb426ft3634) is the corresponding video one and we show the object thumbnail, so shouldn't we do the same for audio?

I defer to @dinahhandel and @andrewjbtw.

**Comment by andrewjbtw** [comment]
Isn't this the subject of the ticket? Showing an audio image prior to login?

If I'm reading the chart right, it's the intended behavior, right? Not the existing behavior where the pre-login display is a blank viewer.

**Comment by jcoyne** [comment]
@andrewjbtw I think we were focused on showing the default audio thumbnail, but I wanted to make sure we show the objects thumbnail if one exists, if that is the intended design.

**Comment by andrewjbtw** [comment]
Confirmed in the planning meeting that we want to show the thumbnail if one exists, otherwise show the default.
