### ISSUE TITLE
Auto-scroll transcript

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/sul-embed#1804]
Auto-sync the transcript scroll with video playback. Highlight (light blue) the transcript segment currently playing. Auto-sync is active by default, and can be switched off via a button.

See the "Transcript Display" and "Single Companion Window Desktop" prototypes in the [Figma Design](https://www.figma.com/file/ADNitlk4aWHDiPDWD1dHdF/Media-Work-Cycle---Media-Player?type=design&node-id=0-1&mode=design
). [Click the "Present" play arrow in the top-right corner and select these prototypes.]
![Image](https://github.com/sul-dlss/sul-embed/assets/2343316/f8a89e8b-d3f7-4bcf-84fd-a39ac3d2cd02)

**Comment by alundgard** [comment]
Small design update:
- Give the Transcript settings `<div>` (containing Autoscroll, Language) the same background color as the "Transcript" heading, shown [here](https://www.figma.com/proto/ADNitlk4aWHDiPDWD1dHdF/Media-Work-Cycle---Media-Player?page-id=0%3A1&type=design&node-id=1031-3748&viewport=-376%2C-392%2C2&t=ae2DaZgSEVPDsdCi-1&scaling=min-zoom&starting-point-node-id=1031%3A3748&show-proto-sidebar=1&mode=design). 
- This is intended to emulate the Mirador styling. For example, see the "Index" tab in the Sidebar, here: https://purl.stanford.edu/zw786bb8487

**Comment by mjgiarlo** [comment]
@hudajkhan do you think we can close this issue?

**Comment by hudajkhan** [comment]
Yes. Closed by #1916
