### ISSUE TITLE
File viewer with single file can be scrolled into confusing state

### ISSUE THREAD

**Issue by thatbudakguy** [sul-dlss/sul-embed#1811]
See related https://github.com/sul-dlss/sul-embed/pull/1147, where we set the viewer height in the case that there's only a single file.

Even with this change, there's still quite a lot of empty space under the single file, which can lead to a situation where you scroll and the viewer appears empty:

![Screenshot 2023-11-21 at 15 54 49](https://github.com/sul-dlss/sul-embed/assets/4924494/282c7981-c702-468f-9e7b-80328d6988b3)

@vivnwong experienced this when giving a demo, which is part of why it'd be nice to make it so that you can't scroll into "empty space".

Screenshot taken of https://purl.stanford.edu/tr171zs0069.

**Comment by peetucket** [comment]
I just tried removing this one small recent change in localhost which added a min-height of 189 to the CSS: https://github.com/sul-dlss/sul-embed/pull/1147/files#diff-38e0fb4859a070ef8a0dde01e3c4e80183d4d11925cc41390802b59f698140fdR81

and that eliminated the extra white space to me.  It also rendered a different file list with many files correctly.  I'm not sure if there are other impacts of removing that CSS though.

See #1820

**Comment by andrewjbtw** [comment]
What happens when you click the "i" and "share" panels in a viewer without that minimum height? It sounds like that's what motivated the minimum height.

**Comment by peetucket** [comment]
Ahh, interesting.  Those panels are larger than the viewport, but have scrollbars.  So not ideal, but still accessible:

![Screen Shot 2023-11-22 at 11 53 11 AM](https://github.com/sul-dlss/sul-embed/assets/47137/b50b48b8-7faa-4e1d-8ba6-8316bb7539f6)


![Screen Shot 2023-11-22 at 11 53 05 AM](https://github.com/sul-dlss/sul-embed/assets/47137/05f95811-6509-4c89-91db-c6d858949369)

**Comment by peetucket** [comment]
Actually, just noticed that's not any different than the current view in production for those panels.

**Comment by vivnwong** [comment]
Part of the bug's problem was that no scroll bar displayed when the file was scrolled off the viewer area. We only saw a empty display and I was not successful in making the scroll bar happen at the time.

**Comment by peetucket** [comment]
I think this PR will make it so that you cannot scroll to a blank area anymore - the height of the file list is only the size of the single file available.  I can't find any new problems it creates.
