### ISSUE TITLE
Fix left drawer scroll behavior

### ISSUE THREAD

**Issue by alundgard** [sul-dlss/sul-embed#1817]
**Horizontal scroll.** The left drawer content should not scroll horizontally. Text/links that overflow the drawer width should be wrapped. (NB: the Media Content section also has horizontal overflow.) Example: https://sul-purl-stage.stanford.edu/xs884bk3832.
![Image](https://github.com/sul-dlss/sul-embed/assets/2343316/2da2fe1c-1a45-4d5d-ba55-1b6b86de25e8)

**Vertical scroll.** The left drawer vertical scroll should not be clipped by the embed view. Example: https://sul-purl-stage.stanford.edu/bq834ky5156.
![Image](https://github.com/sul-dlss/sul-embed/assets/2343316/4c0fa08f-7b96-4df7-a12d-eb6393ea86fc)

**Comment by alundgard** [comment]
I see it on Safari, Chrome, Firefox. (cleared the cache for each)

**Comment by jcoyne** [comment]
Sorry, I can't duplicate that behavior in any browser.  Could it be some extension that you've enabled or perhaps the operating system is making it different?

**Comment by andrewjbtw** [comment]
I see the horizontal scroll:

https://github.com/sul-dlss/sul-embed/assets/8975583/5b5fe2cc-39e6-4b56-9234-fe3f0659ee2f

**Comment by andrewjbtw** [comment]
That was on Firefox. I see it in Chrome too but it's slightly less pronounced.
