### ISSUE TITLE
Redesign of file viewer 

### ISSUE THREAD

**Issue by dbranchini** [sul-dlss/sul-embed#1849]
The need for a redesign started with an accessibility issue - in the current design, each item contains two links, and both links go to the same place. Using a screen reader, the user hears each link twice, which might cause confusion and definitely results in audio clutter. See the screenshot in the comment below. Also, because each item contains two separate links, this adds extra tabs to the keyboard navigation to get to an item further down in the list or to the "download all" and share features. Amy Hodge and I then discussed that the call to action in the current design isn't apparent, and to add to it, Justin Coyne reached out to ask about changing the current design slightly because the aesthetic looks off balance. There's a tiny icon in a large square next to each item. I'd also suggest that the iframe window is small vertically, and we don't use the space horizontally very well. Finally, I thought a familiar pattern, such as Mac's Finder, Window's File Explorer or Google Drive, could inspire our redesign since, dare I say, every user will be familiar with one of those tools.

Given the inspiration outlined above, I based my redesign on that, and reviewed it with Amy, Justin, and Andrew Berger. During that conversation, we also discussed the following requirements:

- Preview isn't required. Per Andrew, it's only available on a couple of items, so it shouldn't be propagated to the new design.
- The file viewer is the only viewer with a search feature.
- Download all isn't always available. If it's above a certain size, the user must contact us to obtain the items. 
- There's essentially no character limit on the description. It can be up to 65,000 + characters. The current design limits what is displayed. 
- File numbers aren't required. It's on the current design, but no one knows how they're used and/or if they're used.  

**See below for designs**

**Comment by lwrubel** [comment]
Closed as redesign has been tested and deployed.
