### ISSUE TITLE
sul-embed shows HTTP 401 error for reading-room restricted image

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/sul-embed#1856]
### Actual behavior

With the new zoom-enabled viewer, we are showing a thumbnail for the first image in a sequence of images that accompany reading-room restricted media. This thumbnail is blurry, but that happens elsewhere in Mirador.

The bigger problem is that any images beyond the first image show an HTTP 401 error:

<img width="1206" alt="Screenshot 2023-11-28 at 3 57 44 PM" src="https://github.com/sul-dlss/sul-embed/assets/8975583/e39d3640-90c9-4c24-a3db-476988300503">

### Steps to reproduce the behavior

See stage example  https://sul-purl-stage.stanford.edu/kv136wr6644

### Additional info

In prod, we currently don't show any images for location-restricted media:

<img width="1206" alt="Screenshot 2023-11-28 at 3 59 52 PM" src="https://github.com/sul-dlss/sul-embed/assets/8975583/981f4af2-8d62-4d1f-9852-3d72394602e8">

**Comment by andrewjbtw** [comment]
Another example, but in this case no image shows: https://sul-purl-stage.stanford.edu/fp499wg2591

Given this example, I don't understand what logic is determining when an image shows or doesn't show when there are location restrictions.

**Comment by jcoyne** [comment]
I think this is stacks. Now that we have deep zoom, the image viewer hits the iiif manifest and all the images are not authorized.

**Comment by mjgiarlo** [comment]
The best course of action at this point, given the OSD is the component that handles the 401, may be to display a blank screen and not initialize OSD.
