### ISSUE TITLE
Update caption settings modal style

### ISSUE THREAD

**Issue by alundgard** [sul-dlss/sul-embed#1871]
Give the modal a "Caption settings" header.
<img width="400" alt="caption-settings-header" src="https://github.com/sul-dlss/sul-embed/assets/2343316/25530114-cf27-4fe7-846c-597dceb0bb81">

Make the buttons look like the other modal buttons.
<img width="400" alt="caption-settings-buttons" src="https://github.com/sul-dlss/sul-embed/assets/2343316/431e458a-827e-405f-83d4-cf7efa80bee1">

**Comment by andrewjbtw** [comment]
We think this is done in a PR that's not linked.
