### ISSUE TITLE
Improve viewing of multi-image objects in list view on small screens

### ISSUE THREAD

**Issue by snydman** [sul-dlss/sul-embed#189]
It is confirmed that the image widget is touch compatible (@tomcramer). However, the viewing experience of an individual image that is part of a multi-image object is sub-optimal on small screens.  The screen real estate taken by the horizontal scroll bar limits the viewing and zooming of an individual image. Its not broken but on small screens there should be a way to see more of the individual image. 

Is there an mobile optimized adaptation of the image view that can be invoked when a smaller viewport is detected?  

Maybe default to horizontal view?  @jvine ? Options? Is this an issue?

![image](https://cloud.githubusercontent.com/assets/3279382/5024768/36675e80-6ac4-11e4-8920-4634e48994c6.png)

![image](https://cloud.githubusercontent.com/assets/3279382/5024773/44a1bf4a-6ac4-11e4-995f-d524bf09d6b6.png)

**Comment by mejackreed** [comment]
Resolved in m3
