### ISSUE TITLE
Update access restriction banner messaging

### ISSUE THREAD

**Issue by alundgard** [sul-dlss/sul-embed#1890]
To coordinate the design across sul-embed viewers and content types...
1. For some viewers/content, there are cases where an item's access rights produce an error (e.g., a PDF is Download-Only, and so it can't be rendered in the PDF viewer). When this happens, the viewer currently shows a message that says: "There was an issue viewing this document." We want to include a similar message in our access restriction banner redesign, so we've added the "Error/Warning" message: "**There was an issue viewing this item.**" (see screenshot below)
2. We've changed the Citation Only message from "This **_media_** cannot be accessed..." to "This **_item_** cannot be accessed...", so that the restriction messages are applicable to any content type.
![Image](https://github.com/sul-dlss/sul-embed/assets/2343316/3763aba0-24fb-4e1a-bbc7-4dd9fbb848f6)

**Comment by jcoyne** [comment]
@alundgard with regard to "There was an issue viewing this item." That only shows up in the pdf viewer.  There is no situation in which the media viewer would render a similar message, so I'm not sure what we can do to implement this.

**Comment by alundgard** [comment]
It sounds like the other WC team is going to copy over some of our implementation to the other viewers. Is it possible to include the Error/Warning in the Media implementation (including the icon and message) for completeness, even if we don't currently render it in the Media player? If not, we should note the discrepancy to the other WC team.
