### ISSUE TITLE
Copy icons in share modal don't work in chrome

### ISSUE THREAD

**Issue by dinahhandel** [sul-dlss/sul-embed#1913]
### Expected behavior
When a user clicks the copy icon in the share modal, the text should be copied to the clipboard.

### Actual behavior
Using Chrome, when I click the copy icon, no text is copied to the clipboard. 

https://github.com/sul-dlss/sul-embed/assets/9371978/df661929-f204-4fbb-a98b-629e9ceb8546

### Steps to reproduce the behavior
Using Chrome, open the share & download modal and click the icon to copy the PURL link or the embed text. 

### Browser / Environment
Chrome Version 119.0.6045.159 (Official Build) (x86_64)

**Comment by aaron-collier** [comment]
Ah, we're hitting a permisisons issue: DOMException: The Clipboard API has been blocked because of a permissions policy applied to the current document.

this works locally but not when deployed. Looking into how to address this.
