### ISSUE TITLE
PDF Viewer Auth Flow: Implement sul-embed UI

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/sul-embed#1919]
Part of #1757 - auth flow for PDF viewer

Add files controllers and tags, etc. to UI

See bullet points 3 and 6 here: https://docs.google.com/document/d/17nhSWDp28CocKsBdcZvtqAOMiNbLnVspBRXENSr6m84/edit#heading=h.fknftcv8cgfk

https://docs.google.com/document/d/1IIPYw4CVIaNCjPjtY427JxcPQngd5ZxgqhQLfhxVbi4/edit#heading=h.fuuyr6c6x300

https://iiif.io/api/auth/2.0/#71-authorization-flow-algorithm

Note that auth service should also indicate if a user is denied due to location restrictions, and this same logic can be used to show messaging around location restrictions, exactly as is done for media.

- [x] Use auth service from #1067 (IIIF probe service)
~~Adjust the viewers (each the PDF viewer) to add target tags to each file that needs to have auth checked.
We need to have the equivalent of the media_tag_controller for files, extracting just the parts that iterate through the existing target tagged files and running auth checks to the new stacks endpoint for each.  It’s possible that most of the media_tag_controller can be generalized, with only the media specific methods (e.g. having to do with media player and thumbnails) left in the media_tag_controller.~~
~~Generalize the auth_restriction_controller … could be as simple as moving out of the media namespace and updating references.~~
~~Add hidden divs with the relevant to the other sul-embed viewers (e.g. pulled from https://github.com/sul-dlss/sul-embed/blob/main/app/components/embed/media_with_companion_windows_component.html.erb#L17-L50).  This could probably be generalized into a new view component to avoid duplication.  Update references to new javascript controllers that are generalized.~~

**Comment by dbranchini** [comment]
Related #1939 .

**Comment by lwrubel** [comment]
See https://github.com/sul-dlss/sul-embed/issues/1757 for additional info.
