### ISSUE TITLE
Access banner button style

### ISSUE THREAD

**Issue by alundgard** [sul-dlss/sul-embed#1929]
- Add `cursor: pointer;` to the `LOG IN` and `X` button hover.

- Add padding around the `X` button.

![Image](https://github.com/sul-dlss/sul-embed/assets/2343316/419d3c1f-347d-4945-89c0-97b6e289a3ec)

Example: https://sul-purl-uat.stanford.edu/bb034wm3873

**Comment by aaron-collier** [comment]
Closed by https://github.com/sul-dlss/sul-embed/pull/1922
