### ISSUE TITLE
Sidebar tab headers should be fixed on scroll

### ISSUE THREAD

**Issue by alundgard** [sul-dlss/sul-embed#1932]
### Expected behavior

Sidebar tab headers are fixed on scroll. Cf. Mirador: https://purl.stanford.edu/bb627py6670.

https://github.com/sul-dlss/sul-embed/assets/2343316/32aa700a-5478-45f8-9895-a3d63b6671ef

### Current behavior

Scrolling the sidebar tabs also scrolls the header.

https://github.com/sul-dlss/sul-embed/assets/2343316/3f46ae2a-228a-47ec-b1c5-84452cfd7332

NB: When selectable options appear below a tab header (eg: Autoscroll the transcript #1804 ), these options should also be fixed on scroll.

**Comment by mjgiarlo** [comment]
@jcoyne I see you have commits related to this issue. Is there a PR in the works?

**Comment by jcoyne** [comment]
Sorry. I thought the PR was made already. I'll check that
