### ISSUE TITLE
Improve UX for Stanford no-download PDFs (i.e., provide some kind of message saying the document isn't viewable)

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/sul-embed#1939]
These are the two sample Purls I'm using in stage, but this issue is mainly about the Stanford no-download one:

- [Stanford-only](https://sul-purl-stage.stanford.edu/xj550hm9593) 
  - we would like this to work with some kind of auth flow, which I think is ticketed elsewhere
- [Stanford-only but no download](https://sul-purl-stage.stanford.edu/gd142xn9905) 
  - we know this won't work and would like that to be more up front about that, rather then sending people through auth only to tell them they can't get the file anyway
  - (as an aside) in general, we should have an indication that a "no-download" PDF won't work

**Suboptimal scenario 1:**

When viewing the Stanford no-download purl in a firefox private window earlier today, I got prompted to auth within the embed viewer itself. I took this screenshot after going through Duo but before clicking through to the next "page":

> <img width="1236" alt="Screenshot 2023-12-07 at 8 40 44 AM" src="https://github.com/sul-dlss/sul-embed/assets/8975583/e2c65b87-f722-4f4f-814f-40037b72b25f">

I was then shown a Firefox error message:

> <img width="1236" alt="Screenshot 2023-12-07 at 8 41 00 AM" src="https://github.com/sul-dlss/sul-embed/assets/8975583/77b07d52-63a9-4570-a71e-73cf2ec4c27e">

Finally, I clicked on the blue "open site in new window" and got a page that said "Access forbidden."

**Suboptimal scenario 2**

When already logged in as a Stanford user, I get a message telling me I should download the file:

> <img width="1236" alt="Screenshot 2023-12-07 at 8 44 13 AM" src="https://github.com/sul-dlss/sul-embed/assets/8975583/3fb09ed3-7f02-418f-aa32-8a906563cb33">

The problem of course is that the file is no-download, so that will never work.

**What is to be done?**

Ideally, people would not accession PDFs with no-download rights (world or Stanford) and we wouldn't encounter this issue. But we do have some content with such rights and we should show a message that at least doesn't imply the content is downloadable, only to deny the access when they run out of links to click on.

I believe there's a design for an access restriction banner that says "There was an issue viewing this item" and directs people to look at the Access conditions to see if there's any more information. There's a chance that there won't be helpful information in the Access conditions, but that's where there could be information about restrictions. We could alternatively ask people to contact purl-feedback for help. If we don't go with a banner we could at least put a message in the viewer box.

**What happens currently**

In prod, we show an error in this situation. It's not ideal but better than going down an authentication path that ends in disappointment.

https://docs.google.com/document/d/1IIPYw4CVIaNCjPjtY427JxcPQngd5ZxgqhQLfhxVbi4/edit#heading=h.fuuyr6c6x300

**Comment by dbranchini** [comment]
Reviewed PDF access conditions - all variations, including Stanford-only view, no download (this ticket) and captured scenarios plus proposed messaging here - https://docs.google.com/document/d/1IIPYw4CVIaNCjPjtY427JxcPQngd5ZxgqhQLfhxVbi4/edit?usp=sharing.

**Comment by lwrubel** [comment]
File-level access rights of download=none for first PDF determines whether messaging is required.

**Comment by dbranchini** [comment]
It’s possible to mix and match many different variations of rights (Stanford-only, citation-only, embargo, location restrictions for view and/or download) during accessioning - essentially, almost any combination is possible. However, on the access side, meaning PURL, SW, or another site where a user is accessing a PDF, **there are currently limitations that force the download rights to outweigh the view rights**. In order to view a PDF, the PDF is technically downloaded first. **Therefore, if a PDF is set to Stanford-only view, but no download, then the PDF becomes unavailable for view and download.** In this circumstance, the following messaging should be displayed:

This item cannot be accessed online. See Access conditions for more information.
