### ISSUE TITLE
Broken image when viewing player in Chrome

### ISSUE THREAD

**Issue by dinahhandel** [sul-dlss/sul-embed#1949]
### Expected behavior
I should see a thumbnail image for the media in the player prior to pressing play for this video: https://purl.stanford.edu/qf378nj5000.

### Actual behavior
![Screenshot 2023-12-11 at 9 58 59 AM](https://github.com/sul-dlss/sul-embed/assets/9371978/e5f3e03c-1d00-47bd-aedd-431099e2e806)

### Browser / Environment
Chrome Version 120.0.6099.71 (Official Build) (x86_64)

**Comment by jcoyne** [comment]
This is due to a request for a tile size larger than the original image.  This is prohibited by the image server.  Fix in stacks?

**Comment by hudajkhan** [comment]
Makes sense to do that there.  Created an issue there: https://github.com/sul-dlss/stacks/issues/1082 .  Haven't added that to the project board but can, otherwise this issue will suffice and I will update this one when done.

**Comment by mjgiarlo** [comment]
Added to project board 🕺

**Comment by hudajkhan** [comment]
Closed by https://github.com/sul-dlss/stacks/pull/1083

**Comment by mjgiarlo** [comment]
Not deployed to prod but this work has otherwise been done.
