### ISSUE TITLE
Deactivate autoscroll upon browser search match

### ISSUE THREAD

**Issue by alundgard** [sul-dlss/sul-embed#1956]
Related to #1804 and #1807.
This issue describes the desired behavior. It may not be technically feasible.
Possibly helpful: [Selection API](https://developer.mozilla.org/en-US/docs/Web/API/Selection_API).

### Desired behavior

✅ = Already done
🛠️ = To be done

**When autoscroll is active** and the user executes transcript search via the browser's default (ctrl+F).

If there is a search match:
- jump the transcript scroll position to the corresponding segment, and highlight the matching string. ✅
- automatically deactivate the autoscroll [box unchecked]. 🛠️
- the current video playback position is unaffected. ✅

If there is no search match:
- the current transcript scroll position is unaffected. ✅
- autoscroll remains active [box checked]. ✅
- the current video playback position is unaffected. ✅

**When autoscroll is inactive** and the user executes transcript search via the browser's default (ctrl+F).

If there is a search match:
- jump the transcript scroll position to the corresponding segment, and highlight the matching string. ✅
- the current video playback position is unaffected. ✅

If there is no search match:
- the current transcript scroll position is unaffected. ✅
- the current video playback position is unaffected. ✅

### Current behavior

Autoscroll and browser search are in tension. Autoscroll automatically moves the transcript scroll position to the current video playback position, while browser search jumps the scroll position to a matching string.

**Comment by jcoyne** [comment]
I took a look at the `selectstart` event. But It doesn't look like that fires when searching.

**Comment by alundgard** [comment]
After more investigation, the desired behavior doesn't seem technically feasible. To mitigate the conflict between autoscrolling and searching, we are deactivating autoscroll by default (#1998), and leaving it to the user to avoid doing both at the same time.
