### ISSUE TITLE
Access restriction banners are repeating "reading room"

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/sul-embed#1964]
### Expected behavior
The Access condition banners should name the reading room where location-restricted materials can be accessed. The banner should not repeat the phrase "reading room".

### Actual behavior
The banners are repeating "reading room" at the end of the reading room names:
https://searchworks.stanford.edu/view/br901zk2113
<img width="825" alt="Screenshot 2023-12-11 at 10 06 26 PM" src="https://github.com/sul-dlss/sul-embed/assets/8975583/c46ac22b-b67b-4803-8fb3-a841fd396d6a">
https://purl.stanford.edu/bb099mt5053
<img width="825" alt="Screenshot 2023-12-11 at 10 05 39 PM" src="https://github.com/sul-dlss/sul-embed/assets/8975583/68515c26-4acb-4dec-828d-d0b5f7459713">

I don't remember seeing this on stage but could have missed it. It looks like "reading room" is being appended to a message that would be complete by itself. For example,
>Access is restricted to the Archive of Recorded Sound listening room. See Access conditions for more information.
would be fine and I think that's what I saw in testing.

### Steps to reproduce the behavior
See location restricted media items, such as:
- https://searchworks.stanford.edu/view/br901zk2113 (ARS)
- https://purl.stanford.edu/bb099mt5053 (Spec)

**Comment by jcoyne** [comment]
@andrewjbtw some of the labels have "reading room" and some do not: 

https://github.com/sul-dlss/stacks/blob/7a87e734d3736d47b6a42ed3fc9c500d617f4498/app/services/media_authentication_json.rb#L28-L33

If we need "reading room" on any of the rest of these, lets add this in stacks.
