### ISSUE TITLE
[sul-embed/prod] TypeError: status is undefined

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/sul-embed#2004]
## Backtrace

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/49295/faults/102962742)

When attempting to view https://purl.stanford.edu/cs860mp4252 which is a citation-only object

The auth check response (https://stacks.stanford.edu/media/cs860mp4252/cs860mp4252_sl.m4a/auth_check) is not returning a status

**Comment by mjgiarlo** [comment]
@jcoyne should this be closed by #2005?

**Comment by jcoyne** [comment]
yes
