### ISSUE TITLE
Embedded IIIF objects don't correctly detect the DRUID for metrics tracking

### ISSUE THREAD

**Issue by thatbudakguy** [sul-dlss/sul-embed#2011]
Database queries reveal that we seem to be tracking an awful lot of views of things called "manifest" and "manifest.json":
```rb
> Ahoy::Event.where_event("$view").group_prop(:druid).order('count_id desc').limit(10).count('id')
 => {"manifest.json"=>1955, ... "manifest"=>467, ... }
```

Many of these are coming from parker.stanford.edu, where the iframe embed URL for sul-embed looks like:
`https://embed.stanford.edu/iiif?canvas_id=&image_tools=true&url=https%3A%2F%2Fdms-data.stanford.edu%2Fdata%2Fmanifests%2FParker%2Fwz026zp2442%2Fmanifest.json`

We probably need to improve the logic that extracts the DRUID from the embed URL.

**Comment by jcoyne** [comment]
Are we going to count views by IIIF viewers that are not hosted by embed?

**Comment by thatbudakguy** [comment]
Do you mean counting requests for IIIF manifests as a view, since we assume the manifest is being used to embed the object and view it (even if not via our embed viewer)?
