### ISSUE TITLE
New PDF Viewer should show list of files for rendering

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/sul-embed#2079]
Now that we've changed the PDF controller to use the CompanionWindowComponent in #2075, the new PDF viwer no longer shows the list of PDFs available for download, which is important to show when there is more than one PDF available, since only the first PDF is shown in the viewer.

We need to update the left side panel that currently just says "Media Content" to show the list of PDFs available for rendering.  Click a file, and it updates the PDF shown in the main panel.

![Screen Shot 2024-01-10 at 10 49 34 AM](https://github.com/sul-dlss/sul-embed/assets/47137/0606345e-9e91-4df7-ac56-cb401c5aac46)
.

**Comment by jcoyne** [comment]
@peetucket downloads are in the popup that opens from the share button:
<img width="238" alt="Screenshot 2024-01-10 at 1 25 00 PM" src="https://github.com/sul-dlss/sul-embed/assets/92044/9d782e1d-e23d-42eb-ab9f-2976d548c9d5">

**Comment by peetucket** [comment]
That downloads the current viewable PDF (i.e. the first one), but there can be objects with multiple files, and you can't get to the others, e.g.https://purl.stanford.edu/ds777pr3860

Also, the heading is currently hardcoded as "Media Contents" and is totally blank for PDF objects.  Andrew noticed this too.

I'm working on trying to make that contents panel more flexible so that each content type can determine what goes there (including the name of the heading).

**Comment by peetucket** [comment]
Oh, i take that back...didn't realize the share button showed all files. ok
