### ISSUE TITLE
Smaller side panels in companion window shouldn't shrink the main content

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/sul-embed#2086]
When you click on the left sidebar, and view a panel which is shorter in height (because there is less content), it shrinks the overall height of the entire sul-embed panel, which has the effect of shrinking the main content as well.  It should retain the full height of the main panel instead.

For example, here is what a PDF looks like when the page loads:

<img width="864" alt="Screen Shot 2024-01-12 at 1 52 24 PM" src="https://github.com/sul-dlss/sul-embed/assets/47137/0a502e10-fd15-4131-b465-ff8322906054">

Here is what it looks like when you click the left drawer and select the small content list:

<img width="922" alt="Screen Shot 2024-01-12 at 1 53 26 PM" src="https://github.com/sul-dlss/sul-embed/assets/47137/56e6eb10-1702-4f7d-b342-ce64ec6276b1">

**Comment by jcoyne** [comment]
@peetucket I don't think we see this in the media player.

**Comment by peetucket** [comment]
Thanks.  I already tried adding the equivalent 
```
.sul-embed-pdf {
  height: 100%;
  width: 100%;
}
```

which didn't change anything.  It looks like a height:100% is already applied for that panel from a superceding style.  The media player panel does seem to shrink down too, but I guess to not less than the size of the content, so it's ok.  Perhaps the browser treats the <object> tag we are using for PDF differently in what it considers to be "100% height".

**Comment by peetucket** [comment]
Specifying a min-height like this forces the main panel to retain some height even if the side panels shrink.  So one possible solution:

```
.sul-embed-pdf {
  min-height: 700px;
}
```
