### ISSUE TITLE
Inconsistent and problematic display of contents list, depending on browser

### ISSUE THREAD

**Issue by saseestone** [sul-dlss/sul-embed#2105]
### Actual behavior
Tamar Barzel reported seeing description text overlaid onto one another, and sometimes also on the 'note' icon when viewing this SearchWorks record: https://searchworks.stanford.edu/view/6347119. She was using Chrome on a MAC.

Looking at the same record, Cory saw additional issues with text and icons overlapping when viewing the record in Firefox on a MAC.

### Steps to reproduce the behavior
Open https://searchworks.stanford.edu/view/6347119 and click the hamburger menu to open the Contents sidebar. Then open the Media list and view the contents list.  

### Browser / Environment
Tamar reported she was on a mac, using Chrome. I've asked her to verify the version number and provide a screenshot. I'll attach them when I hear back.

@corylown will also add screenshots of his Firefox view. 

The original report came through SearchWorks feedback. Here's a like to the JIRA ticket: https://jirasul.stanford.edu/jira/browse/SW-4289

**Comment by saseestone** [comment]
Noting that my display (Chrome Version 121.0.6167.160 (Official Build) (arm64)) looks ok - although there seems to be a light dotted line present for the images.

<img width="414" alt="image" src="https://github.com/sul-dlss/sul-embed/assets/14897546/81abdaae-a9b3-4ebf-af72-e2c531b9e97b">

**Comment by corylown** [comment]
From Firefox 122.0.1 (64-bit) Mac

<img width="1130" alt="pq271rp1793" src="https://github.com/sul-dlss/sul-embed/assets/458247/4d0a9481-d2ad-4884-a388-879e12a0add6">

**Comment by andrewjbtw** [comment]
I'm also on Firefox 122.0.1 on a Mac
<img width="1063" alt="Screenshot 2024-02-07 at 3 20 25 PM" src="https://github.com/sul-dlss/sul-embed/assets/8975583/1b6f5f43-cd7d-4db6-a9e2-9732125523de">

**Comment by jcoyne** [comment]
I see the same as Andrew, no issues on 122.0.1 on Mac.

**Comment by saseestone** [comment]
We received a PURL feedback submission ([PURL-1322](https://jirasul.stanford.edu/jira/browse/PURL-1322)) from Kevin Kishimoto at the Music Library about this record: https://searchworks.stanford.edu/view/wh837xk3994

It's a very similar issue, only even more problematic because of the appearance of the Stanford S. Here's a screenshot in my view (Chrome Version 122.0.6261.129 on Mac)

<img width="425" alt="image" src="https://github.com/sul-dlss/sul-embed/assets/14897546/4967d877-60da-4858-b5f4-028a72f5ad95">

**Comment by jcoyne** [comment]
@saseestone that looks like a different issue to me.  This latest issue you show only happens when there are three lines of text.  The image icon is not displaced as it was in @corylown's screenshots.

**Comment by saseestone** [comment]
ah ok @jcoyne do you want a separate issue for this?

**Comment by jcoyne** [comment]
@saseestone I think that will be best, or we may miss something. I also think we need @dbranchini  to weigh in on a design for a long file label.

**Comment by andrewjbtw** [comment]
We've received an additional report of the original issue via SW-feedback on this item: https://searchworks.stanford.edu/view/14599324

A faculty member would like to use this video in a class and noticed the issue.

I can't reproduce it myself but Jeannette was able to do so and took a screenshot:
> ![sul-embed-image001](https://github.com/sul-dlss/sul-embed/assets/8975583/9cba2446-9d83-44f6-9309-cfab3df24f66)

**Comment by corylown** [comment]
It looks like this is related to OS scrollbar settings. If the scrollbar always displays then the layout of the files list gets mangled. If the OS is set to only display scrollbars upon use then the layout is correct.

**Comment by corylown** [comment]
Possible solutions:

## Setting `--drawer-content-padding: 0.5rem` (currently `1rem`)
Screenshots showing impact with scrollbars set to display when used

POSSIBLE FIX `--drawer-content-padding: 0.5rem`
<img src="https://github.com/sul-dlss/sul-embed/assets/458247/086d3787-89d9-4c4b-a42f-e3246f52a60f" alt="drawing" width="300"/>

POSSIBLE FIX `--drawer-content-padding: 0.7`
<img src="https://github.com/sul-dlss/sul-embed/assets/458247/d4ef3035-b3b3-4b87-aea6-f0bd7128459f" alt="drawing" width="300"/>

CURRENT SETTING `--drawer-content-padding: 1rem`
<img src="https://github.com/sul-dlss/sul-embed/assets/458247/4e64d0d2-0025-4397-8b67-e587aac086d9" alt="drawing" width="300"/>



## Setting `--drawer-width: 316px` (currently `305px`)
Screenshots showing impact with scrollbars set to display when used

POSSIBLE FIX `--drawer-width: 316px`
<img src="https://github.com/sul-dlss/sul-embed/assets/458247/093ce33f-9dc2-4829-b58d-8df7ec3a7789" alt="drawing" width="300"/>

CURRENT SETTING `--drawer-width: 305px`
<img src="https://github.com/sul-dlss/sul-embed/assets/458247/a4300825-514d-418b-a0e0-35ee915db7b8" alt="drawing" width="300"/>
