### ISSUE TITLE
title field in media player appears to be concatenated with other metadata 

### ISSUE THREAD

**Issue by dinahhandel** [sul-dlss/sul-embed#2120]
### Expected behavior
The title bar in the media player should only display the main/primary title, not any other titles. 

### Actual behavior
It appears that the title is being concatenated with other metadata fields, in the example provided it looks like part of the uniform title.

### Steps to reproduce the behavior
See https://purl.stanford.edu/cy499mh7552.

### Browser / Environment
Chrome Version 122.0.6261.69 (Official Build) (x86_64)

**Comment by jcoyne** [comment]
It's displaying what it finds in the IIIF manifest.

It looks like this item has two titles.
<img width="347" alt="Screenshot 2024-03-05 at 2 54 12 PM" src="https://github.com/sul-dlss/sul-embed/assets/92044/8de078cb-13c0-4890-9278-2189cbe58383">

**Comment by andrewjbtw** [comment]
I wonder if there's a problem with the data? There's both a title value and a structuredTitle value. The first is the "primary" title and the second is the "main title" - it seems like that's a conflict.

**Comment by andrewjbtw** [comment]
I checked with Arcadia and this is valid metadata:
> the "primary" title is the overall preferred title for the object, and the main title is part of a structured title that may be accompanied by subtitle or a part number.

**Comment by andrewjbtw** [comment]
This should now be fixed: sul-embed is now reading the title from a different field (the Cocina object "label"), which only includes the primary title. The example in the ticket description now shows only "Genesis VI" https://purl.stanford.edu/cy499mh7552

**Comment by dnoneill** [comment]
@andrewjbtw Can we close this? It looks like it is rendering correctly now?

**Comment by andrewjbtw** [comment]
Yes, I thought I'd closed it. The fix came in indirectly as part of versioning WC work.
