### ISSUE TITLE
Items should be visible in embed even if their parent collection is "dark'

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/sul-embed#2154]
### Expected behavior

An item should be visible in embed if the rights are set to enable a purl. This should not depend on the rights status of the parent collection object.

### Actual behavior

When an item is in a collection where the collection object is set to "dark", the item Purl renders but the viewer just shows a 404 for the collection druid:

<img width="1229" alt="Screenshot 2024-05-28 at 12 35 46 PM" src="https://github.com/sul-dlss/sul-embed/assets/8975583/4f8dc9d2-a9ef-4e1f-b5e5-ef7c83b7d560">

### Steps to reproduce the behavior

See this test item in prod: https://purl.stanford.edu/ct931nf5570

### Additional information

I think this issue may have started when we switched to read from public JSON instead of public XML.

**Comment by jcoyne** [comment]
@andrewjbtw this page is loading correctly for me: https://purl.stanford.edu/ct931nf5570

<img width="1080" alt="Screenshot 2024-05-28 at 2 51 17 PM" src="https://github.com/sul-dlss/sul-embed/assets/92044/1d46322b-7efb-48f9-8e1d-f8cf29a3e78b">

**Comment by andrewjbtw** [comment]
That started working for me too. What about this item? https://purl.stanford.edu/py886rf8253
