### ISSUE TITLE
(new pdf viewer) Odd behavior when loading multiple PDFs in the browser PDF viewer

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/sul-embed#2158]
### Expected behavior

The browser-based PDF viewer (enabled on stage and QA) is capable of displaying more than one PDF. Users can switch between PDFs by navigating in the left companion window:

<img width="645" alt="Screenshot 2024-05-29 at 4 21 08 PM" src="https://github.com/sul-dlss/sul-embed/assets/8975583/4a78597c-3e0a-4a5a-841b-53939e1205f0">

The expected behavior is that the browser loads the first PDF listed in the metadata.

### Actual behavior

I've found it's unpredictable which PDF will load when there's multiple PDFs. Sometimes it's the first one, sometimes it's one later on the list. I've reloaded the same purl in the same browser and seen the browser switch between PDFs upon reload.

### Steps to reproduce the behavior

Two examples in stage:

- Purl with two pdfs: https://sul-purl-stage.stanford.edu/bg077wm0255
- Purl with six pdfs: https://sul-purl-stage.stanford.edu/kp686sg8638

1. Load those purls and check if the first PDF on the list was the PDF to render
2. Load the purls in different browsers and see if the browsers load the same file first
3. Do a hard refresh and see if the same file is loaded each time. Try 4-5 refreshes, not just one.

### Browser / Environment

I've checked with firefox and chrome and both exhibit the odd behavior of not always loading the first PDF on the list.

**Comment by dnoneill** [comment]
@andrewjbtw The fix for this issue is on stage for your review.
