### ISSUE TITLE
Add various title text around embed

### ISSUE THREAD

**Issue by jkeck** [sul-dlss/sul-embed#216]

**Comment by mejackreed** [comment]
Can this be described a bit more?

**Comment by jkeck** [comment]
I'm guessing I meant `alt` attributes (since it's assigned to @jvine I assume for accessibility reasons).

**Comment by jvine** [comment]
= #242?

**Comment by mejackreed** [comment]
I don't know.. anything else besides that?

**Comment by jvine** [comment]
does #242 include the thumbs in the multi-image embed? Basically all thumbs everywhere need to be covered. other than that, i don't know what this might be referring to.

**Comment by mejackreed** [comment]
#242 only deals with file viewer... image viewer will be worked on as we implement the new one.
