### ISSUE TITLE
(new pdf viewer) Clearly indicate which PDF is selected when there are multiple PDFs

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/sul-embed#2161]
The left companion window should indicate which document has been selected when there are multiple PDFs. Currently, you can't tell which PDF you are viewing.

<img width="1333" alt="Screenshot 2024-06-03 at 10 12 00 AM" src="https://github.com/sul-dlss/sul-embed/assets/8975583/b763bc99-c98b-49d6-9788-ede3f99be2a0">

**Comment by alundgard** [comment]
Quick design mockup. Similar to the Media viewer, we can indicate the selected PDF with a `box-shadow`. Does this look OK @andrewjbtw ?

## Media viewer (current)
<image src="https://github.com/sul-dlss/sul-embed/assets/2343316/b7de83f4-8e61-4371-9576-f5c810311032" width=600>

https://purl.stanford.edu/br525sp8033

## PDF viewer (mockup)
<image src="https://github.com/sul-dlss/sul-embed/assets/2343316/415f49e8-e03d-4ead-9de8-c5d91b79dd94" width=600>

https://sul-purl-stage.stanford.edu/xr437fg8293

**Comment by andrewjbtw** [comment]
Thanks, @alundgard! The design looks good to me.

**Comment by dnoneill** [comment]
Updated in PR.
