### ISSUE TITLE
Center thumb in embed viewer

### ISSUE THREAD

**Issue by snydman** [sul-dlss/sul-embed#218]
For items where only a 400px thumb can be displayed within embed viewer, should we center the thumb in the embed view, as opposed to pinning it to the top of the viewer? 

![image](https://cloud.githubusercontent.com/assets/3279382/5383256/b1694e08-8064-11e4-9da6-8074e528accd.png)

@jvine @jchristo4

**Comment by mejackreed** [comment]
I'm not sure if this is fully addressed yet, is it?

**Comment by aeschylus** [comment]
Ah, yes. This is auth related, but I thought it was layout related.

**Comment by mejackreed** [comment]
Resolved as we are now using UV
