### ISSUE TITLE
Disable right-click functionality by default

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/sul-embed#232]
Users should not be able to easily right-click to save an image, since the rights in some cases do not allow this behavior.  Since the entire player requires javascript to function, I believe this can be done via javascript in the iframe:

document.oncontextmenu = function() { 
    return false; 
};

This should not be an optional, otherwise users could embed objects in the own page and request the right-click menu to be enabled.  Alternatively, you could check the rights of the object to decide if right-click should be enabled (download=false disables right-click automatically).

**Comment by mejackreed** [comment]
I would disagree that disabling default browser behavior should be default or even an option for sul-embed's image viewer. Disabling right click will not disallow an image download for a knowledgable user and the consequences of this for our users and consumers are greater.

One consuming the oEmbed service can easily disable right click functionality using:

```javascript
$('body').on('contextmenu', '.openseadragon-container', function(){return false;});
```

**Comment by peetucket** [comment]
Agreed it is not full-proof, and knowledgeable users can take a screenshot or override the JS, but here is the logic:  Revs content is not supposed to be downloadable at greater than 400 pixels (except Stanford people).  The current player, even when in zoom view, uses tiles, so a right-click save as gives you a tile only.  This inability to easily get high resolution content is a key part of our agreement with them to host their content.  The new player makes it trivial to right-click save-as a very high resolution image without resorting to screen-shots.  This would be unacceptable per our agreement with them.  

As a consumer of oembed, we could of course disable it on just the Revs Digital Library website, as you noted above, but it would still be possible on the Revs PURL pages, which are linked to on each Revs page.  It would also continue to make it fairly simple for anyone to embed an object in their own website and then grab the content (though this requires more sophistication).  

Are their other options we can consider to address this content protection issue?

**Comment by mejackreed** [comment]
I believe OpenSeaDragon uses canvas for performance reasons which give the easy to download image on right-click. Maybe @jchristo4 knows if there is a way to not use canvas in OSD?

**Comment by mejackreed** [comment]
Closing this, outside the scope of embed project. We will look into other ways to address content saving. @aeschylus has some ideas on how to do this.
