### ISSUE TITLE
Optional paramater to show javascript alert on right-click

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/sul-embed#233]
Applications using the iframe embed code may want to show users a message when they right-click, instead of just disabling the functionality altogether.  For example, the Revs Digital Library website may want to show a copyright notice on right-click.  It would be useful to be able to pass this as a parameter.

**Comment by mejackreed** [comment]
I'm thinking this is also outside the scope of the project. Will look to @aeschylus to implement saving image restriction idea

**Comment by peetucket** [comment]
If there is any way we can implement on the client side, that would be fine too.  But any basic image saving restriction or copyright notices will be mandatory for us to use sul-embed with the Revs Digital Library -- or else we will be stuck with the old player.  I imagine there will be other projects in the future with similar restrictions.

**Comment by mejackreed** [comment]
Sounds good... lets track this here: https://github.com/sul-dlss/sul-embed/issues/244

**Comment by jkeck** [comment]
@peetucket are the copyright restrictions not present in the metadata (e.g. Use and Reproduction notes)?

**Comment by peetucket** [comment]
They are.  So we can display whatever text is in there.  The issue is that we need to make it  more challenging to get a high-res image when in zoom view.  Currently you can do this by going full-screen, zooming correctly and then taking a screen shot.  With the new image viewer, you don't even need to do a screenshot...go to full screeen in zoom view and then right-click to save the resulting high-res image.  Since the right-click (or drag) to save is a well known way to get images, we wanted to make it harder to do it as a deterrent (screenshot will never be preventable of course).  Showing a message on right-click is another way to show our content owners we are trying to deter theft.

**Comment by jkeck** [comment]
Totally understand about the right-click to save concern you describe.

WRT the copyright notice, we already pull in the use and reproduction note (as well as license if present) from the object into the popup metadata panel, so that is already handled.

**Comment by peetucket** [comment]
Cool about copyright notice/license included, thanks.
