### ISSUE TITLE
Viewing problem for McLaughlin Map druid:fq505jv7833 in SW

### ISSUE THREAD

**Issue by caaster** [sul-dlss/sul-embed#235]
From: "Stuart Snydman" snydman@stanford.edu
To: "Catherine A. Aster" caster@stanford.edu
Cc: "G. Salim Mohammed" gsalim@stanford.edu, "Michael G Olson" mgolson@stanford.edu
Sent: Sunday, March 8, 2015 9:53:52 PM
Subject: Re: viewing sample - searchworks
This actually looks strange to me, and not quite right. Thanks for reporting. I've forwarded it on to the engineering team and they are investigating.  For reference, is there a ticket for this?  If not may I request that you make one at https://github.com/sul-dlss/sul-embed/issues ?
Thanks,
-Stu

On Mar 4, 2015, at 10:22 AM, Catherine A. Aster wrote:

```
Hi Salim,
For very large map images, the tiled image viewers in use these days take a long time to fully load the image. So, the image that first pops up will appear pixelated, because the higher resolution tiles are loading in the background. After a long enough period of time, you would in fact see a non-pixelated view. Alternatively, you can click on the "+" and if the higher resolution tiles have loaded for that magnification, you will see them clearly. I was looking at the sample you provided, McLaughlin Map druid:fq505jv7833.
Stu may be able to weigh in here with additional explanation, so I've cc'd him on my reply.
Best,
Cathy
From: "G. Salim Mohammed" <gsalim@stanford.edu>
To: "Catherine A. Aster" <caster@stanford.edu>
Cc: "Michael G Olson" <mgolson@stanford.edu>
Sent: Friday, February 27, 2015 4:23:36 PM
Subject: viewing sample - searchworks
Cathy,
Attached is a sample of the view we are seeing in SearchWorks (this is what I meant when I said yesterday that the picture embed viewer is pixelated).
Best, Salim
G. Salim Mohammed, Digital and Rare Maps Librarian
gsalim@stanford.edu | 650.723.5100
http://library.stanford.edu/people/gsalim
Branner Earth Sciences Library & Map Collections
Stanford University | 397 Panama Mall; MC 2211
Stanford, CA 94305  
"Live simply so others can simply live." -Gandhi.
```

![mclaughlinmap_fq505jv7833_searchworksviewingsample](https://cloud.githubusercontent.com/assets/3210225/6559734/28a2d93a-c642-11e4-84fb-ac90c2749062.JPG)

**Comment by cbeer** [comment]
http://searchworks.stanford.edu/view/fq505jv7833

**Comment by mejackreed** [comment]
This seems to be resolved now in m3
