### ISSUE TITLE
Improperly scoped javascript in common viewer

### ISSUE THREAD

**Issue by jkeck** [sul-dlss/sul-embed#236]
See https://github.com/sul-dlss/spotlight/issues/1150#issuecomment-101060486

https://github.com/sul-dlss/sul-embed/blob/master/app/assets/javascripts/modules/common_viewer_behavior.js#L30 acts on the first instance of the embed on the page and will not allow multiple embeds to exist on the same page.

**Comment by mejackreed** [comment]
Yep this will need to be part of a larger refactor effort to enable multiple embeds within the same page.

A lot of todos here, including:

 - Id's used in elements will need to be unique (druid prefix/suffix?)
 - js selections should not be global but within the context of the element
 - css injection should check if css is already in page before injecting again
