### ISSUE TITLE
Handle restricted images properly in OSD

### ISSUE THREAD

**Issue by mejackreed** [sul-dlss/sul-embed#244]
Handle zoom only images

per @aeschylus experience with canvas

**Comment by peetucket** [comment]
:+1:

**Comment by aeschylus** [comment]
There are several ways this can be done. The enterprising hacker might have been able to get around them, but thankfully there is a bug in openSeadragon (maybe, there might be some proper CORS setting to not let this happen, but if it's [not a bug](https://github.com/openseadragon/openseadragon/issues/671), it's very hard not to reproduce). This bug makes sure the canvas is "[tainted](https://developer.mozilla.org/en-US/docs/Web/HTML/CORS_enabled_image)". This means that javascript cannot read the canvas data once it is written. That means no programmatic re-assembly.
 
<img width="1436" alt="screen shot 2015-08-13 at 16 43 12" src="https://cloud.githubusercontent.com/assets/145874/9264369/7a0f4c72-41da-11e5-97b8-d44d09dfe7cc.png">

Another approach that can be taken is a content script that intercepts image requests as they come in. They could later be re-assembled. The person would have to be somewhat advanced to do this, but if IIIF ever gets very prevalent, a browser extension will be written by someone to do it with little or no knowledge. A way to prevent request interception is described in this [stackOverflow post](http://stackoverflow.com/questions/20973528/canvas-disable-image-download). It involves scrambling the image response and providing an encrypted tile map that allows the image to be re-assembled in memory before being written to the canvas. This would obviously pose problems for the API conformance, and would require openSeadragon to be modified in a significant way. 

Probably the most common way images would be endangered is by someone simply right clicking and saving the image. This works even if the canvas is "tainted". However, it is very easy to disable. You simply [invalidate the contextmenu event](http://stackoverflow.com/a/10864321/564684). One drawback of this is that it's fairly easy to discover and undo using the browser's developer tools, for someone who knows how. However, it is less protocol specific, and would therefore be less likely to ever have a browser extension written for it.

Really, as I'm sure all the engineers know and the stakeholders don't want to believe, it is a contradiction in terms to send something to the browser and assume you have any control over what is done with it. To be sure of the outcome, it's _either_ zooming _or_ protection (using real Auth, as Rob points out. It seems people only want turing machines for themselves, and "turing machines -1" for everyone else.

A server side partial solution would log the IP (or user account id, if there is one) of every request, and [steganographically](https://en.wikipedia.org/wiki/Steganography) watermark each response, storing the watermark key and IP value pair permanently. This would not prevent downloading completely, but it would tell you exactly who downloaded the image being distributed (though it may have been stolen from that person. Thankfully U.S. Law does not yet equate an IP address with a person).

**Comment by mejackreed** [comment]
Resolved as we are now using UV
