### ISSUE TITLE
Implement standalone layout generation code

### ISSUE THREAD

**Issue by aeschylus** [sul-dlss/sul-embed#252]

**Comment by aeschylus** [comment]
That is, write a big but easy to understand function that just calculates the x and y coordinates, width and height of the canvases in a way that will apply for _both_ openseadragon's "world" and the browser's window.

**Comment by aeschylus** [comment]
Compare [describing UI state with data](http://nicolashery.com/describing-ui-state-with-data/) to [immediate mode GUIs](http://gamedev.stackexchange.com/questions/24103/immediate-gui-yae-or-nay).

**Comment by mejackreed** [comment]
Happening here: https://github.com/aeschylus/iiifManifestLayouts
