### ISSUE TITLE
Stub out new image viewer in Ruby

### ISSUE THREAD

**Issue by mejackreed** [sul-dlss/sul-embed#290]
- New image viewer should register itself for `:image, :manuscript, :map, :book`
 - Should provide the manifest.json url as a data attribute
 - ~~Should also have the label~~ See https://github.com/sul-dlss/sul-embed/commit/c1f63a94408b6f91100e875dfa132c8b79de4b5d#commitcomment-12183814
 - Should also have top controls (two-page, single-page, gallery, fullscreen) placeholders

http://purl.stanford.edu/fw090jw3474/iiif/manifest.json

**Comment by aeschylus** [comment]
just add `iiif/manifest.json` to existing purl to construct manifest.json data attribute.
