### ISSUE TITLE
Add bottom panel thumbnail preview using sly.js

### ISSUE THREAD

**Issue by aeschylus** [sul-dlss/sul-embed#292]
- [x] Get thumb images from the manifest.sequence[0].canvases[i].resource[0]... etc.
- [x] Load image thumbs into sly.js
- [x] Pre-calculate image containers/placeholders from _canvas_ height and width (manfiest.sequence[0].canvses[i].height...etc.)
- [x] Fill in placeholders with image requests as needed with lazy loading, using promises/onload events. See http://imagesloaded.desandro.com/ and mirador image placeholders:
https://github.com/IIIF/mirador/blob/master/js/src/widgets/thumbnailsView.js#L138-L145
https://github.com/IIIF/mirador/blob/master/js/src/widgets/thumbnailsView.js#L164-L175
https://github.com/IIIF/mirador/blob/master/js/src/utils/utils.js#L242-L260

**Comment by mejackreed** [comment]
@aeschylus here is an update where I'm at: https://github.com/sul-dlss/sul-embed/compare/thumb-preview?expand=1

Next thing to add is the lazy loading
