### ISSUE TITLE
Handle case where item is download-restricted to everyone

### ISSUE THREAD

**Issue by ggeisler** [sul-dlss/sul-embed#295]
It seems it is possible that an item can be download-restricted even to Stanford users. Discussing this with @jkeck it sounds like the current logic around displaying the download links only checks to see if the user is Stanford-affiliated when deciding what download links to display.

This logic might need to check the item's rights restrictions to ensure that the item is authorized for download before showing the download links. Currently when you click a download link for an item that doesn't allow even SU people to download you get a "Not authorized" message from the Stacks URL

![https___stacks_stanford_edu_image_rx795tx1655_00004472_small_action_download](https://cloud.githubusercontent.com/assets/101482/8663020/d4d2774c-297a-11e5-97f4-422e38f15c7f.png)

**Comment by mejackreed** [comment]
rx795tx1655

**Comment by ndushay** [comment]
How is this related to #481

**Comment by cbeer** [comment]
Seems fixed; e.g. https://purl.stanford.edu/bb165pk5093
