### ISSUE TITLE
Handle the case of an embargo'ed file

### ISSUE THREAD

**Issue by hannahfrost** [sul-dlss/sul-embed#302]
If a file is under embargo and is listed in the embed viewer, it should be clear to the user that file access is limited.

The item's public XML includes the embargo release date, so perhaps this data can be leveraged for the desired functionality.

**Comment by cbeer** [comment]
@hannahfrost off-hand, do you have an example druid?

**Comment by hannahfrost** [comment]
@cbeer Here's a handy one from sw-test: http://searchworks-test.stanford.edu/gdor/view/wn386gj5687

I can dig up a prod one if necessary.

**Comment by rosy1280** [comment]
Also, in the current version of PURL the order of the rights metadata changes the link behavior.  If your rights metadata looks like this:

```
<access type="read">
<machine>
<none/>
<embargoReleaseDate>2015-12-31T08:00:00Z</embargoReleaseDate>
</machine>
</access>
```

The current production PURL indicates that the file is restricted.  If you flip it to look like this:

```
<access type="read">
<machine>
<embargoReleaseDate>2015-12-31T08:00:00Z</embargoReleaseDate>
<none/>
</machine>
</access>
```

The link to the file appears and you get the forbidden message when you try to click on it.  If we could **NOT** recreate this bug, that would be great.

**Comment by mejackreed** [comment]
@hannahfrost @rosy1280  I'm working on implementing this feature, while other things are blocked. Can you please provide me with some other druids? Also are there such things as embargoed images (jp2's?)?

**Comment by mejackreed** [comment]
Support for embargo scenarios:

 - [ ] mg662qq6088 - access <none/> with embargo release date
 - [ ] km993dd6050 - access stanford with embargo release date
 - [ ] nd387jf5675 - no embargo

Feel free to add others if needed @rosy1280, @hannahfrost, @cbeer

**Comment by LynnMcRae** [comment]
I need to confirm that the bug Rosy mentions, also described in https://jirasul.stanford.edu/jira/browse/HYDRUS-302, was addressed (or never was a problem) in this implementation so I can close that ticket.

**Comment by hannahfrost** [comment]
@LynnMcRae I've tested and can confirm that the matter is resolved and we can close HYDRUS-302
