### ISSUE TITLE
Test PURLs for a variety content types and reading rules

### ISSUE THREAD

**Issue by snydman** [sul-dlss/sul-embed#303]
See: https://docs.google.com/spreadsheets/d/1T4MY5jIUqd4XAnPgwiuKItOTBcTT8oVGHIulRE_ldP8/edit#gid=0

@jkeck @cbeer @mejackreed @aalsum @aeschylus

**Comment by mejackreed** [comment]
Is there a reason that this list should be private? I would like to add the druids to GitHub tickets if possible.

**Comment by cbeer** [comment]
Hope not, I published them in https://github.com/sul-dlss/purl/blob/sw-design/app/views/purl/index.html.erb#L32-61
