### ISSUE TITLE
Handle "mixed-type" (?) object files

### ISSUE THREAD

**Issue by cbeer** [sul-dlss/sul-embed#310]
For some types of objects, e.g. http://purl.stanford.edu/dn665vh1697, there's a set of images (or a book viewer) and some associated object files. It would be really nice if PURL somehow exposed those object files (as a download?) to they are accessible in non-PURL contexts.

**Comment by mejackreed** [comment]
I think this is similar to #14 ? Can you confirm?

**Comment by cbeer** [comment]
I'm confused by #14 (or, I think #14 is confusing..), but @jvine's last comment sounds similar.

**Comment by mejackreed** [comment]
Yeah #14 is confusing. The case here is essentially a book (multi image object) with all of those images concatenated into a pdf file (as another file)

**Comment by cbeer** [comment]
Ok, yep, that's exactly the same problem (although it happens on other types of objects too).

**Comment by jvine** [comment]
I'm confused too - are we talking about:
a) an object with several images, with the option to download the complete set in a PDF, or
b) an object that includes both images and other things - with the example of an included PDF that happens to combine all the object's images.

**Comment by cbeer** [comment]
Here are two examples:

http://purl.stanford.edu/bh538xp9013
http://purl.stanford.edu/sf815vr1246

Note the "Available download formats" on the right side. I think those are showing up correctly for the file list view, but in e.g. the image viewer, those additional formats are not exposed at all.

**Comment by jvine** [comment]
Okay yeah - they should be exposed in the image viewer in the same way - as an additional download option.
