### ISSUE TITLE
Allow deep-linking into the embedded content

### ISSUE THREAD

**Issue by cbeer** [sul-dlss/sul-embed#313]
One feature in the PURL gallery experience is the ability to deep-link to a specific image within an object (although it's highly imperfect). The embed widget should be able to handle deep-linking (and provide some way to expose that back up to the embedding application, using e.g. replaceState?) too.

**Comment by mejackreed** [comment]
We've talked about this a bunch with @snydman, @jvine, @blalbrit , and Lynn. 

It starts to get complicated within the context of a consumer using embed. Discussed in relation to the DRMC in SearchWorks as well. 

#ItsComplicated ¯\_(ツ)_/¯

**Comment by cbeer** [comment]
React.js :trollface: ?

**Comment by aeschylus** [comment]
"Yeah, bro. It's _isomorphic_".

Actually not the worst idea though.

Whenever the issue of deep-linking has come up, it is rarely accompanied by guidance as to the route structure or semantic requirements of the linking urls. In Mirador, for instance, there are dozens of parameters per window representing the view... _per window_. So how do you make a nice url? I like the way jsfiddle does their urls, with a "base" and "branch" number. This allows you to share specific states (and archive them) without requiring some arbitrary and unavoidably ill-conceived url path scheme.

**Comment by snydman** [comment]
I think deep linking to a default view of an individual image in a multi-image object is important. Less so to specific zoom levels, for example.

**Comment by mejackreed** [comment]
Stu, when you say "default view" what does that mean? Is this something given by IIIF manifest? Or is this a parameter passed in from a requestor of embed?

**Comment by aeschylus** [comment]
`http://...?image=[IIIIFCanvasID]` ?

**Comment by snydman** [comment]
When I say default view, I mean single-page view, which I know is an oversimplificiation.  But I think in this case we need to keep it simple and not try to create a solution for every state of the viewer.  

See: http://www.read.gov/exquisite-corpse/Book/#page/24/mode/2up

or https://purl.stanford.edu/bb537hc4022#image/2/thumb
