### ISSUE TITLE
Can we specify a tileSize < 400px for the image viewer?

### ISSUE THREAD

**Issue by mejackreed** [sul-dlss/sul-embed#342]
This goes to concerns that @rosy1280 (and others) have about permissions set on stacks for IIIF image tiles served.

If we could set the tileSize < 400 this might help solve the issue.

https://openseadragon.github.io/docs/OpenSeadragon.IIIFTileSource.html#tileSize

(it looks like this param might be deprecated in the future)

**Comment by cbeer** [comment]
I'm not sure that resolves @rosy1280's concern (although I just skimmed that thread..). The problem I think we're seeing is that stacks isn't enforcing tiles separate from thumbnails, so any request for a tile smaller than a thumbnail will succeed (even if zoom is restricted).

**Comment by mejackreed** [comment]
Yep.. this doesn't solve the problem turns out. I think the problem @rosy1280 is referring to is zoom enabled images. I think part of this can be solved on the info.json response
