### ISSUE TITLE
_loadImages should stop being called after all images are loaded

### ISSUE THREAD

**Issue by mejackreed** [sul-dlss/sul-embed#344]

**Comment by aeschylus** [comment]
?

**Comment by mejackreed** [comment]
https://github.com/sul-dlss/sul-embed/blob/master/app/assets/javascripts/modules/image_x_viewer.js#L149 This continuously gets called. It should stop trying to reload the images after they are all loaded

**Comment by mejackreed** [comment]
Resolved in m3
