### ISSUE TITLE
When switching back and forth between images (using thumb slider) the browser will always request info.json again

### ISSUE THREAD

**Issue by mejackreed** [sul-dlss/sul-embed#379]
Should this be cached? In a store? Or do we need to even cache this?

**Comment by aeschylus** [comment]
I think any URL will be re-"requested" even if it's cached. I believe it just returns the result from the browser's own cache. We do need to make sure to use exactly the same urls, however. So, for instance, the bottom panel thumbs should be the same urls that are used for the canvas. I believe I just request an image of twice the basic display width, in case it needs to be scaled. See: https://developers.google.com/web/fundamentals/performance/optimizing-content-efficiency/http-caching#invalidating-and-updating-cached-responses

and: https://github.com/aeschylus/iiifManifestLayouts/blob/master/src/main.js#L410

I should be using iiifUtils for that, but haven't gotten around to updating it yet. Perhaps the utils/results should be exposed by manifestor somehow.

**Comment by aeschylus** [comment]
Nope, it looks like this is in fact happening. Openseadragon is trying to add a new tilesource every time for the zoomed-in view. The refactoring we talked about will address this as well.

**Comment by mejackreed** [comment]
:+1:
