### ISSUE TITLE
Button style updates visual design.

### ISSUE THREAD

**Issue by mejackreed** [sul-dlss/sul-embed#381]
Todo's:
 - discuss with @jvine and @ggeisler

**Comment by aeschylus** [comment]
Ancillary question: shouldn't the heading be a heading? I think the heading should be a heading with a line-height equal to the height of the header bar, which will properly centre it vertically. 

Opinion: Then the buttons should be absolutely positioned to the right, perhaps with a collapsible menu for mobile. Long titles can either be elided or the font size can be changed to allow wrapping.

**Comment by jvine** [comment]
Agree that the heading should be a heading. Oddly, it is currently an h2 in SearchWorks, and not a heading elsewhere.
