### ISSUE TITLE
Constrain zooming in overview, limit interaction to a vertical scroll

### ISSUE THREAD

**Issue by mejackreed** [sul-dlss/sul-embed#382]

**Comment by aeschylus** [comment]
This is already done. If it seems that it is not done, it's probably because manifestor is actually in detail mode, but just didn't constrain zooming out. If that isn't the case, then it is a bug.

**Comment by aeschylus** [comment]
Sometimes when zooming out programatically, the user's own zooming disrupts the state of the overview events, breaking the event constraints there.
