### ISSUE TITLE
controls disappear in full screen mode

### ISSUE THREAD

**Issue by snydman** [sul-dlss/sul-embed#420]
shouldn't i have access to icons to change state, navigation controls (when they are added), etc in full screen mode?

**Comment by mejackreed** [comment]
@snydman this was tried in one way (full screening the entire embed), but increases the scope of this feature significantly. It is possible to do this, but will require significant enhancements to sul-embed and iiifManifestLayout. A possible intermediary solution could work, but i'm concerned about shipping something at this point. Is this a blocker?

**Comment by snydman** [comment]
@mejackreed @aeschylus : I would't call it an absolute blocker, but it causes us to fall short on parity with current embed widget.

**Comment by mejackreed** [comment]
@snydman though some this behavior is in the current embed widget, i would say that the usability is questionable and the experience on visualization systems is dismal

**Comment by mejackreed** [comment]
@snydman After thinking about this a bit more, I think we should remove the fullscreen option when a user is not in detail view.

**Comment by aeschylus** [comment]
Just leaving a note for us later than `:fullscreen` [is a pseudo-class in css3](https://developer.mozilla.org/en-US/docs/Web/CSS/%3Afullscreen)

**Comment by mejackreed** [comment]
resolved in m3
