### ISSUE TITLE
Only enable "paged" mode for correct viewing hint

### ISSUE THREAD

**Issue by mejackreed** [sul-dlss/sul-embed#421]
Currently "paged" is enabled for every multi image object. This should only be enabled for "paged" viewing hints.

**Comment by aeschylus** [comment]
Is this new? I might have left something in manifestor.

**Comment by mejackreed** [comment]
No this is the current behavior of the image viewer. "Paged" button is on every multi image object (currently)

**Comment by aeschylus** [comment]
Ah, I see. I thought you meant the paged layout setting was being
automatically applied to everything, which I wasn't seeing.

**Comment by aeschylus** [comment]
Closing this as duplicate, since I think #423 is more descriptive.
