### ISSUE TITLE
Mouse control navigation

### ISSUE THREAD

**Issue by mejackreed** [sul-dlss/sul-embed#428]
We removed this functionality specifically from the design. We can use this ticket to discuss the how this should be implemented and the design.

**Comment by aeschylus** [comment]
It would obviously implemented better visually, but is there any objection to this:

![mockup_2](https://cloud.githubusercontent.com/assets/145874/9886589/f6b5685e-5b9f-11e5-9ded-9e81a49a6d32.png)

**Comment by mejackreed** [comment]
We already have horizontal navigation control using the thumbslider. I thought that there was some pushback from putting controls over images?

Honestly I'm curious who and how this is going to be used, rather than implementing because it is a feature in the older embed.

**Comment by snydman** [comment]
So far from what I have seen, the thumbslider is insufficient navigation for a paged (book-like) item. It does not work like the scroll bar we are all familiar with, in that you can click in front of or behind the bar to page ahead or forward one increment. Even if that worked, I don't think it would be sufficient for a paged item.  The keyboard controls will be helpful.  This is not about older embed....the page next/previous/goto function in the UI is a common and useful convention for any bookreader.  

There may be pushback on putting controls over images, but it seems there are lots of places we could put next and previous controls that do not interfere with the images.

**Comment by mejackreed** [comment]
The scroll action was initially added in that same pull request but removed because of the bugginess of it. But I definitely see your point here. One of my big concerns (and I think they were shared) was reducing the number of buttons/controls that were visible to the user. I'll work on some designs to implement this.
