### ISSUE TITLE
Gap between images in two-page view too wide

### ISSUE THREAD

**Issue by snydman** [sul-dlss/sul-embed#438]
![image](https://cloud.githubusercontent.com/assets/3279382/10025770/ccd1bc04-6112-11e5-833d-12fb012167a7.png)

**Comment by aeschylus** [comment]
This is part of https://github.com/sul-dlss/iiifManifestLayouts/issues/77

**Comment by aeschylus** [comment]
I will have a PR in for this shortly. The gap is supposed to be a set percentage of the viewport's pixel width, but is being calculated as a percentage of the page widths, whose actual appearance varies widely depending on zoom level.
