### ISSUE TITLE
Image viewer displays for objects without published content

### ISSUE THREAD

**Issue by rosy1280** [sul-dlss/sul-embed#465]
The image viewer appears for these two objects even though there is no content published for the object:
https://purl-test.stanford.edu/ff228qr7324
https://purl-test.stanford.edu/pz801bw0071 

The first one has no files shelved.
The second one has files that are shelved in the stacks, however the files are not published; you'll notice that the public xml for the object makes no mention of the files.

**Comment by mejackreed** [comment]
Similar to #464 around what should the behavior be when there is no content? Thoughts @jvine ?

**Comment by cbeer** [comment]
I think the current behavior is to show nothing at all. It's not a great experience as a developer, but an end user doesn't know that they're missing anything.

**Comment by cbeer** [comment]
The IIIF manifests for these objects return 404s:

https://purl-test.stanford.edu/pz801bw0071/iiif/manifest.json

The public xml for these objects describe no resources, so PURL refuses to generate one.

sul-embed throws an exception when the manifest is not found. sul-embed should also provide useful fallback behavior ("This page intentionally left blank", "Nothing to see here", etc).

**Comment by mejackreed** [comment]
@jvine @rosy1280 what should we say here: "This object has no images to display"

**Comment by mejackreed** [comment]
Ugg I hate "This object" feels way to library

**Comment by jvine** [comment]
"This object" feels too *library*?? To me it sounds *developery*. Heh.

Why does the object have no images? Do we know? (e.g. images will come later; images are private; somebody made a mistake?)

"There are no images to display." - generic, and a dead-end for the user. Would be nice if we could offer some explanation.

**Comment by mejackreed** [comment]
It's hard to say why there are no images... could be several reasons that sul embed doesn't know about. But essentially, PURL is not delivering a manifest

**Comment by mejackreed** [comment]
@cbeer @rosy1280 are there any objects in the wild with this behavior? (Not just ones in test)

**Comment by LynnMcRae** [comment]
The problem is in publish. The contentMetadata stanza should not be there at all when there is no published content; it should only be there to convey published resources. Will open a separate ticket and republish purls in prod for affected entries.

**Comment by LynnMcRae** [comment]
erp, sorry, not sure I should have closed the ticket in case there is other activity needed here.

**Comment by LynnMcRae** [comment]
This is addressed in https://github.com/sul-dlss/dor-services/issues/97
