### ISSUE TITLE
Image viewer doesn't display more than one image for content type = image

### ISSUE THREAD

**Issue by rosy1280** [sul-dlss/sul-embed#466]
When content type = image, the image viewer only seems to be able to pick up the first image.  See: https://purl-test.stanford.edu/kh361xj6786

**Comment by mejackreed** [comment]
Confirmed this was fixed with 62f1b5410a910afcc8d52dd9d0011ab579b4a3e5 which was added to embed in 133fb6f2593191283346831ba992b803eb613925 . Deployed latest to stage which resolves issue.
