### ISSUE TITLE
What should the copy be to prompt users to login?

### ISSUE THREAD

**Issue by mejackreed** [sul-dlss/sul-embed#472]
cc @jvine @ggeisler 

<img width="641" alt="screen shot 2015-10-25 at 10 33 12 pm" src="https://cloud.githubusercontent.com/assets/1656824/10721960/74d34fd4-7b68-11e5-97ff-96226c11628c.png">

**Comment by cbeer** [comment]
We should also update the text we put in the IIIF responses:

- https://github.com/sul-dlss/purl/blob/master/app/models/iiif_presentation_manifest.rb#L119
- https://github.com/sul-dlss/digital_stacks_rails/blob/master/app/controllers/iiif_controller.rb#L97

**Comment by jvine** [comment]
Various options:
- Stanford-affiliated users: Login to view
 - this is embedded in a half-million or so MARC records
- Stanford-affiliated? Login to view
- Part of Stanford? Login to view
 - like Box
- Login with SUNet ID to view
 - Stanford-only implicit in SUNet ID
 - same pattern as Requests
- Stanford and affiliates: Login to view 
 -  like StanfordWho

**Comment by ggeisler** [comment]
I like "Login with SUNet ID to view"

**Comment by mejackreed** [comment]
I'm leaning towards "Part of Stanford? Login to view." Because embed can and is embedded everywhere, we should use more generalized language.

**Comment by ggeisler** [comment]
That's a good point. Though in that case I like "Stanford-affiliated? Login to view" a bit better ("part of" sounds kind of vague/informal) but whatever you and @jvine agree on is what you should go with.

**Comment by jvine** [comment]
Would this be too vague: "Stanford: Login to view"  ?  Otherwise I'd go with "Stanford-affiliated? Login to view".

**Comment by mejackreed** [comment]
My top 2 are:

 - "Stanford-affiliated? Login to view"
 - "Part of Stanford? Login to view"

Thinking "Stanford-affiliated? Login to view" ... @cbeer can you make that change via stacks. I have embed already referencing the `label` coming back

**Comment by cbeer** [comment]
:ok_hand: 

- https://github.com/sul-dlss/digital_stacks_rails/pull/9
- https://github.com/sul-dlss/purl/commit/57f52dd1c0401d5175715f247068f84d39cf5688

I'll deploy those, hopefully after we get the load-balanced pairs going.

**Comment by mejackreed** [comment]
:clap: ... thanks @cbeer
