### ISSUE TITLE
Can embed be configured to suppress zoom even if allowed

### ISSUE THREAD

**Issue by snydman** [sul-dlss/sul-embed#483]
This may be an edge case, but there will be cases when zoom functionality doesn't make sense for an image, even if it is allowable by its rights.  A postage stamp, a roman coin or a digital bookplate may be examples.  In the case of the digital bookplate, a morae-like pattern effect is introduced by the zoom viewer https://purl.stanford.edu/dn148nh1196.

What are the options to deal with this?

**Comment by mejackreed** [comment]
Well it could be, but should this be expressed via Presentation API?

**Comment by mejackreed** [comment]
I'm not seeing the pattern anymore. Closing for now.
