### ISSUE TITLE
Users can right click and download an image when in full screen

### ISSUE THREAD

**Issue by rosy1280** [sul-dlss/sul-embed#488]
When viewing a no-download objects in full screen, a user can right click and save image as.  To re-create go to https://purl.stanford.edu/zz234zw6791, expand the image to full screen, right click on the image, choose save image as.  This works in Chrome and Firefox, but not Safari.

**Comment by rosy1280** [comment]
Note that the save image as function is essentially a short cut to taking a screenshot of the image, so if I move the image around and zoom in enough so that I can only see a portion of the image, that is all that will be saved when I save the image.  Also the image is being saved as a png, not a jp2 which is the actual file extension for the image.

**Comment by mejackreed** [comment]
We need to fire `_disableClicks` on fullscreen open (https://github.com/sul-dlss/sul-embed/blob/master/app/assets/javascripts/modules/image_x_viewer.js#L256)

https://github.com/sul-dlss/sul-embed/blob/master/app/assets/javascripts/modules/image_x_viewer.js#L395-L401
