### ISSUE TITLE
Gallery view for virtual atlas: MD labels display on top of thumbnails

### ISSUE THREAD

**Issue by caaster** [sul-dlss/sul-embed#500]
Please see attached screen shot. This creates a jarring and unusable experience for the user. Can the labels be truncated instead? 
<img width="1332" alt="screen shot 2016-02-10 at 8 49 13 am" src="https://cloud.githubusercontent.com/assets/3210225/12957548/01eac118-cfe2-11e5-9b7a-6bc2b0de42a9.png">

**Comment by mejackreed** [comment]
Reviewing quickly, feels like we can solve this in embed with:
```scss
overflow: hidden;
text-overflow: ellipsis;
white-space: nowrap;
```
on the `sul-embed-image-x-frame-label` class.

A more holistic approach may be done in iiifManifestLayout, but we can get away without it.
