### ISSUE TITLE
Image download for FRDA - Images de la Revolution is non-functional in Firefox (ver 31.4.0)

### ISSUE THREAD

**Issue by caaster** [sul-dlss/sul-embed#505]
Behavior is as follows:
- Navigate to a FRDA image, such as: http://frda.stanford.edu/en/catalog/pc046yg7765
- Click on download arrow & select size to download (in this example, I chose 313 X 514)
- Behavior: embed viewer disappears from browser window & download can't be found 
-- See screen shot
- NOTE: when I tried the above with Chrome (Version 43.0.2357.130 (64-bit)) -- download was successful & embed window did not dis
![screen shot 2016-02-29 at 2 40 00 pm](https://cloud.githubusercontent.com/assets/3210225/13411540/6f3f6c04-def2-11e5-93a8-df2468753370.png)
appear

**Comment by jkeck** [comment]
After a quick test, I believe the change in #492 will actually address this.

It has not been deployed yet, but once it has I think the download links will begin to work again in Firefox.

**Comment by mejackreed** [comment]
Yep just been talking about that. It is currently deployed on stage.

**Comment by jkeck** [comment]
:metal:

**Comment by mejackreed** [comment]
Resolved by #492 fix deployed to production Tue Mar 15 21:46:13 PDT 2016
