### ISSUE TITLE
evaluate accessibility of media player

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/sul-embed#512]
@jvine as an initial contact point

Accessibility concerns are mentioned here:

https://jirasul.stanford.edu/jira/browse/MEDIAINFRA-31
https://jirasul.stanford.edu/jira/browse/MEDIAINFRA-46
https://jirasul.stanford.edu/jira/browse/MEDIAINFRA-45
https://jirasul.stanford.edu/jira/browse/MEDIAINFRA-44

**Comment by jkeck** [comment]
@jvine we're now using the videojs player.  Looking over the resulting markup, it looks pretty good, but perhaps we can have you take another look over it before we officially go to prod.

**Comment by jvine** [comment]
Filed #668 and #669 re screen reader and keyboard accessibility.

I'm going to assert that the accessibility of videojs is established:
https://accessibility.oit.ncsu.edu/blog/2013/05/09/accessible-video-js-player-available-on-global-accessibility-awareness-day/

More to come.

**Comment by jvine** [comment]
Further comments in https://jirasul.stanford.edu/jira/browse/MEDIAINFRA-44.

**Comment by ndushay** [comment]
hrmm - we need to look at https://jirasul.stanford.edu/jira/browse/MEDIAINFRA-44  and determine what work remains.   @hannahfrost @jkeck
