### ISSUE TITLE
Identify and Document contentMetadata needs in public xml necessary for media streaming

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/sul-embed#525]
(replaces sul-dlss/media/issues/6 )

For image content, each resource has an tag added that records image height and width, taken from jhove's technical metadata.

Will media have a similar need, either for a common or separate and ? The criteria is what embed will need to create the proper experience when instantiating the embed viewer -- duration? encoding? etc. It would also be data included in a future ixif manifest for media for the same reasons.

Involves mapping from known technical metadata (multiple forms?) to contentMetadata in the right places for publishing in Public XML. This is currently something the accessioning robots do for image I think.

**Comment by ndushay** [comment]
This is perhaps blocked by #513  and perhaps also blocked by sul-dlss/media/#5

**Comment by jkeck** [comment]
Currently, the only desirable thing missing from the public XML is the height/width dimensions of the video file (to be added to the `<video>` element to prevent re-sizing.  

More things may come to light in the future.
