### ISSUE TITLE
Update sul-embed design to support mixed media objects

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/sul-embed#530]
Images with multiple file types that require multiple viewers should be supported...a mixed media object (e.g. video and images) that allows both types of media to have different viewers should be displayable without just presenting download links for the files.

Design should allow for multiple players, including:
* image
* video 
* audio
* pdf 
* download link

**Comment by hannahfrost** [comment]
Related user story: https://jirasul.stanford.edu/jira/browse/MEDIAINFRA-54
