### ISSUE TITLE
Implement support for mixed media object displaying in sul-embed

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/sul-embed#531]
* images
* video
* audio
* file download

depends on #530

**Comment by hannahfrost** [comment]
Related user stories:
https://jirasul.stanford.edu/jira/browse/MEDIAINFRA-44
https://jirasul.stanford.edu/jira/browse/MEDIAINFRA-7

**Comment by ndushay** [comment]
@jkeck, @jmartin-sul:  is this done?

**Comment by jkeck** [comment]
I suppose.  This is a pretty high-level ticket so I think we can call it closed.
