### ISSUE TITLE
Show visible zoom in/out controls for images

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/sul-embed#534]
The old image viewer had +/- icons for zooming in and out using mouse clicks.  sul-embed allows zoom with double-click, scroll wheel, and +/- keyboard buttons.  However, there is no access to visible zoom controls, which could be useful for users who do not have scroll-wheel enabled mice and may not be aware of keyboard shortcuts (particularly since there is no visible clue that the image is zoomable).

**Comment by mejackreed** [comment]
resolved w/ m3
