### ISSUE TITLE
Show number of downloadable files next to download icon

### ISSUE THREAD

**Issue by jvine** [sul-dlss/sul-embed#561]
Only images and media files are listed in the index (filmstrip) below the player. Extra files (pdf, zip, etc.) are listed only in the download slider. 

Add a badge next to the download icon showing the total number of downloadable items (i.e. downloadable media and images, plus extra files).

![download-count](https://cloud.githubusercontent.com/assets/6945691/15342524/afb41358-1c4a-11e6-9c31-8ec0d5c654bb.png)

List all media files and all supplemental files in the download panel (and count) regardless of which file is currently selected in the player.

Deprecating this next bit for now, not sure we want to do it.
> Possible future requirement:  Follow the image model, and list in the download panel (and count):
> 1. the currently-selected media file, 
> 2. any dependent files (e.g. a linked transcript),
> 3. any object-level supplemental files (e.g. images of the container, zip file...)
> ... so the list and (possibly) count will change with each selected video.

**Comment by ndushay** [comment]
@jvine  presumably the choice was explicitly made that the number of files was not part of the selected div?

![selected div](https://cloud.githubusercontent.com/assets/96775/15879178/8c13b916-2cd6-11e6-94c7-d21cec3d89fa.png)

**Comment by jvine** [comment]
Was not explicit. It would be nicer if they were part of the same focusable element. Not unusable as-is.

**Comment by ndushay** [comment]
If you would like them in the focusable part, can you make a new ticket for it?
