### ISSUE TITLE
Updating the style and text of "Login to play Stanford-only media" link

### ISSUE THREAD

**Issue by jvine** [sul-dlss/sul-embed#562]
Same interaction pattern as images:  add login link in the lower-left corner of the embed. User clicks link, authentication happens in another tab.

![login](https://cloud.githubusercontent.com/assets/6945691/15342647/fc815f96-1c4b-11e6-9ef7-42d5aaa28dd3.png)

Visual design of the link can be made global for all embedded objects. 
- tab is $color-cardinal-red
- 15px space between tab and footer
- white-on-red s icon: ![s](https://cloud.githubusercontent.com/assets/6945691/15342693/59d8e7ae-1c4c-11e6-88be-c408c44dbcab.png)
- link should be attached to the side of the embed viewer

**Comment by ndushay** [comment]
@jvine we also need an svg of the white-on-red S icon;  is that something you can create, or should we do it?

**Comment by jkeck** [comment]
@jvine also, is there a desired color for the hover state of the link.

**Comment by ndushay** [comment]
focus  color was yucky too.

**Comment by ndushay** [comment]
15 px between bottom and tab may need to var with multiple media dot thingy.

**Comment by ndushay** [comment]
worked with @jvine in person;  styling is approved.

**Comment by ndushay** [comment]
@jkeck  when I logged in with safari, 2 problems:

1.  residual pixel coloring
2.  video didn't play until I did a refresh.

**Comment by ndushay** [comment]
Note:  need svg icon before closing this ticket, in addition to problems above.

**Comment by ndushay** [comment]
Took care of residual pixel coloring with @jkeck yesterday;  video not playing may be due to multiple 2-step webauth requests (easy to push notification button multiple times in safari);  closing this.
