### ISSUE TITLE
Implement location-restricted media message when access is restricted

### ISSUE THREAD

**Issue by jvine** [sul-dlss/sul-embed#564]
- background is sul-i-file-video-3 in $color-beige-20 ~300px high
- overlay with a div with white background, 50% opacity
- inside the div, center:
 - Restricted media cannot be played in your location. [36px; font-weight: 100;]
 - See Access conditions for more information. [24px; font-weight: 100;]

![restricted](https://cloud.githubusercontent.com/assets/6945691/15343549/8141280a-1c52-11e6-81ca-18b1e67bb5b2.png)

connects to #587 
connects to #589

**Comment by ndushay** [comment]
is this somehow a dup ticket?

**Comment by jmartin-sul** [comment]
i believe this is implemented by the PR #598, as part of implementation for issue #587 and issue #589

**Comment by ndushay** [comment]
closed as dup
