### ISSUE TITLE
Review and provide feedback for restricted media and public images

### ISSUE THREAD

**Issue by jvine** [sul-dlss/sul-embed#568]
Some examples to show how restricted video/audio would appear combined with related files:

### Before:
![bt048qc6063-before](https://cloud.githubusercontent.com/assets/6945691/15413575/811e673a-1de6-11e6-822d-c359e30d65b4.png)

### After:
- "Restricted media" message appears for the single audio file.
- Transcript is listed in the download panel (with filename and size)
- Count of downloadable files is 1

![bt048qc6063-after](https://cloud.githubusercontent.com/assets/6945691/15413578/83cdb008-1de6-11e6-84ac-fe2cfb97106a.png)

### Before:
![db950zr9905-before](https://cloud.githubusercontent.com/assets/6945691/15413629/1f8c0580-1de7-11e6-872d-aac3976d156b.png)

### After:
- Index shows media and image
- When media is selected, the "Restricted" message appears

![db950zr9905-after-restricted](https://cloud.githubusercontent.com/assets/6945691/15413634/32dadde6-1de7-11e6-914c-fe51c350d982.png)

- When image is selected, image thumbnail is shown, with no zoom-pan 

![db950zr9905-after](https://cloud.githubusercontent.com/assets/6945691/15413654/5b6e5c60-1de7-11e6-9497-43a909077d69.png)

- Download panel lists full-size image of the media
- Count of downloadable files is 1
- (Why is the "k" in "kB" in lower case? is it meaningful?)

![db950zr9905-after-download](https://cloud.githubusercontent.com/assets/6945691/15413703/f1d77c4a-1de7-11e6-8f99-39b41dbd5eb9.png)

**Comment by hannahfrost** [comment]
@jvine I reviewed these designs today with Glynn and Michelle from SPEC. They meet SPEC's needs and look great. So 👍  from us.
