### ISSUE TITLE
Show message for location-restricted content

### ISSUE THREAD

**Issue by jvine** [sul-dlss/sul-embed#577]
### 1) Either come to the reading room OR login. 
- show the player, with keyframe if there is one
- overlay message to non-stanford users
- show login link
- 1 item available for download; panel will have a red s next to the filename

![location-or-login](https://cloud.githubusercontent.com/assets/6945691/15796077/e950993c-29ac-11e6-90e4-a1522c3d5dd2.png)

### 2) Must login, no matter where you are. 
- same as 1, minus the message to non-stanford users

![login-to-play](https://cloud.githubusercontent.com/assets/6945691/15796092/210fa214-29ad-11e6-8353-ec9efaa2b478.png)

- if there are multiple files in the index, any stanford-restricted files have a red "s" after the label
- note the login label position is relative to the index, so it's not hidden when the index is open
 
![login-to-play-index](https://cloud.githubusercontent.com/assets/6945691/15796385/9beb416a-29b1-11e6-8c0d-9184afbf215c.png)

### 3) Must come to reading room, no matter who you are.
- show icon, no keyframe
- overlay message to all users
- no login link
- download panel has a count of 0, assuming there are no supplemental files

![nothing-to-see-here](https://cloud.githubusercontent.com/assets/6945691/15796082/01a33af8-29ad-11e6-8259-1a7aaed53f98.png)

- if there are multiple files in the index, any location-restricted files have the word "(Restricted)" after the label
- download count ... I'm guessing if the item is location-restricted, it's not downloadable at all? so the count matches the number of actually downloadable files (including stanford-authed downloads)

![nothing-to-see-index](https://cloud.githubusercontent.com/assets/6945691/15796286/3ef96726-29b0-11e6-8afb-88ca39a497b8.png)

**Comment by ndushay** [comment]
closing in favor of #587 #588 #589 and sul-dlss/digital_stacks_rails#54
