### ISSUE TITLE
ensure special chars in (media) filenames are encoded properly for download and stream requests

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/sul-embed#578]
See https://github.com/sul-dlss/digital_stacks_rails/pull/56;   esp.  routing specs, to see which chars need to be URL encoded for  digital stacks.   Media requests have some unique needs.

**Comment by ndushay** [comment]
part of sul-dlss/digital_stacks_rails/issues/49

**Comment by ndushay** [comment]
improved by sul-dlss/dlss-wowza#28.  

@LynnMcRae  will retest and update https://github.com/sul-dlss/media/wiki/Examples-of-files-deposited-by-ETD-users,-special-characters-and-media-files

**Comment by LynnMcRae** [comment]
Note the two test objects referenced on the consul page:

- Image test object – https://purl-test.stanford.edu/fg019pm1396
- Media test object – https://purl-test.stanford.edu/ym777gf7400

**Comment by ndushay** [comment]
* known bug with spaces in image file names
* consul page identifies what we support.
