### ISSUE TITLE
update dash viewer to fix protected videos in non-safari

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/sul-embed#581]
the bug was fixed by https://github.com/Dash-Industry-Forum/dash.js/pull/1392

**Comment by jkeck** [comment]
It appears that adding `withCredentials` to an XHR request requires that the `Access-Control-Allow-Origin` **not** to be set to `*` (as it is now) and instead be the actual origin of the request.

In addition, the response needs to include the `Access-Control-Allow-Credentials=true` in order for the CORS request with credentials to succeed.

**Comment by tingulfsen** [comment]
A couple of useful links pertaining to this issue:

https://github.com/videojs/videojs-contrib-hls#list

http://www.html5rocks.com/en/tutorials/cors/

**Comment by ndushay** [comment]
depends on #600, etc.

**Comment by tingulfsen** [comment]
Note that gm746xg1831 is a good test object.
