### ISSUE TITLE
create/get svg icon for stanford s red text white background

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/sul-embed#584]
this is the final part of #562  (Updating style and text of "Login to play Stanford-only media")

We have png and svg versions of images used in sul-embed, but we still need the svg version of the stanford S red on a white background.  The png image is 

https://github.com/sul-dlss/sul-embed/blob/562-media-login-stylin/app/assets/images/stanford_red_s.png

(or in #562)

Once image is avail in project, need to uncomment line 55 in app/assets/stylesheets/mixins.scss.erb:

https://github.com/sul-dlss/sul-embed/blob/562-media-login-stylin/app/assets/stylesheets/mixins.scss.erb#L52-L56

**Comment by mejackreed** [comment]
Could be added to sul-styles like we did for the GeoBlacklight-Icons for use in EarthWorks:

http://geoblacklight.org/geoblacklight-icons/docs/styleguide/geoblacklight-icons-preview.html

Or feel free to grab the Stanford "S" from that project.

**Comment by ndushay** [comment]
@mejackreed thanks!  But we need a red S on a white background.  Or maybe I'm just missing the point of your post?

**Comment by mejackreed** [comment]
Yep you could do that with the icon font and css (and add a background):
https://github.com/geoblacklight/geoblacklight/blob/master/app/assets/stylesheets/geoblacklight/modules/icon-customization.scss#L8-L10

Or you could just grab the SVG file and create your own. Just wanted to point you to work that already had been done.

**Comment by ndushay** [comment]
@jkeck says that the geoblacklight one isn't quite the same as what we're using (e.g. rounded corners, possibly different).  

in reality it should be in sul-styles.
