### ISSUE TITLE
add overlay message to media viewer when rights are location OR stanford

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/sul-embed#589]
(do this before #587)

from #577 

- [ ] show the player, with keyframe if there is one (Note:  we have no keyframe support in contentMetadata at this time)
- [ ] overlay message to non-stanford users
- [x] show login link
- [x] 1 item available for download; panel will have a red s next to the filename

![location-or-login](https://cloud.githubusercontent.com/assets/6945691/15796077/e950993c-29ac-11e6-90e4-a1522c3d5dd2.png)

**Comment by jkeck** [comment]
@jvine should the `Limited access for non-Stanford guests.` be a heading?

**Comment by jvine** [comment]
Not a heading. I'm pretty sure it doesn't need to be anything other than text content.

**Comment by ndushay** [comment]
@jvine:   we clumped and got to here.  We need more info on colors and styling desired.  

![wip - 587](https://cloud.githubusercontent.com/assets/96775/15980976/a642336c-2f24-11e6-85f1-9a6f94c61538.png)

**Comment by jvine** [comment]
Here's what I did:
```
.sul-embed-media-location-restricted {
    background-color: white;
    border-radius: 10px;
    padding: 20px 25px;
    opacity: .9;
    width: 80%;
}
}
.sul-embed-media-location-restricted.line1 {
    display: block;
    font-size: 35px;
    font-weight: 100;
}
.sul-embed-media-location-restricted.line2 {
    display: block;
    font-size: 24px;
    font-weight: 100;
}
```

![screen shot 2016-06-10 at 5 16 47 pm](https://cloud.githubusercontent.com/assets/6945691/15981769/30e30208-2f2f-11e6-8c9f-1e7d776266eb.png)

**Comment by jmartin-sul** [comment]
WIP branch:  https://github.com/sul-dlss/sul-embed/compare/589-overlay-message

added a couple small commits (one takes a shot at applying @jvine's css suggestions, the other is a minor rubocop fix).  did no rebasing (to make it easy to revert in case i did the wrong thing).
