### ISSUE TITLE
Multi-image test object with special characters breaks image viewer in sul-embed

### ISSUE THREAD

**Issue by LynnMcRae** [sul-dlss/sul-embed#595]
This display is messed up:
https://purl-test.stanford.edu/fg019pm1396

![screen shot 2016-06-14 at 12 28 47 pm](https://cloud.githubusercontent.com/assets/1824732/16056741/bdc2bb38-322b-11e6-96ef-8d467f1f5a6f.png)

The IIIF manifest is available here.  It can be dropped into Mirador and it works ok.

The object is there to test for character set limitations in file names, so each of the resources after the first, main image has a special character added to the name, in case this is what has caused some parsing difficulty. Besides the ghost gallery, the standard image controls are missing from the top right.  The download list looks ok though.

**Comment by mejackreed** [comment]
I'm not sure this is relevant anymore without having available fixtures.
