### ISSUE TITLE
Add (Restricted) text to location restricted media objects in filmstrip

### ISSUE THREAD

**Issue by jkeck** [sul-dlss/sul-embed#602]
Note that the text should be before the object title (similar to the Stanford S icon for Stanford content).

![restricted-text](https://cloud.githubusercontent.com/assets/6945691/15796286/3ef96726-29b0-11e6-8afb-88ca39a497b8.png)

**Comment by LynnMcRae** [comment]
Cover story ticket - https://github.com/sul-dlss/sul-embed/issues/597
