### ISSUE TITLE
Make sure images with 400px long-edge on the y-axis are not clipped in media viewer

### ISSUE THREAD

**Issue by jkeck** [sul-dlss/sul-embed#607]
Currently the `body-height` in embed does not give enough room for images that are 400px tall.

We need to allow the embed to be large enough to show the full image or in the case where a maxheight option is set, resize the height of the image (if necessary).

**Comment by jmartin-sul** [comment]
could you give an example object that exhibits this problem?  the only thing @LynnMcRae and i found in our little bit of digging just now was https://purl-test.stanford.edu/pn861pp0444 (which cuts off the bottom of the image when the page loads, but only because the image selection slider is expanded).

**Comment by jkeck** [comment]
@jmartin-sul the druid you're referencing is an image object, not a media object, and therefor not relevant to this ticket (which was only really described via label, so perhaps that's not obvious enough, and it should be more explicit in the ticket).

If you notice the suave gentleman's shirt in https://purl-test.stanford.edu/xv428cw8400, you'll see that the logo is visible in the thumb yet completely cut-off in the full version.

### Thumb
<img width="195" alt="thumb" src="https://cloud.githubusercontent.com/assets/96776/17112390/bcce00ee-525a-11e6-8442-793111db37f0.png">

### Full
<img width="411" alt="full" src="https://cloud.githubusercontent.com/assets/96776/17112391/bccf472e-525a-11e6-97e6-b88c40315343.png">

_Note: the full size of the image is being highlighted above by the inspector, showing a large portion being cutoff_

**Comment by LynnMcRae** [comment]
is it relevant that the thumb seems to crop the top? or is that a square thumb rather than a full thumb per se? not to distract ...

**Comment by jkeck** [comment]
My comment about the thumb was that, even the square crop (via IIIF) used for the index thumbnail shows that we aren't able to see content that is supposed to be the full image.  We should be seeing more than the square crop in that full image, not less.

**Comment by LynnMcRae** [comment]
thanks, I know it was an aside, just confirming it was a square.
