### ISSUE TITLE
Show "number of files" badge for media objects only, not image objects

### ISSUE THREAD

**Issue by LynnMcRae** [sul-dlss/sul-embed#612]
The download list for media shows the (singular) downloadable form of all files.  The addition of a count of files to the display was to address a situation in media where you might have more downloadable entities than visible ones.  

But image objects use the download widget differently. It offers a list of downloadable sizes available for the current image you are looking at, so the count of the number of files is confusing. From https://purl-test.stanford.edu/pn861pp0444 ...

![screen shot 2016-07-19 at 6 17 36 pm](https://cloud.githubusercontent.com/assets/1824732/16972012/31422f86-4ddd-11e6-9a1d-5b66b3f20c70.png)

Talked to Jennifer ... should just not show it for Image objects.

**Comment by jkeck** [comment]
What about the Geo viewer?

**Comment by LynnMcRae** [comment]
Not familiar with GeoViewer, but does it offer a download list per file or one list for all files.  If the former, then it's like image and should not show the badge; if the latter then it's like media and should show the badge, I think, maybe.  Safe think might be to do media only. Need @jvine to weigh in but I can't add her as a participant.

**Comment by jkeck** [comment]
The download panel in the GeoViewer is not dynamic like the image viewer (the image viewer is the only dynamic download panel).

https://purl.stanford.edu/cz128vq0535

**Comment by ndushay** [comment]
spoke to @jvine  and she says display except when it is the image_x viewer.
