### ISSUE TITLE
Show optional text alongside image when in full screen

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/sul-embed#613]
One of the enhancements we added to the old image viewer was to allow the client to indicate a message that should be shown to users when in fullscreen.  For Revs, we pass in the use and reproduction and copyright statement.  (e.g. go here and click to go to fullscreen on the image: https://revslib.stanford.edu/item/yk807wq6530).

Having parity in sul-embed would be a pre-req for full adoption.  It could be implemented as an optional parameter passed by the embedder with the text to be shown.

see https://github.com/sul-dlss/revs/blob/94abee7a42b1a01dc30c710e8f115c5c47443dea/app/views/catalog/_show_collection_member.html.erb#L18 as an example of how it is done in the old viewer

**Comment by mejackreed** [comment]
Is this still relevant?

**Comment by peetucket** [comment]
Not unless this is needed for other projects -- no current need for Revs.
