### ISSUE TITLE
Brackets or braces in image file names causes embed display problems

### ISSUE THREAD

**Issue by LynnMcRae** [sul-dlss/sul-embed#616]
In this character set test PURL -- https://purl-test.stanford.edu/fg019pm1396 -- the formatting in embed looks like this with the presence of file names including { } or [ ]:
![screen shot 2016-07-26 at 10 41 30 am](https://cloud.githubusercontent.com/assets/1824732/17149272/666d4ec4-531f-11e6-9f1a-1a399a58d0b2.png)

If we unpublish those files to remove them from the display, it looks more normal (ignore any other testing artifacts):
![screen shot 2016-07-26 at 10 52 15 am](https://cloud.githubusercontent.com/assets/1824732/17149296/800bb686-531f-11e6-8684-e85713022569.png)

Not urgent since those characters are not expected in our data. I can manipulate the  test object as needed for testing when this gets worked on.

**Comment by LynnMcRae** [comment]
Note that brackets (left or right) creates an error (object cannot be displayed) for the current file list view for file objects. Just an observation from testing characters; should not be allowed in file names (a few ETDs to be cleaned up).

**Comment by mejackreed** [comment]
I'm thinking that Purl should encode this value correctly in the image resource and service `@id`. Do you concur @cbeer ?

**Comment by cbeer** [comment]
👍

**Comment by mejackreed** [comment]
@LynnMcRae looking at the purl xml a bit closer, it looks like this object does not produce valid XML. Could you provide an example with valid xml so we can get this right?

**Comment by cbeer** [comment]
Ah -- it is valid if you view-source... browsers are just being "helpful" at un-escaping things.

**Comment by mejackreed** [comment]
Resolved in purl in https://github.com/sul-dlss/purl/pull/213
