### ISSUE TITLE
Handle Thumbnails (Object and File level) in Media Player

### ISSUE THREAD

**Issue by jkeck** [sul-dlss/sul-embed#623]
Currently, SUL Embed deals with all `<file>` elements w/i a `<resource>` as first-class files.  However; there are certain cases where they should not be treated as first-class files (particularly in the case of the media player).

- [ ] Do not treat files within `<resource type='thumb'>` or `<resource thumb='yes'>` as first-class files (i.e. they should not end up in the media filmstrip, and not be shown in the viewer like a video/audio file).
- [ ] Do not treat `<file type='thumb'>` or `<file thumb='yes'>` as first-class files.
- [ ] Replace icon in media filmstrip with thumb for objects that have a companion thumbnail `<file>` within the same `<resource>`.

**Comment by jkeck** [comment]
@jvine a question came up today when discussing this ticket around object level thumbs and behavior in the file and media viewers.

FWIW, I _believe_ these are currently displaying in the file viewer (as we don't have any code parsing  thumb attributes).  It seems like we should not remove this behavior (as it my be odd to not have access to that anywhere on the detail/record view that uses the embed).

How should we handle these in the media viewer?  If we follow the rules above the object level thumb would only be accessible via the download panel.

**Comment by jkeck** [comment]
dv738kn2168 (purl-test) is a good example object that has both an object-level thumb as well as a file-level thumb.

**Comment by jmartin-sul** [comment]
discussed w/ @LynnMcRae, @jkeck, and @jvine...

what we came up with was the following set of rules, which in practice, mostly line up with the behavior in the description, though this seems like a simpler/clearer formulation:
* the media thumb slider will make available:
  * resources of type `audio` of the appropriate file type (e.g. `mp3`)
  * resources of type `video` of the appropriate file type (e.g. `mp4`)
  * resources of type `image` of the appropriate file type (e.g. `jp2`)
* an image file in a resource will be considered a resource level thumb.  there should only be one image file in a given resource, but if there are multiple, the first will be used.
  * the resource level thumb will show up in place of the generic media icon on the resource entry in the slider, and as the poster (keyframe) for the media player instance when the object is selected.
* other resource types (e.g. resource type `thumb` or resource type `file`) will be ignored by the media slider, which should automatically keep object level thumbs out of the media slider.

![thumbs for media resources 20160816](https://cloud.githubusercontent.com/assets/7741604/17718531/5929e1c2-63c9-11e6-957d-a83b7e6b8734.jpg)

**Comment by jmartin-sul** [comment]
above image shows up properly in preview, and @tingulfsen says camera was rotated correctly.  workaround is for viewer to rotate head.

**Comment by LynnMcRae** [comment]
Here is a rendering of the diagram with commentary for the consul documentation:
![thumbs](https://cloud.githubusercontent.com/assets/1824732/17727836/a730c3da-6410-11e6-9412-a7df5142c1ef.png)

**Comment by LynnMcRae** [comment]
Picture and rules now part of the Rules of Thumb page -- https://consul.stanford.edu/display/chimera/The+Rules+of+Thumb

Question, is it the "index" as I believe Jennifer called it, or "slider", or is it the "index slider"? :)  Any preferred terminology?
