### ISSUE TITLE
Add height/width attributes to the video element

### ISSUE THREAD

**Issue by jkeck** [sul-dlss/sul-embed#626]
This information is available (in our test objects) in attributes on the `<videoData>` element.

**Comment by jmartin-sul** [comment]
looks like we don't need to do this afterall... the intent of this ticket was to avoid the UI hiccup of a video element flickering from its generic version on page load to the version containing the actual video, and to get the video to scale correctly within the player.  as far as we can tell from testing, video js does both of these things automatically.  additionally, when trying to set width and height manually on the video element, we got unexpected results (e.g. shrunken video that was scaled correctly but which didn't occupy as much player space as it could've leaving unnecessary black bars on top and bottom).

as such, closing this ticket and the associated PR.  will keep the work that adds videoData-related methods to PURL ResourceFile, but will track that under a separate ticket/branch/PR.
