### ISSUE TITLE
Cut a release with media disabled and deploy to production

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/sul-embed#632]
Requires disabling media player, communicating changes to stakeholders and deploying just sul-embed to production

**Comment by peetucket** [comment]
try and complete #622 before cutting release

**Comment by jkeck** [comment]
PR's to review/merge before we get the deploy out:

- [ ] #638
- [ ] #639
- [ ] #640

**Comment by ndushay** [comment]
@jkeck deployed this morning, so I expect he'll close this ticket shortly.
