### ISSUE TITLE
sul-embed: use shared_configs

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/sul-embed#646]
and then note in DevOpsDocs and Puppet Facts

**Comment by jkeck** [comment]
https://github.com/sul-dlss/shared_configs/pull/110
https://github.com/sul-dlss/shared_configs/pull/111
https://github.com/sul-dlss/shared_configs/pull/112

**Comment by jkeck** [comment]
https://jirasul.stanford.edu/jira/browse/SAR-3252
