### ISSUE TITLE
Geoblacklight/Earthworks Map/Attrib Preview Window should be an oEmbed.

### ISSUE THREAD

**Issue by mapninja** [sul-dlss/sul-embed#651]
I'd like to see the map previews and attribute inspection in geoblacklight/Earthworks moved into an oembed, so that the purl page gets both, as well as providing the ability to embed the previews into other pages (Spotlight, Blacklight, blogs, etc...).

**Comment by mejackreed** [comment]
Maybe I can chime in here. I think the feature enhancement for embed is:

In the geo viewer:

 - provide attribute inspection for public datasets
    - using WFS in a similiar way that GeoBlacklight does inspection
 - this includes linkifying links that appear in attribute data

There are implementation questions on how this should be done. EarthWorks / GeoBlacklight use a WMS proxy to handle these interactions. That might not be possible here so there will need to be better error handling cases.

Additional design work needs to be done to see how the attribute data should be best displayed.

For reference attribute inspection in EarthWorks:

![screen shot 2016-08-17 at 7 21 16 am](https://cloud.githubusercontent.com/assets/1656824/17734606/44da2218-644b-11e6-9068-80fbc9755090.png)

**Comment by mapninja** [comment]
I'm bumping this issue, since it's been a while. With Spotlight now mature and in production, as well as the new work on index maps functionality in Geoblacklight, I still think this is a valuable feature. Forseeing the ability to build curated data/map collections for course and project support.
