### ISSUE TITLE
Access Restriction Overlays on Audio need to work

### ISSUE THREAD

**Issue by jkeck** [sul-dlss/sul-embed#664]
They are most likely broken given that the default HTML5 implementation's UI is vastly different.

@LynnMcRae will make an audio fixture object for us with various access restrictions.

**Comment by jkeck** [comment]
We now have a test object: https://purl-test.stanford.edu/pd507wn8117  As you can see, the overlay is jumbled due to the fact that we're overlaying an `<audio>` element instead of a `<video>` element.  @jvine what do?

<img width="1162" alt="screen shot 2016-08-24 at 4 18 33 pm" src="https://cloud.githubusercontent.com/assets/96776/17951366/839b96f0-6a16-11e6-8d77-e509bddafa8e.png">

Here is a video object w/ an overlay that looks correct: https://purl-test.stanford.edu/vf466bd3249

**Comment by jvine** [comment]
Ugh. The video object doesn't look correct for me either, though.

![screen shot 2016-08-24 at 5 19 25 pm](https://cloud.githubusercontent.com/assets/6945691/17952388/ef633cbe-6a1e-11e6-8157-944efaf9e1d6.png)

The absolute position doesn't work well when the player is not tall enough to provide room for the message. I think we started this with the assumption that we would always have something filling that space.

I think the icon background is not helping either, and I'm fine with dropping it if it's complicating things.

For video, we want the height to be set by the player, then the restricted message should overlay that space - which requires absolute positioning.

For audio, when the player is only ~30px high, it would be better if the restricted message just appeared in the flow above the player - removing the absolute positioning. 

I don't have any idea what's happening with the scrollbar on the video above, though. 

Ugh.

**Comment by jkeck** [comment]
Should be fixed along with #675.
