### ISSUE TITLE
File Viewer: How should we represent location restricted files?

### ISSUE THREAD

**Issue by jkeck** [sul-dlss/sul-embed#667]
Currently we don't have any UI indication that the file cannot be downloaded due to their location (as we do have in the media viewer).

Do we need to put anything in the UI to inform the user they could not download the file?  We could possible remove the link, but that would have to happen in JS since that would be the only way to definitively know that the user was not in the location.

**Comment by jkeck** [comment]
A related question would be how should we indicate this in the download panel?

**Comment by ndushay** [comment]
@jvine :  It's my understanding you are aware of this and will give us a "design" for this?

**Comment by jvine** [comment]
The goal is:
- user is informed of the status of the file
- user is prevented from encountering an error

So ideally, in a file list AND in the download panel
- files would have the same "S" and/or "(Restricted) indicators that the files in the thumbnail index have, and
- location-restricted files are not linked if the user is not in an allowed location.

**Comment by jkeck** [comment]
For `location-restricted files are not linked if the user is not in an allowed location.`, this may require a little refactor of the `auth_check` action to either be in both controllers, or exist in a central location.

**Comment by jkeck** [comment]
Closing this as tickets have been spawned with the work requirements. (#683 and #684)
