### ISSUE TITLE
Force Flash on Windows IE/Edge

### ISSUE THREAD

**Issue by tingulfsen** [sul-dlss/sul-embed#701]
With Windows 10 64-bit, the latest versions of Internet Explorer (version 11.0.10586.0) and Edge (version 25.10586.0.0) exhibit some strange behavior with our VideoJS player:

* Internet Explorer will play the first 11 seconds of a video, then stop and the video becomes unresponsive.
* Edge plays the videos fine.
* Internet Explorer plays audio fine.
* Edge refuses to play audio.

This was tested with our current Sul-Embed, which uses the VideoJS HLS plugin to play video and plays audio (MP3) with Flash.

Forcing the use of Flash with the Microsoft browsers for all content appears to work fine.

Note that Chrome and Firefox both seem to work as usual, both with and without Flash.

**Comment by jkeck** [comment]
We should reference the [Known Issues](https://github.com/videojs/videojs-contrib-hls#known-issues) section of the VideoJS HLS plugin in our PR to change this for posterity.
