### ISSUE TITLE
ETD's described differently in contentMD

### ISSUE THREAD

**Issue by snydman** [sul-dlss/sul-embed#72]
Lynn suggests that ETDs are described differently in contentMD, however they should be displayed as Files.  What is our strategy for this? Accommodation in the viewer OR remediation of the ETD data?

**Comment by mejackreed** [comment]
Is this issue still valid?

Should the supplement files not be displayed?

**Comment by LynnMcRae** [comment]
Supplement files should be displayed if they are published.  They are typically the data file or similar accompanying the dissertation.
