### ISSUE TITLE
Issue with handling of file-level thumbs.

### ISSUE THREAD

**Issue by jkeck** [sul-dlss/sul-embed#723]
Example: xy943wj0513

There should only be two thumbnails in the index but the second file in the `Tape 1, Side A` resource is an `.jpg` and not a `.jp2`.  (do we get IIIF responses for non JP2 images?)

**Comment by jkeck** [comment]
@LynnMcRae what would be the expected behavior for this object?  Will the .jpg file get served up under IIIF?  (My initial test indicates not, but maybe I'm missing something: https://stacks.stanford.edu/image/iiif/xy943wj0513%2Fxy943wj0513_275_img_1/square/75,75/0/default.jpg)

Should we simply ignore these when trying to build a file-level thumb (but obviously it would be available in the download panel).

**Comment by LynnMcRae** [comment]
A file level thumb is defined as a .jp2 alongside a non-image resource. By definition that resource has no thumb, just an extraneous file that perhaps represents a conversion failure in creating the object, or simply a file that wasn't not meant to be published.  OK to download it 'cause it's there, but that's it.
