### ISSUE TITLE
Unlink no-download files in the download panel

### ISSUE THREAD

**Issue by jkeck** [sul-dlss/sul-embed#728]
Example: https://purl.stanford.edu/zr649jg5679

**Comment by jkeck** [comment]
@jvine do you have any opinion on this?

1. Is it okay for us to just not link the item?
1. Do we nee to remove the `Download...` part since you cannot download?
1. Would you prefer we remove the text all-together?

**Comment by jvine** [comment]
If the file is never downloadable, and there is no need for the user to know of its specific existence/name/size etc. then I'd say we should not display it in the download list and not include it in the download count.

If the file might be downloadable if certain conditions are met (location, login) then the file should be listed and linked (and counted), and the user gets informed about the conditions either before click (red S) or on click (you're not in the right location).

**Comment by ndushay** [comment]
@jvine:  are you ok with this change ONLY affecting the media viewer for now?   (I think the way I have it in #732  affects the download count showing for all viewers, but that could be fixed)

**Comment by jvine** [comment]
@ndushay a) I don't think we have a download count for non-media viewers, do we? and b) I'm unclear on what "this change" is now.

**Comment by ndushay** [comment]
@jvine I will update the screen shots shortly - doing some local testing and hopefully "ready-er" now
