### ISSUE TITLE
User Reports Embed Viewer Slow to Load Images (via PURL Feedback)

### ISSUE THREAD

**Issue by blalbrit** [sul-dlss/sul-embed#733]
See correspondence below. I'm guessing either embed or stacks issue here - will start here and we can move the issue as necessary.

Hi Ben,

Thanks for responding so quickly.  I've seen this image loading problem occur even with smaller objects, such as this Heckrotte atlas with only 7 images.  The first two images appeared when I initially opened it up but then I had to reload it for all 7 to appear.

https://purl.stanford.edu/wq035vh2804

Best,
Emily
BA
Benjamin L Albritton
   |
Thu 12/8, 4:04 PM
Emily,

I do see the problem you're describing. Do you know if this only happens on large objects (511 pages, in this case), or do you see this on single-image maps as well?

For the list: this issue appears to be related to stacks / embed and is not specific to PURL (ie. it occurs with the embed viewer in SearchWorks as well).

Best,

Ben
P
purl-feedback <purl-feedback-bounces@lists.stanford.edu>
 on behalf of 
feedback@purl.stanford.edu
   |
Thu 12/8, 3:58 PM
Name: Emily Prince
Email: ebprince@stanford.edu
Comment:
The thumbnail images don't appear the first time the multi-image view is clicked.  I had to refresh the page in order to see the images.  I've experienced this many times when viewing purls - seems fairly consistent.

Message sent from: https://purl.stanford.edu/rs701sk6219
Host: 
IP: 171.66.18.195
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.85 Safari/537.36
Viewport: width:960 height:507

**Comment by mejackreed** [comment]
@blalbrit with our viewer and image stacks enhancements I think that this issue may be resolved. Feel free to reopen if something seems amiss still.
