### ISSUE TITLE
full-page embed (related to #718)

### ISSUE THREAD

**Issue by abrin** [sul-dlss/sul-embed#734]
Hi,
  Would it be possible to for the embed to fill both the full width (which it currently does thanks to #718 and #716) as well as the full page height?  I've attached a video (animated gif)  of how it's being used in the Stanford map libraries to better demonstrate the use case.  On a large 52 inch? screen the normal mode renders a super-tiny image.

![ezgif com-29c713f981](https://cloud.githubusercontent.com/assets/192686/21299001/6fe6f08e-c554-11e6-90de-3880c3aca269.gif)

thanks!

**Comment by jkeck** [comment]
@abrin as best I can tell, it doesn't appear that this page is using the `fullheight` option as mentioned in https://github.com/sul-dlss/sul-embed/issues/718#issuecomment-250636275.  Have you updated the page to take advantage of the new option as described in the comment linked above?

**Comment by abrin** [comment]
you're right it got dropped out, and I missed it when I was debugging, apologies.
