### ISSUE TITLE
Add support for audio/mp4 mimetype for streaming audio

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/sul-embed#737]
* add support to sul-embed for recognizing audio/mp4 as a valid audio mime type
* we also need check to ensure that wowza supports streaming of that mime/type

e.g. https://purl.stanford.edu/vd799qk9514
https://purl.stanford.edu/cp821rz8872

These objects (and possibly others?) may need to be remediate to convert the audio mimetype for the file to expected type.

**Comment by hannahfrost** [comment]
@jkeck I see you marked this ticket as in progress. This lack of support for audio/mp4 is starting to be a real issue. Have you started to look into what is involved to resolve the matter?  

It looks like Wowza supports it (https://www.wowza.com/docs/understanding-streaming-protocols-and-output-file-formats).

**Comment by jkeck** [comment]
@hannahfrost there is a PR that just needs to be merged, we can cut a release, and deploy.  Also, do we want to test this in our UAT environment first (and if so, who would do that)?

**Comment by hannahfrost** [comment]
@jkeck :metal: 

Please yes to UAT. @oceanofsound (Geoff) would be a good tester.

**Comment by peetucket** [comment]
Merged
