### ISSUE TITLE
Large image download issues

### ISSUE THREAD

**Issue by LynnMcRae** [sul-dlss/sul-embed#739]
This is a story to bring together specific examples of large image presentation issues to document them and help clarify them for further action. Here are examples of large images:

- https://purl.stanford.edu/bb023fw1977 (9499 x 7444)
   - Tōa gojūmanbun no ichi zu
- https://purl.stanford.edu/fq505jv7833 (29750 x 17785)
   - A new & correct map of the whole world
- https://purl.stanford.edu/hs631zg4177 (34342 x 22939)
   - Ōmi Kuni-ezu -- 近江國絵圖 (Japanese Tax Map)
- https://purl.stanford.edu/bf830pb0546 (45967 x 25522)
   - Carte de la Mer du Sud (The Beaver Map)
- https://purl.stanford.edu/mj244pd1157 (49752 x 58540)
   - Irrigation map of the state of California
- https://purl.stanford.edu/st808xq5141 (51754 x 34631)
   - A Chart of the World upon Mercator's Projecton [sic]
   - there is an odd overlayed image at the bottom of this which may be an issue with the original
- https://purl.stanford.edu/wq035vh2804 (5 maps, each 19400 x 14500)
   - [Atlas Geográfico de España]

Currently none of these have display issues .. the initial tiled image loads relatively quickly and zoom levels seem to operate ok.  This may be helped by the objects being fully cached after early examination. One of the above had several side tile dropouts on first display that disappeared with a page reload.

The problems seems to relate to djatoka's ability to create a .jpg file for download. From experimentation on Chrome and Safari, I observe:

- For all of these, clicking on a download link for large files, or smaller versions of very large files in Chrome takes a long time to respond, 15-45 seconds, sometimes to the point you think it's not working and do multiple clicks.  Multiple resulting dialogs from these clicks eventually show up in succession.

Files > 9-10k pixels on long edge
- In Chrome, images over 9k on an edge often get a name of "default.jpg" on download and lead to an immediate "Failed - Server problem". The download fails in Safari with a "Sorry something went wrong" page.
- In all cases, a repeated attempt, same or different browser, might lead to success, at least for <20k files..

Files > 20k pixels on long edge
- Downloads "succeed" in both browsers but create empty files.

Generally observations were clearest on first tries...caching I assume helps things along once object files get successfully referenced.

**Comment by blalbrit** [comment]
@calavano - @cbeer has noted that some of the very large image objects that they're evaluating have the old jp2-creation problem where there's a green band at the bottom. As the team discovers more of these, if they could also list them here then Tony will have a batch that you could address in bulk.

**Comment by anarchivist** [comment]
* http://purl.stanford.edu/dh543mm5405 (41271 x 58200)
  *  Map of the county of San Mateo, California

**Comment by hannahfrost** [comment]
More user reports via SDR/Searchworks feedback:

- https://purl.stanford.edu/yq456hs4727 (29043 x 17813)
- https://purl.stanford.edu/tv064pw2417 (26975 x 16711)

**Comment by cbeer** [comment]
I took a look at some of these in -uat with the newer version of Cantaloupe and Kakadu. The good news is it can reliably serve up images larger than the old version, however still falls over for very, very large images (not sure of the cutoff, but the 29043 x 17813 image was fine, the 41271x58200 very much isn't.)

Instead of trying to tweak Cantaloupe / kakadu to serve up full-res derivatives, maybe we could just add the raw JP2 as a download option for these very large files (which might make them easier to work with locally too....)?

**Comment by mejackreed** [comment]
I'm 💯 with @cbeer here for offering the JP2. @anarchivist any reason not to do that?

**Comment by anarchivist** [comment]
Let me follow up with @hannahfrost, as I want to understand potential service concerns.

**Comment by mejackreed** [comment]
Proposal based off of email discussion + @cbeer suggestion:

 - Offer the raw jp2's as downloadable
 - Try to determine and remove downloadable sizes that may cause issues

**Comment by mejackreed** [comment]
Closing this based off the 🚢 solution
