### ISSUE TITLE
UV: blank login screen

### ISSUE THREAD

**Issue by tingulfsen** [sul-dlss/sul-embed#763]
This issue refers to the "f" branch of the source code, at commit

bf416158ea920aab7abc51cf3fd7d2b7ceabcbbf

![screen shot 2017-06-26 at 11 31 43 am](https://user-images.githubusercontent.com/3740294/27562546-d5907992-5a81-11e7-810f-1a651729c6bf.png)

The login popup is blank.

Example: https://sul-purl-uat.stanford.edu/bf815tt2433

**Comment by cbeer** [comment]
I think this is missing information from the stacks API response. We filled out the required fields from the spec:

http://iiif.io/api/auth/1.0/#service-description

I'd guess UV also expects / requires the recommended fields as well.

**Comment by edsilv** [comment]
Yep, the UV is using the `header`, `description`, and `confirmLabel` to build the UI.

**Comment by mejackreed** [comment]
Resolved upstream in UV https://github.com/UniversalViewer/universalviewer/commit/6924d407dd5eea004934376f043f0fccca851843 and in stacks https://github.com/sul-dlss/stacks/commit/a5e47316afb84bd97841899f32e6bf2adf8e944e
