### ISSUE TITLE
UV: no download button

### ISSUE THREAD

**Issue by tingulfsen** [sul-dlss/sul-embed#764]
This issue refers to the "f" branch of the source code, at commit

bf416158ea920aab7abc51cf3fd7d2b7ceabcbbf

It looks like the download button is missing. Compare

https://purl.stanford.edu/bb006ys3871

and

https://sul-purl-uat.stanford.edu/bb006ys3871

(that object has no access restrictions).

**Comment by cbeer** [comment]
It doesn't look like it was enabled (either intentionally or accidentally). Other viewer classes have:

https://github.com/sul-dlss/sul-embed/blob/f/lib/embed/viewer/image_x.rb#L27-L29

@jkeck, were we hoping UV would give something to us, or should we toggle it back on?

**Comment by jkeck** [comment]
Hmm, I think this is an open design question.  If we want to support our previous download behavior, we'll need to make some modifications to how our download panel works.  The links in the panel change based on which image is being viewed (which would require some sort of interactivity with the image viewer).

Do we know if UV gives us any behavior that would be useful to evaluate for downloading?

**Comment by cbeer** [comment]
Ah, makes sense. I think they have a download button in their toolbar (which we're not using) but I'm not sure how sophisticated it is.

**Comment by cbeer** [comment]
I'll toss a design needed label on this. Clearly what we've done now was intentional, or at least an interim approach.

**Comment by mejackreed** [comment]
I think we decided to just go with what UV offers out of the box. Feel free to reopen if needed.
