### ISSUE TITLE
UV: sometimes embed window is blank

### ISSUE THREAD

**Issue by tingulfsen** [sul-dlss/sul-embed#765]
This issue refers to the "f" branch of the source code, at commit

bf416158ea920aab7abc51cf3fd7d2b7ceabcbbf

Sometimes the embed window is blank when you load an item for the first time:
![screen shot 2017-06-26 at 12 57 20 pm](https://user-images.githubusercontent.com/3740294/27563269-7f72366e-5a85-11e7-9613-2079f1ed2ed0.png)

Reloading the page fixes the problem. I've only seen this in Safari, where it seems to happen fairly often for me.

**Comment by edsilv** [comment]
This sounds like it could be that the `uvLoaded` event is firing before the DOM is ready:

https://github.com/UniversalViewer/examples/blob/gh-pages/index.html#L57

Is uv.js the last thing on your page?

https://github.com/UniversalViewer/examples/blob/gh-pages/index.html#L206

**Comment by tingulfsen** [comment]
Thanks for looking at this @edsilv - I think you may be onto something, we'll have to investigate this further.

**Comment by mejackreed** [comment]
This is resolved with some of the new ways we load UV and the requirejs fix
