### ISSUE TITLE
UV: Buttons don't work on first load PURL

### ISSUE THREAD

**Issue by snydman** [sul-dlss/sul-embed#766]
Upon reload the buttons do work.

**Comment by snydman** [comment]
Using Chrome on Mac

Open https://sul-purl-uat.stanford.edu/wv304jy9677 in a new incognito window.  Try the info or share buttons.  

Now reload and try again.

**Comment by mejackreed** [comment]
Reproduced the same issue on Chrome and Firefox

**Comment by blalbrit** [comment]
Works okay in Safari.
![git-766](https://user-images.githubusercontent.com/796990/27607045-73f49d38-5b37-11e7-9b45-ff2ae39fb079.gif)

**Comment by tingulfsen** [comment]
Reproduced in Chrome Canary (cutting edge developer version -  61.0.3142.3).

But in the latest regular Chrome it seems to work fine (version 59.0.3071.115).

**Comment by edsilv** [comment]
Ah, this isn't the UV, it's the existing sul-embed UI.

**Comment by mejackreed** [comment]
Resolved.
