### ISSUE TITLE
UV: Stanford theme does not work

### ISSUE THREAD

**Issue by snydman** [sul-dlss/sul-embed#767]
What is it and do we want / need it?

**Comment by edsilv** [comment]
This sets a few custom colours to fit with your design.

I've committed a change that I think will fix it: https://github.com/sul-dlss/uv-en-GB-theme/commit/829ec1d7a3821f4d5130451251ce0a953d4cc7fe

**Comment by cbeer** [comment]
Thanks, I've updated our UV fork to use that.
