### ISSUE TITLE
CDATA tag seems ineffective

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/sul-embed#779]
There's a nokogiri call to cdata here:
https://github.com/sul-dlss/sul-embed/blob/48654cd5826cd22e6cc5cabdb68da0fb386103b2/lib/embed/viewer/media.rb#L12

However, that doesn't appear anywhere in the source:

https://embed.stanford.edu/iframe?url=https://purl.stanford.edu/md375vb8412

Is that cdata important?

**Comment by jcoyne** [comment]
It also appears that CDATA is deprecated in HTML 5: https://developer.mozilla.org/en-US/docs/Web/API/CDATASection

**Comment by mejackreed** [comment]
I think this has since been removed. Closing the issue.
