### ISSUE TITLE
Download popup information changes to undefined

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/sul-embed#804]
DRUID: yc714xp8382
Browser: Google Chrome
Before I log in, the download box says "
After I log in, it says "Whole image undefined x undefined (jpg)". Image attached.
![screen shot 2017-08-18 at 10 20 55 am](https://user-images.githubusercontent.com/5558511/29469918-35b52f88-83ff-11e7-929d-2e2d3ce4f9e5.png)

**Comment by amyehodge** [comment]
In recreating this, I wonder if I am just clicking on the download button again too quickly after logging in and it hasn't had time to load the information? If I check a couple of seconds later it displays just fine.

**Comment by mejackreed** [comment]
I'm not seeing this happen anymore in prod. Feel free to reopen if it is happening still

**Comment by amyehodge** [comment]
I'm unable to recreate at purl.stanford.edu/yc714xp8382, but there is no login on that system. I no longer have the link for how to check this on prod.
