### ISSUE TITLE
Decide on number of file size options for download from UV

### ISSUE THREAD

**Issue by caaster** [sul-dlss/sul-embed#806]
Testing this druid: bb112zx3193. When logged in as a Stanford user, on sul-embed I have a choice of several image sizes to download, while in UV I only have 2 choices.

Stu says: "We are not going to have the same number of download choices with UV.  Fine to file a github ticket and the issue can be discussed and documented."
<img width="249" alt="screen shot 2017-08-18 at 10 23 06 am" src="https://user-images.githubusercontent.com/3210225/29472022-2ae7115e-8407-11e7-81d0-be182df8178f.png">
<img width="235" alt="screen shot 2017-08-18 at 10 23 26 am" src="https://user-images.githubusercontent.com/3210225/29472026-2d961774-8407-11e7-9103-c0dc97886968.png">

**Comment by hannahfrost** [comment]
Testing this same object today, I only have 1 file download option after login, the same file size offered before I logged in (400 x 325px). This is a sign of functionality regression.

**Comment by mejackreed** [comment]
@caaster is this still relevant or can we close now with the recent work?

**Comment by caaster** [comment]
@mejackreed - no longer relevant; closing
