### ISSUE TITLE
UV image viewer should download images when download button is clicked instead of rendering in browser

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/sul-embed#820]
### Expected behavior
When the user clicks on the "Download" button in the download panel, the selected image should download directly as a file with the original filename (as currently occurs with the non-UV image viewer).

### Actual behavior
Currently, a new window is opened and the image is rendered in the browser, forcing the user to right-click and save it.  

### Steps to reproduce the behavior
Open the download panel on an image object, and click the "Download" button for any size.

### Browser / Environment
All browsers/environments.

**Comment by peetucket** [comment]
Implementation note: the current stacks server allows this behavior to be implemented by adding a "?download=true" parameter to the end of any IIIF image url.

**Comment by mejackreed** [comment]
Resolved w/ m3
