### ISSUE TITLE
Blank pop up window and odd image viewing behavior

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/sul-embed#821]
### Expected behavior
Pop up window has explanation of what to do.
Images appear at normal zoom.

### Actual behavior
Blank pop up window
Images zoomed/cropped oddly.

### Steps to reproduce the behavior

- Visit https://sul-purl-uat.stanford.edu/fr352bj3947
- Click on page 2/3 in two page view
- Click on page 2/3 again
- Get blank pop up window. 
- Click cancel.
- Get another window saying authentication failed and to disable popups (which i already did).
- Click ok.
- See a very zoomed in version of the image that cannot be manipulated.

### Browser / Environment
Mac OS El Capitan
Opera (latest) - uses chromium

![screen shot 2017-09-07 at 10 38 42 am](https://user-images.githubusercontent.com/47137/30177073-71579f2a-93b9-11e7-8dad-cc6d8515e474.png)
![screen shot 2017-09-07 at 10 42 17 am](https://user-images.githubusercontent.com/47137/30177079-7681d970-93b9-11e7-958a-a58e23fc65ac.png)

**Comment by snydman** [comment]
@aeschylus and I discussed a solution that would disable the user's ability to click on thumbnails other than the first until they authenticate. Given the complexity of solving this bug, I consider this a reasonable stop-gap. This may actually put us in more complete compliance with guidelines related to thumbnail access. For multipage objects, only a single thumbnail can be considered metadata.

**Comment by snydman** [comment]
see also

![multicanvasauthbuguv](https://user-images.githubusercontent.com/3279382/30567487-80d6431e-9c85-11e7-9804-da79e631f3a4.gif)

**Comment by snydman** [comment]
A fix has been applied to this.  It doesn't fully solve it but populates the pop-up to communicate instructions to the user 

see: https://user-images.githubusercontent.com/1656824/30627752-1717aece-9d87-11e7-83a3-4dceae6f0bbd.gif
