### ISSUE TITLE
Blank white page shown on PURL instead of seeing sul-embed player

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/sul-embed#822]
### Expected behavior
See the sul-embed player

### Actual behavior
Blank white box

### Steps to reproduce the behavior
Visit https://sul-purl-uat.stanford.edu/bb066bf1599

### Browser / Environment
Mac OS El Capitan
Opera (latest)
Firefox (latest)
Safari (latest)

![screen shot 2017-09-07 at 10 46 57 am](https://user-images.githubusercontent.com/47137/30177184-e20a95e2-93b9-11e7-849d-98d1c0233311.png)

**Comment by hannahfrost** [comment]
@peetucket I think that this object is not properly formed, which is leading to the unwanted display behavior. I'm going to remove this object from the test set of PURLs and close this ticket. We know that this content needs remediation!

**Comment by cbeer** [comment]
The object has:

```
<access type="read">
  <machine>
    <none/>
  </machine>
</access>
```

Maybe that deserves a special case in sul-embed?
