### ISSUE TITLE
The download panel for images with Stanford / World no-download rights restricts authenticated downloads to 400px long edge

### ISSUE THREAD

**Issue by cbeer** [sul-dlss/sul-embed#828]
### Expected behavior

After authenticating as a Stanford user, I expect to be able to download the full image or large crops from the image.

### Actual behavior

After authenticating, my downloads are still limited to 400px long edge thumbnails.

### Steps to reproduce the behavior

Visit https://purl.stanford.edu/bb000kq3835

Click "Log in" and authenticate

Get no additional download options.

After refreshing the page, the additional download options appear.

### Browser / Environment

![ezgif com-optimize](https://user-images.githubusercontent.com/111218/30867293-68246a06-a290-11e7-8476-a56a0034579d.gif)

**Comment by mejackreed** [comment]
This is resolved with the new Mirador viewer.
