### ISSUE TITLE
Downloadable PDFs in Image Objects are no longer downloadable

### ISSUE THREAD

**Issue by blalbrit** [sul-dlss/sul-embed#841]
see also : https://github.com/sul-dlss/purl/issues/193

The old sul-embed provided for the possibility of downloading of files associated with a book or image object (full-text XML, PDF, etc.). That is - the primary display would be an image viewer, but the download options included associated non-image objects.

The current implementation of UV no longer provides this critical functionality.

See, for instance, any object in: https://searchworks.stanford.edu/catalog?f%5Bcollection%5D%5B%5D=357970 .

If we go to one of these objects - https://searchworks.stanford.edu/view/xt162pg0437 - we see that UV offers the standard image viewing environment we would expect. However, the additional files that are available with this object in stacks are not offered to the user in the Download button:
![screenshot 2017-10-24 09 53 09](https://user-images.githubusercontent.com/796990/31956770-4f213526-b8a1-11e7-8610-6057b11ceba6.png)

When we go to the public XML - https://purl.stanford.edu/xt162pg0437.xml - we can see the PDF is available and just not offered to the user:
![screenshot 2017-10-24 09 54 46](https://user-images.githubusercontent.com/796990/31956833-93ef0eee-b8a1-11e7-97a7-f82598abe6c6.png)

Browser / Environment: all.

cc. @snydman @LynnMcRae

**Comment by snydman** [comment]
See rows 40-54 of 

https://docs.google.com/spreadsheets/d/1ud5kM_wNLAsRQCdkfqFtzZAwqRHHjE-dwTFh-QNw-sM/edit#gid=197628797

...for examples.

**Comment by snydman** [comment]
We want behavior similar to this 

https://wellcomelibrary.org/item/b1948799x#?c=0&m=0&s=0&cv=0&z=-0.8268%2C-0.0833%2C2.6536%2C1.6669

![image](https://user-images.githubusercontent.com/3279382/32512015-663fe414-c3aa-11e7-9820-7b2733d585d7.png)

**Comment by LynnMcRae** [comment]
Example of PURL with a non-PDF object download (XML) - https://purl.stanford.edu/bb962tm5458 (and other Walters objects)
```
<resource type="object" sequence="361" id="file-1">
     <label>Descriptive Metadata</label>
     <file mimetype="application/tei+xml" format="XML" size="136109" id="W631_tei.xml"</file>
</resource>
```

Example of a PURL with three download files -- https://purl.stanford.edu/bg262qk2288 (and all other AP objects)
```
<resource type="object" sequence="1" id="bg262qk2288_1">
     <label>Object 1</label>
     <file id="bg262qk2288.pdf" mimetype="application/pdf" size="2218576614"></file>
     <file id="bg262qk2288.rtf" mimetype="text/rtf" size="13093220"></file>
     <file id="bg262qk2288.xml" mimetype="application/xml" size="6885684"></file>
</resource>
```

With thanks to Ben, who adds: ...also, many labs projects have PDF + .txt or .xml for the object download. Tony Calavano might have knowledge of good examples.

**Comment by hannahfrost** [comment]
As of today, this issue appears to be resolved in production and in UAT: https://purl.stanford.edu/xt162pg0437
