### ISSUE TITLE
Allow for an external (to the manifest) search service to be passed to UV

### ISSUE THREAD

**Issue by jkeck** [sul-dlss/sul-embed#843]

**Comment by cbeer** [comment]
"Allow" might be going too far; maybe "Analyze if it's possible"?

**Comment by mejackreed** [comment]
I'm not sure what is the aim of this, can you say more? Does UV need to support a search service that is passed in that is not part of the manifest?

We have the ability in embed now to pass through different supported UV params: https://github.com/sul-dlss/sul-embed/pull/842

**Comment by jkeck** [comment]
@mejackreed yes, you have the aim correct.  This would be in a holding pattern for now, because we need to determine our exact approach with the content search service in general.

If we don't end up generating all or a subset of our manifests with the search service url, we'll need a way to initialize UV w/ a search service (understanding that this may not be a feature that exists currently in UV).

And apologies for the not-as-clear-as-could-be issue.  This was hastily created in a planning meeting when we were doing a bunch of ticketing.

**Comment by mejackreed** [comment]
Gotcha and understood. No worries about the original intent, I was just curious. I wonder if this is too big of an ask for UV, could a stand in solution be a configuration in PURL that added the search service for a whitelisted group of druids.

**Comment by anarchivist** [comment]
We've decided not to go this route, so closing for now.

**Comment by mejackreed** [comment]
I'm wondering if its worth leaving this issue open. Perhaps its not relevant for a current project, but I could see this being utilized elsewhere.
