### ISSUE TITLE
OkComputer getting exceptions back from geowebservices check

### ISSUE THREAD

**Issue by drh-stanford** [sul-dlss/sul-embed#851]
### Expected behavior

The /status/all OkComputer check should ping the GeoServer webservice with a valid response.

Here's an example of a WMS query with a valid response (a PNG image):

https://geowebservices.stanford.edu/geoserver/wms?SERVICE=WMS&REQUEST=GetMap&VERSION=1.1.1&LAYERS=druid%3Azv296hf8888&STYLES=&FORMAT=image%2Fpng&TRANSPARENT=true&HEIGHT=256&WIDTH=256&TILED=true&CRS=EPSG%3A900913&DETECTRETINA=false&SRS=EPSG%3A3857&BBOX=-13775786.985667603,3757032.814272983,-12523442.714243276,5009377.08569731

### Actual behavior

The /status/all check gets back a 200 OK, but the XML in the payload is an exception

```
<ServiceExceptionReport xmlns="http://www.opengis.net/ogc" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="1.3.0" xsi:schemaLocation="http://www.opengis.net/ogc https://geowebservices.stanford.edu:443/geoserver/schemas/wms/1.3.0/exceptions_1_3_0.xsd">
<ServiceException code="MissingParameterValue" locator="request">
Could not determine geoserver request from http request org.geoserver.platform.AdvancedDispatchFilter$AdvancedDispatchHttpRequest@7c2400d6
</ServiceException>
</ServiceExceptionReport>
```

### Steps to reproduce the behavior

Run a /status/all check and this line will trigger the check:

https://github.com/sul-dlss/sul-embed/blob/master/config/initializers/okcomputer.rb#L34

### Browser / Environment

n/a

**Comment by mejackreed** [comment]
This seems to be resolved.
