### ISSUE TITLE
UV truncates toolbars when exiting fullscreen; upstream escalation needed

### ISSUE THREAD

**Issue by caaster** [sul-dlss/sul-embed#953]
Please navigate to:
https://frda.stanford.edu/en/catalog/dd524ms4380

In both Chrome and Firefox, when I click on the "full screen" icon, the ability to navigate disappears and the user is stuck. 

The bottom toolbar on the viewer disappears and the viewer does not expand to full screen. 

The back button of the browser will not take the user back to: https://frda.stanford.edu/en/catalog/dd524ms4380

**Comment by camillevilla** [comment]
One additional point to clarify @caaster : I'm not sure I understand what you mean by: 
> frozen (un-navigable)

I'm still able to pan around the canvas and select additional thumbnails from the contents sidebar. Do you mean the top, bottom, and More Information toolbars are not accessible?

**Comment by caaster** [comment]
Yes @camillevilla that is what I mean. Thanks for helping to clarify my imprecise description!

**Comment by cbeer** [comment]
Obsolete!
