### ISSUE TITLE
ETDs with CC license declaration of "none" are displaying human readable stanza which shouldn't appear

### ISSUE THREAD

**Issue by caaster** [sul-dlss/sul-embed#973]
### Expected behavior
When no Creative Commons license has been declared for an ETD in the rightsMetadata datastream, no human readable license declaration should display in sul-embed when a user clicks on the information icon. This is an example of the rightsMetadata declaration in question:

![Screen Shot 2019-04-29 at 2 42 28 PM](https://user-images.githubusercontent.com/3210225/56928906-0d71b700-6a8d-11e9-8518-3c561831ca46.png)

### Actual behavior
This is what is currently displaying in sul-embed when a user clicks on the information icon, when an ETD has the rightsMetadata declaration as shown in the screenshot above.

![Screen Shot 2019-04-29 at 2 40 05 PM](https://user-images.githubusercontent.com/3210225/56928776-b835a580-6a8c-11e9-82ff-2e807f3916c4.png)

### Steps to reproduce the behavior
Are listed above.

### Browser / Environment
This is N/A.

There are 725 ETDs currently effected by this problem. They can be found in Argo by first faceting on Admin Policy = ETDs, and then faceting on License = none.

**Comment by jcoyne** [comment]
We no longer have a "none" license type. This is no longer an issue.
