### ISSUE TITLE
Disable Download menu item when canvas has no associated image

### ISSUE THREAD

**Issue by ggeisler** [sul-dlss/sul-embed#985]
Part of #981.

If the item has nothing to download (e.g., no canvas image and no `rendering` property in the manifest):

- [ ] Disable the "Download" link in the Window options menu:

<img width="424" alt="Screen Shot 2019-05-16 at 2 02 03 PM" src="https://user-images.githubusercontent.com/101482/57886982-41fea600-77e3-11e9-917f-02ad1f7fe94c.png">

**Comment by jkeck** [comment]
@ggeisler do you happen to have an example manifest that has this kind of canvas?

**Comment by ggeisler** [comment]
@jkeck Try these that are listed in the fixtures: https://github.com/ProjectMirador/mirador/wiki/M3-Fixtures-&-sample-IIIF-data#canvases-with-no-image-or-any-resources

**Comment by cbeer** [comment]
Deprioritized for sul-embed, and pushed to the plugin repo.
