### ISSUE TITLE
Add Share link section to Share dialog

### ISSUE THREAD

**Issue by ggeisler** [sul-dlss/sul-embed#988]
Part of #986.

The Share link section is intended to look something like:

<img width="622" alt="Screen Shot 2019-05-16 at 5 33 22 PM" src="https://user-images.githubusercontent.com/101482/57895493-ca3f7400-7800-11e9-8281-9e30d2e2949c.png">

- [x] Add a textfield, populated with the URL of the object's PURL page.
- [x] Add a label "Share link URL" for the textfield, but make it **screenreader-only**.
- [x] Add a "Copy" [outlined button](https://material-ui.com/demos/buttons/#outlined-buttons) that when selected will copy the URL in the textfield to the user's clipboard.
- [x] ~~Add Facebook and Twitter icons, each which is linked to share the link via those companies' service. See the Share option on a Youtube page as an example.~~ See ProjectMirador/mirador-share-plugin#5

**Comment by jkeck** [comment]
@ggeisler/@jvine WRT this task:
> Add a label "Share link URL" for the textfield, but make it screenreader-only.

Is putting an `aria-label` on the `<input />` reasonable?  That's what MUI example does for the input w/o a visible label.

**Comment by jvine** [comment]
Huh. I’d have said yes off the bat, but then I found this:  https://www.powermapper.com/tests/screen-readers/labelling/input-text-aria-label/

Sigh. Should we be more robust in this one instance, or remain consistent with MUI? Leaning toward the latter I think. Gary?

**Comment by ggeisler** [comment]
I suspect we might have more than one instance of this in the future (i.e., search panel might have an input with hidden label) but not sure that really helps make a decision. From that web page JV found it looks like the support for the `aria-label` support is improving and fails in pretty limited cases, so I'd be comfortable sticking with the MUI approach.
