### ISSUE TITLE
Configure SUL theme for Mirador 3 viewer

### ISSUE THREAD

**Issue by ggeisler** [sul-dlss/sul-embed#991]
At least as a starting point (we might want to adjust after seeing the viewer in the context of all of our applications), here's the color theme:

```
    SUL: {
      palette: {
        type: 'light',
        primary: {
          main: '#8c1515',
        },
        secondary: {
          main: '#8c1515',
        },
        shades: {
          dark: '#2e2d29',
          main: '#ffffff',
          light: '#f4f4f4',
        },
        notification: { 
          main: '#e98300'
        },
      }
    },
```

That theme should look like this:

<img width="953" alt="Screen Shot 2019-05-17 at 11 37 43 AM" src="https://user-images.githubusercontent.com/101482/57949268-c7905d80-7898-11e9-802d-5de84a9b4ff8.png">

**Comment by mejackreed** [comment]
@ggeisler Should we have any concern here that our sul-embed image viewer will have a different chrome/color scheme than the other embedded content types? Or will we eventually migrate all of that too?

**Comment by ggeisler** [comment]
@mejackreed Yeah @jkeck brought this up to me last week and I discussed with @jvine a little while ago. While not ideal, we don't think this is going to be a problem worth worrying about. 

It will point out (at least to users who register the difference, which might not be most users) that we are using different viewers for other types of content, but that is probably not that big of deal, and eventually we'll have everything in M3 and looking consistent.

When we get the new M3 embed viewer with the lighter theme added to SW, PURL, exhibits, etc., if the visual difference does seem to be a bigger issue than we currently think it will be, we can always change the M3 theme to a darker one (I have one defined already), which isn't much effort I don't think. So we'd rather move to the lighter theme now even though we understand there will be some visual inconsistencies for some period of time based on media types.

**Comment by mejackreed** [comment]
Sounds good!

> and eventually we'll have everything in M3 and looking consistent

For images, pdf, and 3d perhaps. But we still may not have that for geo and web archive. Just noting this for future reference.
