### ISSUE TITLE
Configure default settings for Mirador 3 viewer

### ISSUE THREAD

**Issue by ggeisler** [sul-dlss/sul-embed#992]
Below are the configuration settings to use for the Mirador 3 viewer that are different from the default settings. 

`window` settings

```
window: {
    allowClose: false, 

    defaultSideBarPanel: 'attribution', 

    sideBarOpenByDefault: true, 
  },
```

`workspace` settings

```
showZoomControls: true,
```

`workspaceControlPanel` settings

```
enabled: false,
```

Those settings should give us something like this on initial load of the viewer:

<img width="953" alt="Screen Shot 2019-05-17 at 11 37 43 AM" src="https://user-images.githubusercontent.com/101482/57949911-8e58ed00-789a-11e9-9860-9ce5e2c512d1.png">

Note that we might want to revisit the default side panel settings (open to the Rights panel) with Hannah, given the new viewer, to see whether she still thinks we need to have the Right info visible on initial load of the viewer.

Also, I created a [Mirador 3 issue](https://github.com/ProjectMirador/mirador/issues/2623) to add a configuration setting to enable hiding the window title in the title bar. Assuming that is implemented, I think we'd also want to set the title display off:

```
window: {
   hideWindowTitle: true, 
}
```

**Comment by mejackreed** [comment]
@ggeisler I'm assuming we will want `allowMaximize: false` and `allowFullscreen: true` once https://github.com/ProjectMirador/mirador/pull/2641 is shipped.

**Comment by ggeisler** [comment]
@mejackreed Yep, that make sense.
